### ISSUE TITLE
여성자켓에 대한 설명과 이미지를 추가

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#100]
대여품목을 고를때 모든 여성의 자켓은 유사하므로 설명과 사진을 미리 보여주어야 합니다

**Comment by aanoaa** [comment]
어디에 어떤 설명과 사진이 들어가야 하는지 알아야 합니다.

**Comment by 10001if** [comment]
http://opencloset1.godo.co.kr/shop/data/goods/info/women/suit.JPG

자켓과 스커트가 함께 있는 사진 (3번째 이미지)를 보여주면 됩니다. 
![2017-03-18 5 22 00](https://cloud.githubusercontent.com/assets/4696328/24070369/71ee6910-0bff-11e7-8084-ddd6dc98b267.png)

위치는 품목을 선택할 때 보여지면 될 듯합니다.

**Comment by aanoaa** [comment]
![2017-05-04 17-49-28](https://cloud.githubusercontent.com/assets/170528/25696412/0e5acfb6-30f2-11e7-939e-c91f6e6774ab.png)

이미지 링크를 누르면 자켓 이미지가 레이어팝업 형식으로 나타납니다.

**Comment by pingpongworks** [comment]
확인했습니다
