### ISSUE TITLE
자켓사이즈, 스커트 사이즈에 이미지 가이드를 추가

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#101]

**Comment by aanoaa** [comment]
고도몰 쇼핑몰에 이미지가 있었는데 지금은 모든 상품이 내려가 있어서 이미지를 참고할 수 있는 방법이 없습니다.
해당 이미지 파일이 필요합니다.

**Comment by 10001if** [comment]
http://opencloset1.godo.co.kr/shop/data/goods/info/women/suit.JPG

**Comment by 10001if** [comment]
@aanoaa 여기서 참조 부탁드립니다~ ^^

**Comment by 10001if** [comment]
![2017-03-18 5 19 35](https://cloud.githubusercontent.com/assets/4696328/24070356/2e24175c-0bff-11e7-952a-50b09d3f231f.png)
이 이미지가 들어가면 되구요. 이 이미지는 사이즈 고르는 화면 위 쪽에 위치해 있으면 됩니다.

**Comment by pingpongworks** [comment]
확인했습니다~
