### ISSUE TITLE
고도몰로 주문이 들어옴

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#105]
- footer의 '온라인 예약' 링크가 online.theopencloset.net
- online.theopencloset.net 이 고도몰로 연결됨

--------------------------

더이상 고도몰을 운영하지 않을 것이라면, 도메인 관리를 하거나 share 로 redirect 되도록 해야합니다.

**Comment by 10001if** [comment]
고도몰을 운영하지 않을 계획입니다. 리다이렉트 되도록 요청드립니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Story-Web/issues/48

이슈에서는 노출된 online 주소 대신에 share 를 사용하도록 하고 있습니다.
노출된 주소를 변경하더라도, `online.theopencloset.net` 으로 접속하면 share 로 연결해주는 기능이 필요합니다.

도메인 관리는 제가 하고 있지 않습니다.
cc @yongbin

**Comment by yongbin** [comment]
현재 동작은 `online.theopencloset.net` 에 접속하면 `미즈호스트`(http://www.mizhost.com)의 포워딩 서비스로 연결된 뒤(121.78.127.169) 이쪽 설정에 따라 `share.theopenclsoet.net`으로 연결되도록 설정되어있습니다. 확인해보고 이 동작이 맞다면 간단하게 CNAME을 이용해서 `online.theopencloset.net` 으로 접속시 `share.theopencloset.net`으로 연결되도록 변경하겠습니다.

**Comment by yongbin** [comment]
### 변경전

```
; <<>> DiG 9.8.3-P1 <<>> online.theopencloset.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2197
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;online.theopencloset.net.	IN	A

;; ANSWER SECTION:
online.theopencloset.net. 600	IN	A	121.78.127.169

;; Query time: 286 msec
;; SERVER: 192.168.10.1#53(192.168.10.1)
;; WHEN: Wed Mar 22 14:24:31 2017
;; MSG SIZE  rcvd: 58
```

### 변경후

```
; <<>> DiG 9.8.3-P1 <<>> @151.80.120.8 online.theopencloset.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50674
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;online.theopencloset.net.	IN	A

;; ANSWER SECTION:
online.theopencloset.net. 600	IN	CNAME	share.theopencloset.net.

;; Query time: 426 msec
;; SERVER: 151.80.120.8#53(151.80.120.8)
;; WHEN: Wed Mar 22 15:02:32 2017
;; MSG SIZE  rcvd: 62
```

A 레코드의 TTL이 600초였기때문에 반영에 통상적으로 10분정도 끊어짐이 있을수 있습니다.
