### ISSUE TITLE
부분취소 했을 경우에 품목변경을 할 수 있어야 함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#106]
블라우스 취소후에 대여품목이 다르기때문에 `선택한 의류를 대여합니다` 버튼을 눌렀을때에 오류가 발생합니다.

**Comment by aanoaa** [comment]
결제 후 상황인 것 같습니다.

주문품목과 대여품목이 다르더라도 대여할 수 있도록 하는 기능입니다.
다를 경우에 staff 에게 다르다는 것을 인지시켜주고, 그럼에도 계속 진행할지 여부를 결정할 수 있도록 해야 합니다.

**Comment by 10001if** [comment]
orders/55136/purchase 제가 실제로 주문해서 진행해 보았는데요. 셔츠만 주문하고 자켓 셔츠를 대여했는데, 그냥 자켓은 사라지고 셔츠만 대여중으로 바뀌었습니다. 월요일에 본 기능에 대한 설명을 좀 부탁드릴게요~ 제가 잘 이해를 못한 것 같습니다. @aanoaa

**Comment by 10001if** [comment]
@aanoaa 내일 오시면 이 기능 설명 요청드리겠습니다. ^^

**Comment by aanoaa** [comment]
주문한 품목중에서 어떤 품목을 제외하고 대여하는건 고려했지만, 주문하지 않은 품목을 대여하는건 고려하지 않았습니다.
어떻게 동작할지는 확인해봐야 합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
