### ISSUE TITLE
게시판의 생성

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#109]
대여자가 문의를 할 수 있는 창구가 필요합니다. 어느 곳에 어떻게 필요한지는 고민이 필요합니다. 고민 후 다시 남기도록 하겠습니다.

**Comment by aanoaa** [comment]
어디에 어떤식으로 필요한지 남겨주세요.

**Comment by 10001if** [comment]
@aanoaa 온라인 기획 시점에는 필요할 것으로 예상되었지만, 구체적으로 필요한 내용이 무엇인지는 정리되지 않았습니다. 그리고 정말 필요한 기능인지는 조금 더 생각해 볼 필요가 있어 보입니다. 우선 이슈 닫도록 하겠습니다.
