### ISSUE TITLE
체결된 주문서 목록

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#11]
결제가 끝난 주문서들에 대해 포장할 수 있도록 목록이 필요합니다.
사용자가 직접 의류를 골랐다면 매칭시켜 주고, 아니라면 추천의류를
보여주어야 옷을 고르기에 수월할 것 같습니다.

추가로 선택된 의류가 없을때에 사용자에게 적절한 SMS 를 보낼 수 있는
기능같은게 있으면 좋겠습니다.

**Comment by aanoaa** [comment]
온라인 주문서에 의해서 의류가 `발송대기`가 되었는데,
오프라인주문서에 의해 `대여중`으로 변경될 가능성이 있습니다.

이미 누군가가 탈의실에서 입고있던 옷이라던지
이미 포장중 혹은 결제대기 중이던 옷이라던지

선택한 의류의 상태를 목록에 나타내주어야 하겠습니다.

**Comment by aanoaa** [comment]
주문서 상태에 따른 목록이 필요합니다.
온라인 주문서만 보여져야 합니다.

- 결제완료
- 입금확인
- 발송대기
- 배송중
- 배송완료
- 반송신청
- 반납

**Comment by aanoaa** [comment]
staff 의 액션이 상태마다 필요합니다.

    결제완료 -> 입금확인

은 필요가 없을 수도 있습니다.
결제완료 상태를 곧 입금이 된 것으로 본다면 말이죠.

현재 기증서비스의 목록과 비슷하게 처리될 것 같습니다.

**Comment by aanoaa** [comment]
기증서비스는 한명이 전담하고 있고, 반송건수가 그리 많지 않기 때문에, 사용자가 요청한
날짜에 택배사에 대신 반송신청을 하고 있습니다.

이것이 온라인서비스에도 같이 적용되긴 어렵지 않을까 합니다.
대신 반송신청을 하지 않고, 대여자가 택배사에 직접 반송신청할 수 있도록 유도/안내 해야
합니다.

**Comment by aanoaa** [comment]
결제완료된 주문서의 상세화면

- 대여자의 신체정보를 한눈에 볼 수 있어야 함
- 대여자의 최근 대여이력을 볼 수 있어야 함
- 추천의류가 나타나야 함
- 바코드를 찍을 수 있어야 함
- 대여기간을 설정 할 수 있어야 함
- 포장완료 버튼이 있어야 함

**Comment by aanoaa** [comment]
- 담당자
- 대여기간
- 대여일
- 반납예정일
- 반납희망일
- 대여비
- 연체/연장료

등에 대한 정보가 추가로 표시되면 좋을 것 같습니다.

**Comment by aanoaa** [comment]
주문옵션에 대여기간옵션이 없습니다.
반납희망일이 필요가 없습니다.

언제 착용해야 하는지를 알 수 있다면, 좀 더 효율적으로 옷을 보내고 받을 수 있을 것
같습니다.

착용일에 대한 옵션이 없기 때문에, 5일뒤에 입을 건데 미리 주문해버리면 문제가 발생할 수
있습니다. 지금 당장 주문을 하더라도, 4일뒤에 택배로 받을 수 있도록 된다면 그게 가장 좋을
것 같습니다.

**Comment by aanoaa** [comment]
포장단계에서 대여일과 반납예정일등을 나타내고 싶은데,
무엇을 기준으로 해야 할까요?

결제를 2016-08-01 23:00 에 했다고 가정하면,
포장은 업무시간인 2016-08-02 10:00 이후에 될텐데
대여일은 지금 날짜를 기준으로 하는게 좋을까요?
반납예정일은 지금날짜 + 4박5일이 될테고요.

**Comment by aanoaa** [comment]
포장을 18:00 이후에 해서 택배가 익일 출발하게 된다면 대여일은 오늘이 아니라 내일이 되어야
하겠습니다.

이 기준을 어떻게 하는게 좋을까요?

**Comment by aanoaa** [comment]
대여일을 기본으로 오늘로 하되 수정할 수 있도록 하겠습니다.
수정이 되면, 대여기간도 알아서 바뀌어야 하겠지요.

**Comment by aanoaa** [comment]
대여일에 관련해서 오늘로 예를 들겠습니다.
오늘이 `2016-09-01`

대여일은 +1 일 반납예정일은 +5 일

대여일: `2016-09-02`
반납예정일: `2016-09-06`

**Comment by aanoaa** [comment]
배송비에 대해 생각을 안해봤군요.
@10001if 배송비는 어떻게 해야 할까요?

**Comment by 10001if** [comment]
배송비는 일괄 3,000원입니다. 반송시에는 자신이 선불로 지불하고 반납합니다.

**Comment by aanoaa** [comment]
몇만원 이상 무료배송 이런거 없나요?

**Comment by aanoaa** [comment]
배송비와 관련된 논의는 아직까지 없었다고 합니다.
모두 3,000 원으로 생각하겠습니다.

**Comment by aanoaa** [comment]
운송장, 코멘트를 입력할 수 있습니다.
위에 언급된 대부분의 내용이 완료되었습니다.
