### ISSUE TITLE
사이즈를 임의로 변경하였을 때 추천의류가 갱신되지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#110]
대여자가 사이즈를 잘못 입력 하였을 경우, 사용자 정보에서 사이즈를 수정 하여도 주문서 추천의류가 의류가 추천되지 않습니다. 수정이 필요해 보입니다.

**Comment by aanoaa** [comment]
실제 링크를 알려주세요.

**Comment by 10001if** [comment]
~orders/54223/purchase 입니다~

**Comment by aanoaa** [comment]
![aaa](https://cloud.githubusercontent.com/assets/170528/23936392/4ada86ae-0995-11e7-8705-701aaab7e7ef.png)

위 사이즈로 추천의류가 검색되는지 알아봐야 합니다.

**Comment by aanoaa** [comment]
GET /clothes/recommend.json?order_id=54223
    []

신체치수를 변경했지만 실제로 검색결과가 없는 케이스 같습니다.

**Comment by 10001if** [comment]
@aanoaa 비슷한 문제가 발생했을 때 다시 한번 확인해보고 말씀드리도록 하겠습니다.
