### ISSUE TITLE
배송주문서목록의 발송예정일별 검색이 오작동

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#113]
예를 들어 2017-03-08(발송예정일)을 누르면 2017-03-08의 모든 주문서가 보여야 함에도 전부 보이지 않습니다. 전체에서 보았을 때에는 4개인데 03-08을 누르면 3개만 보입니다. 아마도 의류착용일과 연관이 있는 것이 아닌가 싶습니다. 3개는 착용일이 03-11인데 하나는 03-12입니다. 이 때문에 발생하는 것 같습니다. 발송예정일이 가장 중요하므로 발송예정일이 동일하면 모두 보일 수 있도록 수정 요청드립니다.

**Comment by aanoaa** [comment]
발송 예정일이 전부 보이지 않음

**Comment by aanoaa** [comment]
![2017-03-16 16-22-54](https://cloud.githubusercontent.com/assets/170528/23985908/d65dfaec-0a64-11e7-95f6-a4a35981feb1.png)

관리메뉴 - 배송주문서의 위 사진을 말하는 것 같습니다.
날짜에 링크가 걸려있습니다.

    /orders/shipping?wearon_date=2017-01-29

배송예정일인데 query parameter 가 `wearon_date` 입니다.
잘못된 링크문제인 것 같습니다.

**Comment by aanoaa** [comment]
저 기능이 추가될때는 발송예정일을 가지고 의류착용일을 계산할 수 있었습니다.(#81)
하지만 계산에 오류가 발견되어서 수정하였습니다.

발송예정일만 가지고는 의류착용일을 확정할 수 없습니다.
가장 가까운 가능한 의류착용일을 알아낼 수 있을 뿐입니다.

    # 발송(예정)일 = 주말 + 공휴일 + 0일    # AM 10:00 이전
    # 발송(예정)일 = 주말 + 공휴일 + 1일    # AM 10:00 이후
    # 도착(예정)일 = 발송(예정)일 + 공휴일 + 주말 + 2일
    # 의류착용일   = 도착(예정)일 + 1일

**Comment by aanoaa** [comment]
발송예정일은 의류착용일로 부터 계산해서 알아낼 수 있는 값 입니다.
저장해놓은 값이 아니라서 발송예정일을 범위로한 주문서 검색은 할 수 없습니다.

링크를 제거하도록 하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 그럼 앞으로는 의류착용일을 클릭해서 정렬을 진행하면 되는건가요?

**Comment by aanoaa** [comment]
의류착용일별 검색은 가능하지만 배송예정일별 검색은 안됩니다.

**Comment by 10001if** [comment]
그럼 의류착용일이 토요일(25일), 일요일(26일)이라 금요일(24일)날 택배를 배송 받아야 하는 경우이므로 배송예정일이 수요일(22일)입니다. 종전에는 22일을 누르면 착용일 기준으로 25일 목록만 보이거나 26일 목록만 보였는데요. 앞으로는 착용일 25일을 누르거나 착용일 26일을 눌러 확인해야 한다는 말씀인가요~?

**Comment by aanoaa** [comment]
네 말 그대로 배송예정일로는 검색할 수 없습니다.

왜냐면,

1. 배송예정일은 저장하고 있는 값이 아니고 의류착용일로부터 계산해서 나오는 값 이고,
2. 배송예정일이 같다고 의류착용일이 같지는 않기 때문에

**Comment by 10001if** [comment]
네. 이해했습니다. 
제가 걱정했던 부분은 목록이 많아지면 당일 발송해야할 주문서를 놓치게 되는 일이 발생할 수도 있지 않을까 하는 것이었는데요. 현재로 당일은 초록색으로 표시해 주고 계시지만, 면적이 작아, 실수가 발생할 여지가 있는 것 같습니다. 당일 발송 목록을 한번에 모아서 보기 힘들다면 다음과 같이 조금 더 분명하게 표시를 해주면 좋을 것 같습니다. ^^
![2017-03-23 3 39 25](https://cloud.githubusercontent.com/assets/4696328/24235159/50b27b90-0fdf-11e7-8f76-a41873e18a0c.png)

**Comment by 10001if** [comment]
@aanoaa 오늘이 27일이라고 감안했을 때 모습입니다.

**Comment by 10001if** [comment]
@aanoaa 당장 중요한 이슈는 아닌 듯 합니다. 나중에 문제가 발생되면 다시 이슈에 요청 드리겠습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
