### ISSUE TITLE
신체치수를 보다 쉽게 입력할 수 있도록 안내

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#114]
저의 아이디어 입니다.

- 허리 치수의 비교 표를 나타냅니다. (inch 와 cm)
- 키/몸무게/허리 를 입력하고 나면 나머지 부위의 평균 사이즈를 보여줍니다.
- 입력값이 많을 수록 평균값이 정확해 집니다.
- 입력하는 순서는 중요도순입니다.
  - 키
  - 몸무게
  - 허리
  - 배둘레
  - 윗배둘레
  - ...
- 평균사이즈를 활용할 수 있는 팁을 많이 남겨 놓습니다.
  - 예) 배가 나온 체형은 허리둘레보다 배둘레가 큽니다.
  - 예) 대부분의 경우 팔길이는 비슷합니다.

--------------------

물론 자신의 신체치수를 정확히 알고 입력하는게 Best 겠지만,
지금은 신체치수를 입력하지 않으면 대여를 할 수 없도록 되어 있기 때문에,
신체치수입력을 쉽게 할 수 있도록 도와주는 것이 사용률을 높이는 방법이 아닐까 합니다.

중요도와 우선순위 모두 높은 이슈라고 생각합니다.
의견이 필요합니다.

**Comment by 10001if** [comment]
신체 치수 입력 란에 센치 인치 변환 계산기 있는 건, 너무 과한 생각 일까요? 그리고 센치 인치가 헷갈릴 수 있으니 입력란 우측에 단위를 표기해 주면 좋을 것 같습니다.

**Comment by aanoaa** [comment]
![2017-03-09 15-27-06](https://cloud.githubusercontent.com/assets/170528/23738526/e1fee9b6-04dc-11e7-849b-0214a376c7b0.png)

입력 단위는 이미 표시해주고 있습니다.

**Comment by aanoaa** [comment]
![2017-03-09 16-07-07](https://cloud.githubusercontent.com/assets/170528/23739506/7975aa46-04e2-11e7-8090-c431db586260.png)

**Comment by aanoaa** [comment]
키/몸무게/성별을 가지고 신체치수를 추정할 수 있는 기능이 있습니다.
이 기능에 각 신체치수를 더 입력해서 더 정확한 결과를 받고 싶습니다.

신체치수를 더 입력한다고 더 정확한 결과가 나오는 것은 아니라고 합니다.

https://github.com/opencloset/opencloset/issues/608#issuecomment-216100182

`OpenCloset::Size::Guess::OpenCPU::RandomForest` 에 비슷한 기능이 있는데,
속도가 6~7초 정도 걸리고 결과에 치수가 빠져있는 것도 있습니다.

**Comment by 10001if** [comment]
> 신체치수를 더 입력한다고 더 정확한 결과가 나오는 것은 아니라고 합니다.

정말 그런가요? 키/몸무게를 가지고 사람 치수를 추론하는게 타당하지 않다는 건 @yongbin 이야기를 통해 이해했는데요. 신체치수를 더 입력하면 더 정확한 결과가 나오는게 왜 아닌지 궁금합니다. ㅠ

**Comment by 10001if** [comment]
2. 멘트 수정할 것
* 가슴둘레 
(남자) 양팔을 들어올려 줄자를 겨드랑이 가장 윗부분에 끼운 후 양팔을 내려 수평 둘레를 측정한다.
(여자) 가슴의 가장 두꺼운 부분의 둘레를 수평으로 측정한다.
 
* 윗배둘레 -> ’ 열린옷장만의 특별한 사이즈 포인트로, 자켓에서 단추가 잠기는 부분을 뜻합니다.’ 추가
(여자) 정장 치마는 골반이 아닌 배꼽 윗 부분에 맞춰 입습니다. 그래서, 허리가 아닌 윗배둘레로 의류를 찾기때문에 윗배둘레가 중요합니다.
 
 3. 여성 의류 선택시 - 열린옷장의 의류는 기성복 사이즈(일반적인 S,M,L 등)이 아닌 실측 사이즈로 표시되어 있습니다. 평소에 M을 입는 분들도 실측 사이즈에 따라 M이 아닌 다른 사이즈를 받으실 수 있습니다. 절대 다른 사이즈가 아니므로 안심하고 선택해주세요. ”
 
정장 선택 팁 - 왜 5를 더하나요? 활동시에 필요한 최소한의 여유공간을 5cm로 잡고 있습니다. 측정한 사이즈는 신체 자체의 사이즈이므로, 의류는 조금 더 여유롭게 입어야 합니다.
 
* 위 가이드는 -> 밑에 안내된
 
* 치수 측정 제목 옆에 “ 사이즈를 직접 측정하여 정확하게 입력할수록 더 잘 맞는 의류를 받아볼 수 있습니다. ”

5. 신체 치수를 누르면, 팝업이 뜬다.
“ 치수 측정할 준비 되셨나요? 다음 준비물을 준비해주세요. ”
줄 자, 측정을 도와줄 친구
-> 부득이하게 줄 자가 없는 경우, 끈으로 둘레를 잰 후, 일반 자를 이용하여 실측 사이즈를 기입해주세요.
-> 혼자서도 측정이 가능하나, 친구와 함께 재면 더 정확하게 잴 수 있어요!
-> 각 사이즈의 빈칸을 누르면 그 사이즈를 잴 수 있는 설명과 영상이 준비되어 있습니다. 
 
사이즈 우선순위
남성의 경우, 키 - 몸무게 - 윗배 - 허리
여성의 경우, 키 - 몸무게 - 윗배 - 엉덩이

**Comment by 10001if** [comment]
**추가요청 사항**
1. 평균 사이즈 정보를 현재 사용자 정보에서 보는 것과 같이 우측에 평균 치수를 안내해주고 평균 치수와 얼마나 차이가 나는지 사용자 정보에서 사이즈를 입력하는 방식처럼 보여주도록 요청드립니다. 
![2017-03-21 4 24 24](https://cloud.githubusercontent.com/assets/4696328/24136687/4609df9a-0e53-11e7-8d09-a06db62d92c3.png)

2. 여성의 신체치수 중에서 무릎 길이와 허리둘레는 빼 주시길 요청드립니다. 실제 의류를 찾을 때 큰 도움이 되지 않는 사이즈라 과감하게 없애려고 합니다. 

3. 여성의 평균 사이즈가 나오는데, 엉덩이 둘레는 빠져있습니다. 입력한 치수와 동일한 평균값이 나오도록 수정 요청드립니다.

4.

**Comment by aanoaa** [comment]
@10001if 이슈가 다시 열렸다면 우선순위도 다시 조절해주세요.

**Comment by 10001if** [comment]
@aanoaa 네~ 알겠습니다!

**Comment by aanoaa** [comment]
평균치수와의 오차를 보여주는 것은 과연.. 쉽게 이해할 수 있을지 의문입니다.
더 헛갈려 할 수 있을 것 같습니다.

    가슴둘레: 97(+4)

**Comment by aanoaa** [comment]
https://online.theopencloset.net/stream/mens/Man_waist_measurement_all.mp4

online.theopencloset.net 이 share 로 redirect 되면서 치수측정 동영상이 재생되지 않습니다.

**Comment by aanoaa** [comment]
@yongbin 이건 따로 이슈에 등록하도록 하겠습니다.

**Comment by aanoaa** [comment]
평균치수와의 오차를 보여주는 것

을 제외하고 완료하였습니다.

어디에 어떻게 나타내면 헛갈리지 않고 받아들일 수 있을지 고민해서 답변 남겨주시면 반영하도록 하겠습니다.

**Comment by 10001if** [comment]
제 맥에서 신체치수 입력을 진행해본 결과 동영상이 재생되지 않습니다~

**Comment by aanoaa** [comment]
> 제 맥에서 신체치수 입력을 진행해본 결과 동영상이 재생되지 않습니다~

#127 알고 있는 이슈입니다.

**Comment by aanoaa** [comment]
여성의 허리둘레를 입력받지 않았더니, 추천의류 API 에서 다음과 같은 에러가 나타납니다.

> Waist is required

cc @yongbin

**Comment by aanoaa** [comment]
GET /api/order/:id/search/clothes
    GET /api/user/:id/search/clothes

지금 의류추천 API 는 두개 입니다.

    GET /api/clothes/recommend?height=xxx&weight=xxx&...
    GET /api/clothes/suggestion?height=xxx&weight=xxx&...

와 같이 query parameter 로 신체치수를 받아서 적절한 의류를 추천, 제안해주는 API 가 있다면 좋을 것 같습니다.

**Comment by 10001if** [comment]
> 신체치수 안내 멘트를 수정하고자 합니다.
> 가슴둘레
> 현재 -> 양팔을 들어올린 후 줄자를 겨드랑이 가장 윗부분에 끼운 후 양팔을 내린다.
> 변경요청 -> (남자) 양팔을 들어올려 줄자를 겨드랑이 가장 윗부분에 끼운 후 양팔을 내려 수평 둘레를 측정한다.
> (여자) 가슴의 가장 두꺼운 부분의 둘레를 수평으로 측정한다.
> 
> 윗배둘레
> 현재 -> 배꼽 위치에서 6CM(보통의 경우 남성의 경우 손가락 3개, 여성의 경우 4개)위의 둘레를 수평으로 측정한다.
> 변경요청 -> (남자) 윗배둘레는 열린옷장만의 특별한 사이즈 포인트로, 자켓에서 단추가 잠기는 부분을 뜻합니다. 배꼽 위치에서 6CM(보통의 경우 남성의 경우 손가락 3개, 여성의 경우 4개)위의 둘레를 수평으로 측정한다.
> (여자) 윗배둘레는 열린옷장만의 특별한 사이즈 포인트로, 자켓에서 단추가 잠기는 부분을 뜻합니다. 배꼽 위치에서 6CM(보통의 경우 남성의 경우 손가락 3개, 여성의 경우 4개)위의 둘레를 수평으로 측정한다. 정장 치마는 골반이 아닌 배꼽 윗 부분에 맞춰 입습니다. 그래서, 허리가 아닌 윗배둘레로 의류를 찾기 때문에 윗배둘레가 중요합니다.
> 
> 여성 의류 선택시 멘트 추가하고자 합니다.
> <스커트 사이즈 선택 버튼 하단에 위치>
> 열린옷장의 의류는 기성복 사이즈(일반적인 S,M,L 등)이 아닌 실측 사이즈로 표시되어 있습니다. 평소에 M을 입는 분들도 실측 사이즈에 따라 M이 아닌 다른 사이즈를 받으실 수 있습니다. 절대 다른 사이즈가 아니므로 안심하고 선택해주세요. ”
> 
> 열린옷장 정장 선택 팁의 내용을 수정하고자 합니다.
> 현재 -> 자켓: 윗배 둘레에 5cm를 더해서 찾는다.
> 변경요청 -> 윗배 둘레에 5cm를 더해서 찾는다. (왜 5cm를 더하나요? 활동시에 필요한 최소한의 여유공간을 5cm로 잡고 있습니다. 측정한 사이즈는 신체 자체의 사이즈이므로, 의류는 조금 더 여유롭게 입어야 합니다.)
> 
> 현재 -> 위 가이드는 참고용이며 평소에 착용하는 사이즈 및 상세사이즈 확인 후 선택해주세요.
> 변경요청 -> 밑에 안내된 가이드는 참고용이며 평소에 착용하는 사이즈 및 상세사이즈 확인 후 선택해주세요.
> 
> 현재 -> 정확한 신체치수를 입력하는 것은 중요합니다. 신체치수를 정확히 측정하여 입력해주세요.
> 변경요청 -> 키와 몸무게는 1주일 이내에 측정된 기록 이어야 합니다. 정확하게 입력해주세요.
> 사이즈를 직접 측정하여 정확하게 입력 할수록 더 잘 맞는 의류를 받아볼 수 있습니다.
> 
> 신체 치수를 누르면, 신체치수 입력 전에 다음과 같은 안내멘트가 보이고 이에 동의한 경우 신체치수 입력 창이 나타나도록 변경 요청드립니다.
> “ 치수 측정할 준비 되셨나요? 다음 준비물을 준비해주세요. ”
> 
> (1) 줄 자
> (2) 측정을 도와줄 사람
> 
> -> 부득이하게 줄 자가 없는 경우, 끈으로 둘레를 잰 후, 일반 자를 이용하여 실측 사이즈를 기입해주세요.
> -> 혼자서도 측정이 가능하나, 친구와 함께 재면 더 정확하게 잴 수 있습니다.
> -> 각 사이즈의 빈칸을 누르면 그 사이즈를 잴 수 있는 설명과 영상이 준비되어 있습니다.
> 
> 확인사항) 얇은 옷을 입고 측정하는게 더욱 정확합니다.
> 앉아서 잴 경우, 사이즈가 부정확하게 측정됩니다. 선 채로 측정해주세요.
> 줄 자는 몸에 붙인 상태에서 타이트하게 당겨 측정해주세요.
> 
> * 온라인 대여의 경우, 대여자가 제공한 신체치수를 기준으로 발송이 이루어집니다. 따라서 신체 치수를 잘못 측정한 경우 몸에 맞지 않는 의류가 전달될 수 있습니다. 신체치수를 정확히 측정하여 입력해주세요.
> 
> 사이즈 우선순위
> 남성의 경우 : 키 - 몸무게 - 윗배 - 허리
> 여성의 경우 : 키 - 몸무게 - 윗배 - 엉덩이

내용이 적용되지 않은 것으로 보입니다. 확인 부탁드립니다~

**Comment by aanoaa** [comment]
@pingpongworks 님이 동영상+사진의 위치와 inch<->cm 테이블표의 위치를 바꾸는게 더 좋을 것 같다고 했습니다.

**Comment by aanoaa** [comment]
> 열린옷장 정장 선택 팁의 내용을 수정하고자 합니다.

정장 선택 팁이 뭔가요?

**Comment by aanoaa** [comment]
> 정장 선택 팁이 뭔가요?

여성에게만 나타나는 정보입니다.

**Comment by aanoaa** [comment]
> 혼자서도 측정이 가능하나, 친구와 함께 재면 더 정확하게 잴 수 있습니다.

ㅋㅋㅋ

**Comment by aanoaa** [comment]
> 다음 준비물을 준비해주세요.

준비 라는 단어가 반복됩니다.
맞는 말이긴 한데..

**Comment by aanoaa** [comment]
저의 웃음포인트는 고향떠나 혼자 사는 50대 남성이 친구와 함께 신나게 측정하는게 상상되서..

**Comment by pingpongworks** [comment]
“ 치수 측정할 준비 되셨나요? 다음 준비물을 준비해주세요. ”
>> 치수측정 단계입니다. 다음을 준비해주세요. 

혼자서도 측정이 가능하나, 친구와 함께 재면 더 정확하게 잴 수 있습니다.
>> 혼자서는 정확한 측정이 불가능하오니, 친구의 도움을 받아주세요.

문구 이렇게 수정해주세요~
