### ISSUE TITLE
관리자가 주문서의 배송상태를 임의로 변경하는 기능

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#118]
지하철 택배를 통해 발송한 경우에는 운송장번호를 입력할 수 없어 발송 대기 상태로 남아 있습니다.
상태를 변경할 수 있는 기능이 필요합니다.

~/orders/54887/purchase 이런 경우입니다.

**Comment by 10001if** [comment]
@aanoaa 보시고 #87 이슈와 동일하다고 생각되시면 이슈를 닫아주셔도 됩니다.

**Comment by aanoaa** [comment]
> ~/orders/54887/purchase 이런 경우입니다.

그냥 링크 걸어주세요.

https://share.theopencloset.net/orders/54887/purchase

**Comment by aanoaa** [comment]
#87 은 `주문서의 상태` 와 관련되었지만 이것은 `배송상태` 와 관련이 있습니다.

**Comment by aanoaa** [comment]
운송장 번호를 입력하면 배송상태가 `발송대기` -> `배송중` 으로 변경되고 문자메세지가 발송됩니다.

**Comment by aanoaa** [comment]
![2017-03-22 15-12-33](https://cloud.githubusercontent.com/assets/170528/24184573/00c373dc-0f12-11e7-8a00-a6800833162c.png)

`결제완료 발송대기 배송중 배송완료 반송신청 반납` 등을 누를 수 있도록 하면 되지 않을까 합니다.

**Comment by 10001if** [comment]
@aanoaa 네, 그런 방식이 가장 적합해 보입니다.
