### ISSUE TITLE
주문서별 배송 상태 업데이트 자동화

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#12]
주문서의 스키마 변경이 필요합니다.

- 운송장
- 반납운송장

을 저장할 수 있는 공간이 필요합니다.

**Comment by aanoaa** [comment]
반송신청을 자동화 할 수 있으면 좋겠습니다.
현재 반송신청하고 있는 프로그램에 대해 설명해주세요.

**Comment by 10001if** [comment]
@aanoaa 문자 내용은 다시 정리해서 말씀드리겠습니다. 그리고 현재 반송 신청하는 프로그램에 대해서는 어떻게 설명해 드리면 될까요? 궁금하신 점 알려주시면 아는 범위 내에서 설명해드리도록 하겠습니다. 현재는 CJ 대한통운에서 제공해준 프로그램을 다운 받아 제공해준 ID 와 비밀번호를 입력하여 로그인하는데, 로그인 후 사용하는 것은 거의 반송 신청이 대부분입니다.

**Comment by aanoaa** [comment]
운송장번호를 가지고 배송상태를 자동으로 변경할 수 있는 데몬을 실행시켜야 합니다.
실행방법은..

    $ ./script/share shipped2delivered            # 배송대기 -> 배송완료 30min
    $ ./script/share returnrequested2returning    # 반송요청 -> 반송중  1hr
    $ ./script/share returning2returned           # 반송중 -> 반송완료  1hr

**Comment by aanoaa** [comment]
> 주문서의 스키마 변경이 필요합니다.

스키마는 변경해서 OpenCloset::Schema 의 `develop` 에 머지되었습니다.

**Comment by aanoaa** [comment]
상태 변경마다 사용자(대여자)에게 알려주어야 한다면,
각 포인트 마다 어떤 메세지를 어떤 방법으로 전달해 주어야 할 지 알아야 합니다.

**Comment by 10001if** [comment]
@aanoaa 반송 신청하는 프로그램은 직접 설명해드리도록 하겠습니다. 시간 되실 때 알려주세요. 찾아뵐게요 ^^

**Comment by 10001if** [comment]
`발송대기`->`배송중` 으로 변경 될 때에는 다음과 같은 문자 메세지가 발송되어야 합니다.
- [열린옷장 - 배송안내] 안녕하세요. OOO님. 대여하신 OOOOO(주문서 링크)가 CJ대한통운 OOOOOO(운송장 번호)으로 발송되었습니다. 감사합니다.

`배송중`->`배송완료` 으로 변경 될 때에는 다음과 같은 문자 메세지가 발송되어야 합니다.
- [열린옷장 - 배송확인] 안녕하세요. OOO님. 대여품목은 잘 받으셨나요? 택배 반송일은 OO일 입니다. OO일에 택배 기사님이 택배를 받은 장소로 택배 수거를 위해 방문할 예정입니다. 감사합니다. 

`OO일 2일 전'
- [열린옷장- 반납안내] 안녕하세요. OOO님. 택배 반송일인 OO에 CJ 택배 기사님이 방문하실 예정입니다. 만약, 대여기간 연장을 원하시는 경우 XX를 눌러 연장 신청해주세요. 감사합니다.

**Comment by 10001if** [comment]
@aanoaa 생각나는대로 작성을 했습니다. 더 필요한 내용이 있을 것 같습니다. 조금 더 고민하고 덧붙이도록 하겠습니다.

**Comment by aanoaa** [comment]
반송은 대여자의 역량에 맡깁니다.
직접 반송신청을 하거나 하지 않습니다.
