### ISSUE TITLE
의류를 대여한 이후에는 결제 취소가 되지 않도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#120]
orders/55136/purchase 에서 의류의 코드를 넣어 확인을 누르면 의류코드의 상태가 대여중으로 바뀝니다. 하지만 이 경우에도 의류를 주문한 사람은 결제취소를 할 수 있습니다. 결제취소는 의류의 코드를 넣어 확인을 누르기 전까지만 가능하도록 해야 할 것 같습니다. 그리고 이때 `S012`의류를 대여했는데, staff 첫화면에서 이 의류코드를 넣었을 때 검색이 되지 않았습니다.

**Comment by aanoaa** [comment]
결제완료 -> 발송대기 -> 배송중 -> 배송완료 -> 반납

의류의 바코드를 입력하고 `선택한 의류를 대여합니다` 버튼을 누르면 주문서의 상태가 `결제완료 -> 발송대기` 로 변경됩니다.

`발송대기 ~ 배송완료` 까지는 `대여중` 상태입니다.

언제 바뀌었는지는 모르겠지만 다른 이슈를 처리하면서 해결된 것으로 보입니다.
`결제완료` 상태가 아닐때에는 사용자가 결제취소를 할 수 없습니다.

**Comment by aanoaa** [comment]
제가 잘못 이해한 것인지 확인해주세요.
@10001if

**Comment by 10001if** [comment]
> 언제 바뀌었는지는 모르겠지만 다른 이슈를 처리하면서 해결된 것으로 보입니다.

이슈 남긴 시점과 좀 달라진 것 같습니다. 문제가 다시 발생하면 이슈를 다시 열도록 하겠습니다.
