### ISSUE TITLE
의류 선택화면의 의류 코드에 의류정보 링크를 추가

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#121]
https://share.theopencloset.net/clothes/J2GW

![2017-03-22 4 33 12](https://cloud.githubusercontent.com/assets/4696328/24186977/390a1d70-0f1e-11e7-9b0f-78c07826fcb4.png)
누르면 바로 의류정보의 새 창으로 이동할 수 있도록 요청드립니다.

의류의 기증자 혹은 의류의 대여율 등을 확인하고자 할 때 필요합니다. 그리고 본 의류의 대여자 신체 사이즈 누적기록을 확인하는데에도 필요합니다. 자주 확인하게될 내용입니다.

**Comment by pingpongworks** [comment]
확인했습니다~ 감사합니다!
