### ISSUE TITLE
결제완료 주문서를 취소

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#124]
결제는 되었지만 배송 ~ 반납 과정을 거치지 않고 취소해야 하는 상황이 발생할 수 있습니다.

- 테스트로 인해서
- ...

배송주문서 목록에 계속 남아있기 때문에 이를 적절히 취소할 수 있는 기능이 필요합니다.

**Comment by 10001if** [comment]
@aanoaa 직접 대여자가 취소하면 되지만 직접 본인이 취소할 수 있다는 사실을 인지하지 못한 경우가 종종 발생합니다. 옷장지기 또한 직접 취소할 수 있는 사실을 모르는 경우가 있어 아임포트를 통해 직접 카드결제를 취소한 경우가 있는데, 이 경우 주문서가 결제완료로 남아 있어 이 부분에 대한 수정이 필요합니다. ~/orders/65847/purchase 주문서는 `결제완료` -> `취소`로 변경되어야 합니다.

**Comment by pingpongworks** [comment]
테스트해보니까 이 문제는 해결된 듯 합니다.
아임포트에서 카드취소를 하면 주문이 취소되었다는 문자가 전송된 뒤 
주문서목록에서도 사라집니다. 
문제가 다시 발생하면 요청드리기로 하고 이슈 닫겠습니다.
