### ISSUE TITLE
주문서에 담당자, 반납 희망일 입력

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/OpenCloset-Share-Web#125]
온라인 대여 주문서의 경우 담당자와 반납 희망일이 입력되어 있지 않습니다.
담당자는 대여에서 발생한 상황을 알기 위해서 필요합니다.
반납 희망일은 연체 관리를 위해서 필요합니다.

**Comment by aanoaa** [comment]
반납희망일은 #115 에서 처리되었습니다. 지난 주 수요일부터 반영되었습니다.

담당자는 대여할때에 지정해야 합니다.

![2017-03-22 18-47-50](https://cloud.githubusercontent.com/assets/170528/24191801/379a1438-0f30-11e7-98f3-95ce211bfda6.png)

**Comment by 10001if** [comment]
@aanoaa 담당자는 로그인 기록으로 바로 입력되도록 수정 요청드립니다. 그러나 일반적으로는 로그인 한 자가 담당할 것이지만, 수정이 필요한 경우가 있으므로 수정도 가능하도록 요청드립니다.

**Comment by pingpongworks** [comment]
확인했습니다~
