### ISSUE TITLE
운송장 번호를 입력했지만 배송중으로 바뀌지 않음 

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#126]
https://share.theopencloset.net/orders/shipping?s=52

어제(23일)부터 운송장 번호를 입력하여도 배송중으로 바뀌지 않고 있습니다.
배송중으로 바뀌지 않아 해당 문자도 발송되고 있지 않습니다.

확인 부탁드리겠습니다.

**Comment by aanoaa** [comment]
지난 버전에서 버그가 발생하고 이번에 배포되기 전까지 `배송대기 -> 배송중` 으로 변경되지 않아서 `배송중 -> 배송완료` 로도 변경되지 않은 주문서들이 남아 있습니다.
반납되면 배송상태는 상관이 없지만 문자메세지 안내를 받을 수 없습니다.

**Comment by 10001if** [comment]
@aanoaa 확인 하였습니다. 기존에 변경되지 않고 남아있는 주문서는 수동으로 문자 메세지를 보내도록 하겠습니다. 그런데 반납되면 배송상태가 `발송대기`에서 `반납`으로 자동변경되는 건가요? 혹시 발송대기 상태에 그대로 머물러 있는 건 아니겠죠? `발송대기`에서 `반납`으로만 주문서 이동이 이뤄지면 됩니다.

**Comment by aanoaa** [comment]
- 주문서의 상태
- 주문서의 배송상태

두개가 있습니다.
반납이되면 주문서의 배송상태는 여전히 `발송대기` 일 테지만, 주문서의 상태는 `반납`으로 됩니다.
목록에서 볼때는 문제가 없습니다.
해당 주문서는 반납 목록에서 보여집니다.
