### ISSUE TITLE
대여일(rental_date) 을 주문할때가 아닌 결제가 되었을때 넣어주도록 함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#130]
오프라인 대여와 비슷한 방향으로 진행하기 위해서 결제가 되었을때에만 `rental_date` 를 넣어주도록 해야 합니다.

    대여일 = 의류착용일 - 1일

로 계산할 수 있기 때문에 의류착용일을 가지고 결제 시점에 넣어줄 수 있습니다.

**Comment by aanoaa** [comment]
제가 필요하다고 생각해서 우선순위를 조절하였습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/issues/1224

온라인 통계를 위해 필요한 작업입니다.

**Comment by 10001if** [comment]
확인은 못했지만 완료되었다고 생각하고 우선순위의 확인요망 창에서 제거하도록 하겠습니다.
