### ISSUE TITLE
신체치수 필수 입력값 관련 오류

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/OpenCloset-Share-Web#131]
![1](https://cloud.githubusercontent.com/assets/14110661/24658172/e64ef586-1983-11e7-895b-bc44379e68eb.JPG)

이런 이유로 전화도 많이 오고 메일도 와 있습니다.
우선적으로 처리되어야 합니다.

**Comment by aanoaa** [comment]
이게 원래 있던 기능인데 요청에 의해 뺏습니다.

https://github.com/opencloset/OpenCloset-Share-Web/issues/114#issuecomment-287998923

> 남성의 신체치수 중에서는 다리길이를 빼주시길 요청드립니다.

지난 버전부터 다리 길이는 신체치수 입력화면에서 입력받고 있지 않습니다.

**Comment by MoDoLEE** [comment]
![default](https://cloud.githubusercontent.com/assets/14110661/24665598/d63d962e-1998-11e7-9a5c-3c6de5c5e84d.JPG)

현재 다리길이가 없어서 주문서 작성을 할 수 없습니다.

**Comment by aanoaa** [comment]
방금 다리길이를 입력하지 않아도 주문서를 작성할 수 있도록 수정하고 배포하였습니다.
a7524d49d96e59716ba9289fb4d6eaf6e3231397

**Comment by aanoaa** [comment]
다리길이를 입력받을 것인지 말것인지는 다시 내부 논의를 거쳐 말씀해주세요.

**Comment by MoDoLEE** [comment]
감사합니댜. 논의 후 말씀드리겠습니다.

**Comment by aanoaa** [comment]
여성의 경우 무릎길이를 입력할 수 없는데 무릎길이가 없어서 주문을 할 수 없는 버그를 수정하였습니다.

**Comment by aanoaa** [comment]
d7bdf9a61d0bfc780e4a7cbb8f96044bda4360c7

**Comment by aanoaa** [comment]
다리길이를 입력받지 않는 대신에 `GET /orders/:id/purchase` 에서 평균 다리길이를 보여주어야 합니다.

**Comment by aanoaa** [comment]
여성의 허리둘레를 입력받지 않았더니, 추천의류 API 에서 다음과 같은 에러가 나타납니다.

> Waist is required

cc @yongbin

**Comment by 10001if** [comment]
다시 생각해보니, 본 내용은 옷장지기가 확인하는 부분이므로 평균 데이터를 계산할 필요 없이 남성의 경우 160cm~200cm까지 5cm 단위로 다리의 평균 길이를 보여주면 됩니다. 
그리고 여성의 경우 140cm~180cm까지 5cm단위로 무릎의 평균 길이를 보여주면 됩니다.

**Comment by MoDoLEE** [comment]
여성의 경우 허리, 허벅지를 입력하는 란이 없는데
입력을 하지 않으면 다음 단계로 넘어갈 수 없습니다.

**Comment by 10001if** [comment]
@aanoaa 치수 수정하면서 제가 확인 못한게 많네요~ 

> 여성의 경우 허리, 허벅지를 입력하는 란이 없는데
> 입력을 하지 않으면 다음 단계로 넘어갈 수 없습니다.

이 건은 빨리 수정이 되어야 할 것 같습니다. 확인 부탁드릴게요~!

**Comment by aanoaa** [comment]
> 여성의 경우 허리, 허벅지를 입력하는 란이 없는데
> 입력을 하지 않으면 다음 단계로 넘어갈 수 없습니다.

확인중에 있는데 재현되지 않습니다.
문제를 어떻게 확인하셨나요?

**Comment by MoDoLEE** [comment]
지난 금요일에 대여자가 전화로 문의한 내용입니다. 기존에 대여한 기록이 없고 신체치수 데이터는 허리, 허벅지를 제외한 데이터만 입력된 상태였습니다.(0값이 아니라 NULL값이었습니다.) 그 상태에서 허리, 허벅지 데이터가 입력되지 않았다는 오류가 뜬다고해서 관리자가 임의로 사용자 데이터의 허리, 허벅지 데이터를 입력했습니다. 그리고 다시 확인하니 오류 메세지 없이 정상 동작한다고 했습니다.

**Comment by aanoaa** [comment]
허리와 허벅지는 남성의 경우 체크하도록 하고 있습니다.
여성분(대리인)과 통화해서 헛갈리신 것 아닐까요?

옷장지기의 계정으로 다시 한번 확인해보도록 하겠습니다.

**Comment by MoDoLEE** [comment]
사용자번호 60445 입니다. 성별 선택이 안되어 있어서 발생한 문제였던 것 같습니다. 죄송합니다~
