### ISSUE TITLE
결제수단 확인이 언제나 가능하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#134]
온라인에서 결제완료 단계에서는 결제수단이 확인가능하나 그 이후 단계에서는 결제수단 확인이 어렵습니다. 사용자 주문서에서도 보이지 않습니다. 대여가 진행된 이후에도 결제 수단이 보이도록 수정 요청드립니다. 결제 후 대여 중에 환불요청이 들어오면 카드인지 계좌이체 인지에 따라 대응하는 방법이 다르기 때문입니다.

**Comment by aanoaa** [comment]
![2017-04-13 08-57-00](https://cloud.githubusercontent.com/assets/170528/24984256/3712e564-2027-11e7-8f93-9c9ebceaa965.png)

표시하고 있습니다.
어디에서 어떻게 보여야 하는 것인지 자세하게 알려주세요.

**Comment by 10001if** [comment]
@aanoaa https://share.theopencloset.net/orders/56418/purchase 처럼 대여가 진행되는 상황에서는 결제방법을 볼 수 없습니다. 주문서 정보를 볼 수 있는 란 자체가 나타나있지 않습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
