### ISSUE TITLE
결제완료 이후 단계에서 대여자가 기록했던 신체 치수와 선택한 사이즈(S,M 등)이 보이도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#135]
결제완료 이후 단계에서 대여자가 기록했던 신체 치수와 선택한 사이즈(S,M 등)이 보였으면 좋겠습니다. 결제 이후에도 대여자와 소통을 해야 하는데, 어떤 사이즈를 주문했었는지 확인 할 수가 없습니다.

**Comment by aanoaa** [comment]
@10001if 
여성의 자켓과 스커트 사이즈를 말씀하시는 건가요?
어디에 무엇이 보여야 하는지 구체적으로 말씀해주세요.

**Comment by 10001if** [comment]
![2017-04-14 11 16 40](https://cloud.githubusercontent.com/assets/4696328/25030956/15aca7ba-2104-11e7-99f6-a7747719ec9e.png)
@aanoaa 여성의 자켓과 스커트 사이즈가 맞구요. https://share.theopencloset.net/orders/55617/purchase 처럼 이미 대여가 진행된 이후에도 대여자의 신체 사이즈와 선택한 사이즈를 볼 수 있도록 수정 요청드립니다. 위치는 선호하는 색상 하단에 들어가면 되구요. 들어가야 하는 내용은 대여자의 신체사이즈와 선택한 의류 사이즈 입니다. 대여시 확인하는 정보와 동일합니다.

**Comment by aanoaa** [comment]
![2017-04-20 12-13-30](https://cloud.githubusercontent.com/assets/170528/25211940/cc3dfa66-25c2-11e7-8e3e-8f11bfad7de4.png)

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다^*
