### ISSUE TITLE
결제완료 후 대여자의 주문서에 온라인담당자 메모란 필요

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#136]
결제완료된 주문에 대해 온라인담당자가 대여자와 전화나 옐로우아이디로 소통하여 추가되는 요청사항을 적을 곳이 필요합니다. 사이즈, 디자인, 배송과 관련하여 결제 완료 후 요청사항들이 있을 수 있는데, 지금은 개인 수첩에 적을 수 밖에 없습니다. 온라인 담당자 메모란 만들어주세요.

**Comment by pingpongworks** [comment]
![image](https://cloud.githubusercontent.com/assets/17288038/25927714/d3e37fa4-3632-11e7-9bbf-374ec5313659.png)

오프라인 대여에서 '5F 주문서 메모'와 같은 역할입니다. 
결제완료 시점에서 담당자가 메모한 내용이 
발송완료 한 후에 온라인대여의 경우에는 
'5F 주문서 메모' 대신에 '온라인 주문서 메모'로 연동되면 좋을 거 같습니다. 



메모 위치는 주문서 정보와 의륱코드 입력 사이에 들어가면 좋겠습니다.

![image](https://cloud.githubusercontent.com/assets/17288038/25927797/58b86f64-3633-11e7-9fba-be0f7928f16e.png)

**Comment by aanoaa** [comment]
온라인에서는 `return_memo`(반납메모) 를 활용하고 있지 않는데,
이를 활용할 수 있도록 하면 스키마 변경없이도 가능할 것 같습니다.

**Comment by 10001if** [comment]
@aanoaa 온라인 주문은 온라인 페이지에서 담당합니다. 담당자가 실제 주문서로 들어와서 코멘트를 확인하도록 한다면 번거로운 작업이 될 것 같습니다. 가능하면 현재 온라인 주문을 확인하는 페이지에서 코멘트를 확인 할 수 있도록 하는 것이 좋을 것 같습니다.

**Comment by 10001if** [comment]
@aanoaa 제가 이해를 잘 못한 것 같습니다. 상기에서 제가 작성한 것은 본 이슈 내용과 요청사항이 동일하구요. 다만 추가적으로 오프라인 주문서와의 메모 연동을 요청하신 것 같네요. :)

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1102
https://github.com/opencloset/opencloset/issues/1240

온라인 주문서에 메모란을 만드는 것은 다른 이슈와 관계없이 필요합니다. 하지만 오프라인 주문서와의 연동 이슈는 위 두 가지 이슈와 관련이 있는 것으로 보입니다. 연동하려고 한 이유는 5층에서 미리 입어본 사람이 차후에 온라인으로 주문을 할 때 그 내용을 온라인으로 바로 확인하도록 하려했기 때문입니다. 위 2가지 이슈가 해결된다면 오프라인-온라인 주문서의 연동은 따로 필요하지 않는 것으로 보입니다.

**Comment by aanoaa** [comment]
위에 언급해주신 이슈는 따로 우선순위를 정해주세요.
여기에서는 온라인주문서에 담당자 메모를 기록하는 작업을 하겠습니다.

**Comment by aanoaa** [comment]
![1](https://user-images.githubusercontent.com/170528/27370765-fec72b54-5698-11e7-8311-67c961869d96.png)

기록하는건 이정도면 될 것 같은데, 기록 후에 어디에서 내용을 확인할 수 있어야 하나요?

**Comment by 10001if** [comment]
주문서 메모는 위 그림처럼 기록하고 그 화면에서 기록된 내용을 확인하면 됩니다. 다만, @pingpongworks 논의 해보니 온라인 주문서에 기록된 내용이 실제 주문서(~/order/*****)의 `주문서 메모 5F`에 동기화 되도록 요청드리고자 합니다. 
하지만, 온라인 주문서의 메모가 5층 메모에 들어가는 게 바람직하지 않다고 생각되어지면, 온라인 주문서 메모 란을 추가하여도 됩니다. 이렇게 하려는 이유는 온라인 주문이 들어왔을 때 과거의 주문서 기록을 찾아 그때 빌렸던 의류와 정보를 확인하는 과정이 필요한데, 온라인 주문서에만 남아 있으면 이후에 온라인에 기록된 내용을 확인 할 수 있는 방법이 없기 때문입니다.

**Comment by aanoaa** [comment]
> 제가 질문을 잘 이해 못했는데, 주문서 메모는 위 그림처럼 기록하면 됩니다. 그리고 그 화면에서 기록된 내용을 확인하면 됩니다.

배송주문서의 `결제완료` 목록에서 주문서를 눌렀을때 `주문서 메모` 를 입력할 수 있습니다.
어딘가에서 참고하려고 입력하는건데, 입력한 `주문서 메모` 가 어느 화면에서 보여져야 합니까?

@10001if

**Comment by aanoaa** [comment]
`주문서 메모 5F` 란을 활용해서 주문서 메모를 작성할 수 있도록 하고 

     결제완료 | 발송대기 | 배송중 | 배송완료 | 반송신청 | 반납

상태의 온라인 주문서상세에서 보여지도록 해야 합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
