### ISSUE TITLE
온라인대여 품목 등록시, 상태변경 가능 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#137]
온라인대여 품목을 등록하다가, 대여가능 상태가 아닐 경우 **오프라인 대여 페이지에서처럼** 바로 상태변경이 가능하면 좋겠습니다. 현재는 첫 화면으로 가서 상태를 변경한 후 처음부터 다시 등록해야 해서 업무가 원활하지 않습니다.

**Comment by 10001if** [comment]
@pingpongworks 혹시 이 이슈가 https://github.com/opencloset/OpenCloset-Share-Web/issues/145 와 같은 이슈인가요? 같은 이슈라면 닫아도 되는지요?
