### ISSUE TITLE
운송장번호 입력 후에도 확인 가능하도록

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#138]
온라인담당자가 운송장번호를 입력한 후에는 볼 수가 없어 문자발송 등 후속조치를 할 때 불편합니다. 사용자주문서에 입력한 운송장번호도 나타나도록 해주세요.

**Comment by aanoaa** [comment]
> 온라인담당자가 운송장번호를 입력한 후에는 볼 수가 없어 문자발송 등 후속조치를 할 때 불편합니다.

어디에서 무엇을 볼 수가 없나요?

**Comment by aanoaa** [comment]
운송장 번호를 얘기하는 것 이었습니다.
구매 상세내역에서 확인할 수 있습니다.
