### ISSUE TITLE
첫화면(HOME)

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#14]
HOME 이라 하면 처음 로그인 후에 보게 되는 화면입니다.
- staff
- 회원
  - 대여기록이 있는
  - 대여기록이 없는
- 비회원

사용자별로 HOME 에서 보여져야 할 내용이 달라야 하지 않나 싶습니다.

대여기록이 있는 사용자라면 지난 대여를 압축해서 보여주고, 메세지등도 연결할 수 있을 것 입니다.

대여기록이 없다면 치수측정 방법 안내로 이동할 수 있도록 하거나, 어떤 식으로 서비스를 이용하면 된다.
라는 가이드가 있으면 좋을 것 같습니다.

**Comment by aanoaa** [comment]
주문을 하다가 말았다면, 계속 진행할 수 있도록 해야합니다.
이때 카테고리에 따라서 진행 방식이 다른데,
자켓 + 팬츠의 경우와 그렇지 않은 경우입니다.

바로 결제로 이동할 수 있도록 하거나,
의류를 선택할 수 있도록 링크를 제공해 주어야 합니다.

**Comment by aanoaa** [comment]
> 주문을 하다가 말았다면, 계속 진행할 수 있도록 해야합니다.

진행상황이 업데이트 되지 않아서 그런데, 이미 해결되었습니다.
첫화면을 어떻게 구성해야할지 고민해봐야 합니다.

피드백을 통해 수정하도록 하겠습니다.

**Comment by aanoaa** [comment]
첫화면에 대한 의견이 많았습니다.
어떻게 구성해야 좋을지 의견바랍니다.

현재는 지난 대여이력을 첫화면에서 보여주고 있습니다.

**Comment by aanoaa** [comment]
지난 대여이력이 3개월이상 된 사용자에게 신체치수 변경을 안내해야 합니다.

어디에 어떻게 나와야 좋을까요?

**Comment by 10001if** [comment]
지난 대여이력은 첫화면 대신 상단에 메뉴를 추가하여 `대여이력보기`를 클릭하면 확인 할 수 있도록 요청드립니다.

**Comment by aanoaa** [comment]
따로 뺐습니다.
