### ISSUE TITLE
구매탭에서 키에 따라 평균다리길이와 평균무릎길이를 보여줌

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#140]
> 다시 생각해보니, 본 내용은 옷장지기가 확인하는 부분이므로 평균 데이터를 계산할 필요 없이
> 남성의 경우 160cm ~ 200cm까지 5cm 단위로 다리의 평균 길이를 보여주면 됩니다.
> 그리고 여성의 경우 140cm ~ 180cm까지 5cm단위로 무릎의 평균 길이를 보여주면 됩니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Share-Web/pull/133

에서 이어서 진행하면 되겠습니다.

**Comment by aanoaa** [comment]
``` sql
SELECT AVG(leg) FROM `order` o JOIN booking b ON o.booking_id = b.id WHERE o.leg IS NOT NULL AND b.gender = 'male' AND o.height BETWEEN 160 AND 165;
+----------+
| AVG(leg) |
+----------+
|  92.6724 |
+----------+
```

**Comment by aanoaa** [comment]
160 ~ 165 | 166 ~ 170 | 171 ~ 175 | 176 ~ 180 | 181 ~ 185 | 186 ~ 190 | 191 ~ 195 | 196 ~ 200
--- | --- | --- | --- | --- | --- | --- | ---
92.6 | 95.2 | 97.8 | 100.6 | 103.6 | 106.9 | 110.0 | 111.0

**Comment by aanoaa** [comment]
벗어난 범위는 테이블을 참고하지 못하므로 계산해서 보여주도록 하겠습니다.

**Comment by aanoaa** [comment]
140 ~ 145 | 146 ~ 150 | 151 ~ 155 | 156 ~ 160 | 161 ~ 165 | 166 ~ 170 | 171 ~ 175 | 176 ~ 180
--- | --- | --- | --- | --- | --- | --- | ---
43.4 | 45.6 | 47.2 | 48.6 | 49.7 | 51.1 | 52.8 | 54.5

**Comment by aanoaa** [comment]
실측 사이즈는 흰색으로 평균사이즈는 검정색으로 표시하도록 하였습니다.
실측사이즈가 우선이고(방문해서 측정했을 수도 있으니까) 측정사이즈가 없으면 평균사이즈를
나타내도록 했습니다.

**Comment by aanoaa** [comment]
ede6147063381261926ebc2288e361f2de94565b
648743e25f7fcf1ff215bf0a8053e4a9e4faaffe

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Share-Web/pull/133#issuecomment-293170574

> 평균사이즈 타이포 컬러를 노랑으로 해주세요~ 검정이 잘 안보여요~

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
