### ISSUE TITLE
로그인 페이지에 회원가입 링크 삽입

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#141]
<img width="531" alt="2017-04-11 15 40 59" src="https://cloud.githubusercontent.com/assets/17288038/24895850/52d77d9c-1ecd-11e7-81b5-5cda9fd08545.PNG">

예시와 같이 회원가입 링크 삽입 요망

**Comment by aanoaa** [comment]
통합 로그인?의 느낌으로 이미 id.theopencloset.net 이 있지만 활용되고 있지 못합니다.

지금 문제가 되고 있는 것이

- share 에서 로그인을 시도함
- 알고보니 아이디를 모르겠음
- **아이디를 찾는 방법이 없음**
- 아이디가 기억남
- 비밀번호를 모르겠음
- **비밀번호를 찾는 방법이 없음**
  - `암호를 잊어버렸어요` <- 인증번호 갱신임
- 등록된 아이디가 아니었음
- **로그인에서 바로 회원가입을 하고 싶은데 링크가 없음**

입니다.

**Comment by aanoaa** [comment]
> 비밀번호를 찾는 방법이 없음 

아이디를 알고 있다면 email 을 통해 password 를 reset 하는 기능은 있습니다.

**Comment by aanoaa** [comment]
관련된 이슈가 #75 #123 있습니다.

**Comment by aanoaa** [comment]
#75 가 해결되어서 id.theopencloset.net 을 이용하게 된다고 하더라도
자체 서비스에 로그인 화면을 붙이도록 하겠습니다.

**Comment by aanoaa** [comment]
가장 우선적으로 해결되어야 하는 것은 로그인 화면에 회원가입 링크가 제공되는 것입니다.

**Comment by aanoaa** [comment]
비밀번호 reset 후에 링크를 클릭해서 로그인하는 기능이 있습니다.
클릭한번으로 로그인을 하기 위해서 `GET /login` 기능이 있습니다.
그쪽을 바꾸더라도 로그인을 위해서

    GET /login

에서 로그인 폼을 보여주도록 하겠습니다.

**Comment by aanoaa** [comment]
나머지는 #32 에서 진행하겠습니다.

**Comment by aanoaa** [comment]
![2017-04-12 17-09-21](https://cloud.githubusercontent.com/assets/170528/24947707/cb874b02-1fa2-11e7-9af8-34ba7a502478.png)

이렇게 바뀌었습니다.

**Comment by aanoaa** [comment]
https://share.theopencloset.net/login

**Comment by pingpongworks** [comment]
패스워드를 잊었거나 잘못 알고 있을 경우, "잘못된 요청입니다" 페이지로 가게되면 그 다음엔 대부분 전화를 하십니다,,, 패스워드를 잊었을 경우, 로그인 페이지 내에서 다음 문구 노출 요망~

## 패스워드가 기억나지 않아요!

**Comment by aanoaa** [comment]
뜻은 이해했습니다.
적절하게 더 좋은 방향으로 진행하겠습니다.

**Comment by pingpongworks** [comment]
네~ 그럽시다^^

김소령
OpenCloset / story tailor
010. 5278. 2844
pingpong@theopencloset.net

2017. 4. 12. 오후 5:18 Hyungsuk Hong <notifications@github.com> 작성:
