### ISSUE TITLE
추천검색 안내 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#142]
![image](https://cloud.githubusercontent.com/assets/17288038/24943172/2c615b88-1f90-11e7-8423-f8eb36ad876c.png)

현재의 안내는 추천검색과 추천대여가 한 덩어리로 되어있어 아래 의류사진들의 존재가 헷갈릴 수 있습니다. 
다음의 순서로 바꾸면 어떨지요?

[추천검색 수정.pdf](https://github.com/opencloset/OpenCloset-Share-Web/files/915553/default.pdf)

**Comment by aanoaa** [comment]
추천의류가 많을 경우에는 스크롤 밑으로 `추천대여` 버튼이 내려가게 됩니다.

**Comment by pingpongworks** [comment]
@aanoaa 의류 검색 스크롤이 돌아가는 동안 '**## 추천의류 검색 중**' 안내 추가해주세요. 어쨋든 대여자가 검색추천된 의류를 보고 선택할 수 있도록 해보는게 좋을 것 같습니다.

**Comment by pingpongworks** [comment]
좋아요!!

**Comment by aanoaa** [comment]
:+1: 이런 기능이 있지요
