### ISSUE TITLE
대여품목 등록시, 상태변경  

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#145]
* 온라인대여 품목 등록시, 대여가능 상태가 아닐 경우, 오프라인에서처럼 바로 상태변경 가능하면 좋겠습니다. 
* 현재는 대여의류 등록하다가 '반납'이나 '대여불가'가 나오면 첫화면으로 가서 전부 상태를 확인하고 상태변경을 한 후 처음부터 다시 등록해야해서 무척 불편합니다.

**Comment by aanoaa** [comment]
![2017-04-20 12-33-30](https://cloud.githubusercontent.com/assets/170528/25212501/952589ec-25c5-11e7-9865-43786849e28e.png)

- 대여중
- 대여불가
- 분실
- 폐기
- 재활용(옷캔)
- 재활용(비백)
- 사용못함

의 경우를 제외하고는 상태를 변경하지 않고도 대여할 수 있습니다.
위 사진을 보시면 `반납`임에도 체크할 수 있습니다.

**Comment by 10001if** [comment]
@aanoaa 체크 한 뒤 대여합니다 버튼을 눌러 대여중으로 변경되면 문제가 없습니다. 실제로 문제없이 작동 중입니다. 이슈 닫겠습니다.
