### ISSUE TITLE
테스트로 주문했던 내역 삭제요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#147]
<img width="960" alt="2017-04-21 19 13 30" src="https://cloud.githubusercontent.com/assets/17288038/25273420/aafd2c5a-26c6-11e7-8ad2-661f2a5fb6a6.png">

주문확인할 때 괜히 번거롭다고 합니다. 테스트로 옷장지기들이 주문했던 내역 좀 없애주세요~

주문서 ID
50847, 51039, 51042, 51171, 51181, 52767

**Comment by aanoaa** [comment]
``` sql
DELETE FROM `order` WHERE id IN (50847, 51039, 51042, 51181, 51171, 52767);
```

**Comment by pingpongworks** [comment]
확인했습니다~감사합니다^^
