### ISSUE TITLE
주문서내의 SMS 전송 버튼의 기능 변경

### ISSUE THREAD

**Issue by MoDoLEE** [opencloset/OpenCloset-Share-Web#148]
![order_send_sms](https://cloud.githubusercontent.com/assets/14110661/25368554/268f471a-29b8-11e7-992c-ddfc1a1ba37d.png)
주문서내의 SMS 전송 버튼

![user_info_send_sms](https://cloud.githubusercontent.com/assets/14110661/25368555/282a32e2-29b8-11e7-9963-2a59d2f47de0.png)
사용자 정보의 SMS 전송 버튼

현재 온라인 주문서에서는 SMS 전송 버튼을 통해서 SMS를 전송하는 일이 없습니다.
기존 온라인 대시보드를 통해서 SMS를 전송하거나, 사용자 정보의 SMS 전송 버튼을 눌러서
온라인 대여 후 메세지를 전송하고 있습니다.
그래서 SMS 버튼의 역할을 사용자 정보의 SMS 전송 버튼과 동일하게 변경했으면 합니다.
새 창으로 열어 주시면 더 좋을 것 같습니다.^^

**Comment by pingpongworks** [comment]
궁극적으로는 온라인대여에서도 대여후 대여자에게 보내는 문자메시지S는 자동으로 발송되어야 한다고 생각됩니다.  현재 주문서에 만들어져있는 SMS 버튼과 관련해서 기획단계에서 계획했던 다른 목적이나 내용이 있으면 공유바랍니다~ @aanoaa

**Comment by aanoaa** [comment]
지금도 자동으로 발송되고 있습니다.

![2017-04-26 15-16-40](https://cloud.githubusercontent.com/assets/170528/25420513/62ca8fa6-2a93-11e7-81e3-cf1be7c09237.png)

**Comment by pingpongworks** [comment]
발송되는 문자 내용을 모두들 제대로 확인해보지 못했네요. 암튼 문자내용 다시 정리해서 #150 에 요청 드렸고요, 

주문서 내의 SMS 버튼은 사용자 정보의 SMS 전송 버튼과 동일하게 변경하자는 @MoDoLEE 의견에 저도 동감합니다~

**Comment by aanoaa** [comment]
내용을 이해하지 못했습니다.

![2017-05-04 16-49-45](https://cloud.githubusercontent.com/assets/170528/25694462/bae5247e-30e9-11e7-98c4-3580f21f3c12.png)

대여자에게 직접 SMS 를 보내는 기능인데, 어떻게 바뀌어야 하나요?
버튼을 눌러서 textarea 를 토글할 수 있습니다.

cc @pingpongworks @MoDoLEE

**Comment by pingpongworks** [comment]
<img width="960" alt="2017-05-04 19 22 05" src="https://cloud.githubusercontent.com/assets/17288038/25699735/717ecb80-30ff-11e7-94e7-a1e7d11e1b85.png">

설명이 자세하지 못했네요. 수지니 사용자정보에 

> SMS보내기

와 같은 기능을 원하는 것입니다.

**Comment by aanoaa** [comment]
매크로와 같은 기능을 사용하고 싶다는 뜻 입니다.
staff 로 새창을 열어서 보내주는 링크면 될 것 같습니다.

**Comment by pingpongworks** [comment]
확인했습니다~
