### ISSUE TITLE
주문서의 상태추가

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#15]
오프라인일때에는 주문서가 방문예약 -> 치수측정 -> 의류준비 ... 등으로 만족할 수 있었지만,
온라인일때에는 더 많은 상태가 필요합니다.

주문서의 상태를 좀 더 세분화해야 합니다.

카테고리 선택 - **품목선택중** - 의류선택 - **의류선택중** - 결제전 - **결제중** - 결제완료 - **배송중** - 수취

더 고려해 봐야 하겠지만 최소한 위의 4개는 더 필요할 것 같습니다.

**Comment by aanoaa** [comment]
필요한 모든 상태를 나열해 볼 필요가 있습니다.

- 주문서작성
- 결제대기
- 배송대기
- 배송중
- 배송완료

**Comment by aanoaa** [comment]
- 입금확인

이 추가로 필요할 것 같습니다.

포장대기 대신에 발송대기로 변경하고자 합니다.

발송대기 - 결제완료된 주문서에 대해 옷을 포장해서 배송번호를 부여하기까지의 상태

**Comment by 10001if** [comment]
@aanoaa @yongbin 이상에서 언급해 주신 방식으로 진행하면 될 것 같습니다.
