### ISSUE TITLE
온라인 배송완료 후 문자 수정 요망

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#150]
기존 문자에서 본인의 주문서를 보여주는 url 수정해주세요~

https://share.theopencloset.net/orders/58980 

1. orders
2. `가` 띄어쓰기

그리고 문자 내용 전체적으로 보강해서 수정할까 합니다. 내용 확인 한번 해주세요~ @10001if

발송대기->배송중 으로 변경 될 때

    [열린옷장 배송안내] 안녕하세요. OOO님.  주문하신 https://share.theopencloset.net/orders/58980 가 CJ대한통운 OOOOOO 으로 발송되었습니다. 감사합니다.

## 배송중->배송완료 로 변경 될 때 ##

    [열린옷장 배송확인] 안녕하세요. OOO님.  대여품목은 잘 받으셨나요? 반납예정일은 OO일입니다. 기증자의 마음이 담긴 의류이오니 소중하게 착용 부탁드립니다.

## OO일 2일 전 ##

```
[열린옷장 반납안내] 안녕하세요. OOO님. 반납예정일은 OO일 입니다. 아래 반납안내를 참고하여 OO일까지 반납 부탁드립니다. 만약, 대여기간 연장을 원하시는 경우 XX를 눌러 연장 신청해주세요. 감사합니다.
 
< 반납안내 >
1. 택배 반납시 : 반납 예정일 1일 전에 발송(택배비는 본인부담), 받은 상자에 그대로 담아서 보내주세요.
 - 주소: 서울시 광진구 아차산로 213 (화양동, 웅진빌딩) 403호 (우.05019)
 - 전화: 02-6929-1020

2. 방문 반납시 : 웅진빌딩 4층 엘리베이터 앞 노란 무인반납함
 - 반납가능시간: 월~일 AM 10:00 ~ PM 9:00 ( 단, 밤 9시 이후에는 빌딩 보안상 출입 통제)

< 배상 규정 안내 >
1. 대여기간 연장: 1일 연장시 대여비의 20%
2. 대여기간 연체: 사전 연락없이 1일 연체시 대여비의 30%
3. 대여의류 손상: 대여비의 5배 배상 청구
4. 대여의류 분실: 대여비의 10배 배상 청구 

열린옷장 서비스 이용에 문의사항이 있으시면, 유선/카카오톡 엘로아이디/홈페이지 통하여 문의 부탁드립니다!
감사합니다 :)
```

**Comment by aanoaa** [comment]
지금 반납 2일전 메세지는 보내고 있지 않습니다.
반납 1일전 메세지가 있습니다.

`D-2`, `D-1` 메세지가 두번 보내져야 하나요?
온라인 대여와 오프라인 대여에 대해 `D-x` 메세지가 달라져야 하나요?

참고로 `D-1` 메세지는 아래와 같습니다.

    [열린옷장] 내일은 x일에 대여하신 의류 반납일입니다. 내일까지 반납부탁드립니다. 택배로 반납하실 경우, 오늘까지 택배사에 접수해 주셔야 추가 비용이 발생하지 않습니다.

**Comment by pingpongworks** [comment]
@aanoaa  예전에 만일대표가 github에 정리해놓은 거 보고 착각했어요. 반납2일전 아니고, 반납 1일전 메시지로 보내면 됩니다. 아래와 같이 다시 정리했습니다~


**_[열린옷장] 내일은 x일에 대여하신 의류 반납일입니다. 내일까지 반납부탁드립니다. 택배로 반납하실 경우, 오늘까지 택배사에 접수해 주셔야 추가 비용이 발생하지 않습니다.

< 반납안내 >
1. 택배 반납시 : 반납 예정일 1일 전에 발송(택배비는 본인부담), 받은 상자에 그대로 담아서 보내주세요.
 - 주소: 서울시 광진구 아차산로 213 (화양동, 웅진빌딩) 403호 (우.05019)
 - 전화: 02-6929-1020

2. 방문 반납시 : 웅진빌딩 4층 엘리베이터 앞 노란 무인반납함
 - 반납가능시간: 월~일 AM 10:00 ~ PM 9:00 ( 단, 밤 9시 이후에는 빌딩 보안상 출입 통제)

< 배상 규정 안내 >
1. 대여기간 연장: 1일 연장시 대여비의 20%
2. 대여기간 연체: 사전 연락없이 1일 연체시 대여비의 30%
3. 대여의류 손상: 대여비의 5배 배상 청구
4. 대여의류 분실: 대여비의 10배 배상 청구 

열린옷장 서비스 이용에 문의사항이 있으시면, 유선/카카오톡 엘로아이디/홈페이지 통하여 문의 부탁드립니다!
감사합니다 :)_**

**Comment by aanoaa** [comment]
@pingpongworks 

https://github.com/opencloset/OpenCloset-Cron-SMS/issues/21

온라인 주문서의 경우 반납 2일전 메세지를 요청하셨었는데, 이 이슈는 무시해도 될까요?

**Comment by pingpongworks** [comment]
네~무시해주세요~

**Comment by pingpongworks** [comment]
제가 테스트 대여중입니다. 혹시 수정할 부분 있으면 말씀드릴게요. 일단은 마감하겠습니다~

**Comment by aanoaa** [comment]
온라인주문서의 상태가 `배송중 -> 배송완료` 로 변경되었을때의 메세지가 변경되어야 합니다.

```
[열린옷장 배송확인] 안녕하세요. 홍길동님. 대여품목은 잘 받으셨나요? 반납예정일은 24일입니다. 택배는 하루전인 23일에 발송해주세요. 기증자의 마음이 담긴 의류이오니 소중하게 착용 부탁드립니다.

1. 택배로 발송을 하신 경우: <%= url_for("/order/$order_id/return")->to_abs %> 를 클릭하여 반납택배 발송알리미를 작성해주세요.

서울시 광진구 아차산로 213(화양동 48-3번지) 웅진빌딩 403호 열린옷장

2. 대여기간을 연장 하려는 경우: <%= url_for("/order/$order_id/extension")->to_abs %> 를 클릭하여 대여기간 연장신청서를 작성해주세요.

[열린옷장] 안녕하세요. <%= $user_name %>님.
<%= $user_name %>님이 대여하신 의류의 기증자 이야기를 읽으시려면 URL을 클릭해 주세요.

https://story.theopencloset.net/letters/o/<%= $order_id %>/d
```

**Comment by 10001if** [comment]
'온라인주문서의 상태가 배송중 -> 배송완료 로 변경되었을때의 메세지가 변경되어야 합니다.

[열린옷장 배송확인] 안녕하세요. 홍길동님. 대여품목은 잘 받으셨나요? 반납예정일은 24일입니다. 택배는 하루전인 23일에 발송해주세요. 기증자의 마음이 담긴 의류이오니 소중하게 착용 부탁드립니다.

1. 택배로 발송을 하신 경우: <%= url_for("/order/$order_id/return")->to_abs %> 를 클릭하여 반납택배 발송알리미를 작성해주세요.

서울시 광진구 아차산로 213(화양동 48-3번지) 웅진빌딩 403호 열린옷장

2. 대여기간을 연장 하려는 경우: <%= url_for("/order/$order_id/extension")->to_abs %> 를 클릭하여 대여기간 연장신청서를 작성해주세요.

[열린옷장] 안녕하세요. <%= $user_name %>님.
<%= $user_name %>님이 대여하신 의류의 기증자 이야기를 읽으시려면 URL을 클릭해 주세요.

https://story.theopencloset.net/letters/o/<%= $order_id %>/d'

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
