### ISSUE TITLE
가상계좌 입금기한 만료시

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#154]
결제대기 상태에서 대여자가 가상계좌 입금기한을 놓쳤을 때 
입금 가능한 새로운 가상계좌를 발송할 수 있도록 기능이 필요합니다.
미납시 '가상계좌 문자전송'과 같은 기능입니다.

![image](https://cloud.githubusercontent.com/assets/17288038/25929015/870c2f70-363a-11e7-929d-38e7e59eb2ec.png)

현재는 '결제대기' 상태인 대여자 목록을 따로 볼 수 없는데
**주문서 목록에서 '결제완료' 전에 '결제대기' 목록도 따로 볼 수 있었으면 어떨까요?**
현재는 결제대기 사용자정보를 찾는게 동명이인도 많아 번거롭습니다.

**결제대기 목록에서 '가상계좌 문자전송' 기능이 있으면 어떨까** 합니다만
의견주시면 좋겠습니다

**Comment by aanoaa** [comment]
결제 기간을 놓친 사용자에게 다시 주문하게 하지 않고, 결제가 다시 가능하도록 하는 안내하는 기능인 것 같습니다.

**Comment by aanoaa** [comment]
온라인의 결제대기 주문서는 의미없다고 생각해서 목록을 제공하지 않았습니다.
결제대기 목록은 결제를 하지 않은 온라인 주문서 수량을 파악하기에도 좋은 것 같습니다.

**Comment by 10001if** [comment]
https://github.com/opencloset/opencloset/issues/1308 기능이 생성되었으므로 본 이슈는 자연스럽게 해결이 되었습니다. 이슈 닫도록 하겠습니다.
