### ISSUE TITLE
58235 주문서 찾아주세요~

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#155]
기존에 온라인으로 2번 주문하셨던 이*림 님인데, 이번에 또 주문하시면서 

2017-04-24 대여했던 의류를 다시 대여하고 싶습니다.

라고 해주셨습니다만, 그 주문서 58235가 사라져서 기존 주문 내역을 확인할 수 없습니다.

아임포트에 결제했던 기록도 있다고 하는데, 

대체 어디로 갔을까요?

**Comment by aanoaa** [comment]
https://share.theopencloset.net/orders/58235

주문서를 찾을 수 없다고하네요
사용자검색해서 주문내역중에 찾아보세요

**Comment by 10001if** [comment]
차후에 비슷한 이슈가 발생하면 다시 열도록 하겠습니다.
