### ISSUE TITLE
결제취소 주문내역 삭제

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#156]
![image](https://cloud.githubusercontent.com/assets/17288038/25978904/341e3666-3700-11e7-9c6f-01d24248c00a.png)

58155 주문서는 결제완료 후 주문취소하셔서 카드취소까지 해드린 주문서인데
주문내역에 계속 남아있습니다. 옷장지기가 직접 삭제할 수 있는 기능을 요청하였지만,
실수로 다른 주문서를 삭제할 우려가 있을 것 같아 대여자가 직접 주문취소를 하는 쪽으로 유도하기로 하고
일단은 좀더 생각해보기로 했습니다. 

일단, 58155 주문서 목록에서  삭제요청드립니다~

**Comment by pingpongworks** [comment]
58155 
60307 
61414 
62321
주문서 목록에서 삭제해주세요~

**Comment by aanoaa** [comment]
#147 에서 비슷한 작업을 했던 이력이 있습니다,

**Comment by aanoaa** [comment]
``` sql
DELETE FROM `order` WHERE id IN (58155, 60307, 61414, 62321);
```

**Comment by aanoaa** [comment]
삭제하였습니다.

**Comment by pingpongworks** [comment]
주문서 목록이 말끔해졌습니다~ 감사합니다~~
