### ISSUE TITLE
쿠폰을 이용하여 결제한 경우 주문서 상에서 어떤 쿠폰으로 결제 했는지 내역을 확인 할 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#158]
취업날개로 인해 인식하게된 이슈입니다.

취업날개 쿠폰으로 결제한 경우 주문서 상에 취업날개 쿠폰을 통해 결제했다는 내용을 알 수 있어야 합니다. 이는 비단 취업날개의 이슈는 아니며 쿠폰으로 결제한 경우 결제한 쿠폰의 종류에 따라 그 내용을 확인 할 수 있도록 요청드립니다.

**Comment by 10001if** [comment]
![2017-05-25 4 05 31](https://cloud.githubusercontent.com/assets/4696328/26440028/850c2ca8-4165-11e7-8908-1f19cd68c12b.png)
현재는 이렇게 쿠폰으로 사용했다는 내용만 안내되고 있습니다.

**Comment by aanoaa** [comment]
![default](https://user-images.githubusercontent.com/170528/27271345-30d06f02-54ff-11e7-9cf7-1e9c9d61caea.png)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
