### ISSUE TITLE
취업날개 쿠폰을 사용한 경우 택배비는 지불하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#159]
취업 날개 쿠폰을 통해 대여를 진행한 경우, 현재는 택배비를 포함하여 무료로 대여가 진행됩니다.
하지만 택배비는 개인의 부담으로 결정났기 때문에 택배비 3,000원은 본인이 결제를 완료해야 주문이 확정되도록 수정 요청드립니다.

**Comment by 10001if** [comment]
@keedi 취업날개의 경우 택배비 부담은 본인이 하는 것으로 결정났습니다. 쿠폰으로 사용해보니 택배비까지 결제가 되고 있어서 결과적으로는 저희가 택배비를 대신 내주는 상황이 되었습니다. 신속하게 변경해야 할 이슈입니다. 작업 시간이 되시는대로 요청드립니다. ^^

**Comment by keedi** [comment]
알겠습니다. 금일 확인하고 처리하겠습니다. 내일 반영 가능 여부는 이슈에 남기도록 하겠습니다.

**Comment by keedi** [comment]
더불어 취업날개를 떠나서 모든 쿠폰은 택배비 포함인지요? 아니면 쿠폰마다 별개로 다른지요?

**Comment by 10001if** [comment]
쿠폰마다 별개로 다릅니다. 우선 취업날개는 택배비는 별도입니다.

**Comment by keedi** [comment]
그러면 취업날개를 제외하고는 현재 나머지 쿠폰은 모두 택배비 포함인지요?

**Comment by 10001if** [comment]
네. 현재는 그렇습니다!

**Comment by aanoaa** [comment]
#157 에서 진행중이었습니다.

**Comment by aanoaa** [comment]
#157 과 중복된 이슈이므로 닫겠습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
