### ISSUE TITLE
결제완료 했는데 배송주문서에서 확인 불가능했던 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#160]
**사용자 64916**
가상계좌로 주문하고 결제완료했는데 
온라인 관리메뉴 배송주문서에서 입금완료로 뜨질 않아서
누락되는 바람에 배송을 놓친 경우입니다. 
주문자가 연락을 주셔서 10일 만에 확인이 가능했습니다. 
원인이 무엇인지 확인바랍니다.

**Comment by aanoaa** [comment]
해당 주문서는 `입금대기` 상태 입니다.
아직 결제가 완료되지 않았을때의 상태입니다.

iamport 의 결제승인내역에서 검색해보았는데 결제를 하였습니다.

이건 무슨의미냐면,

결제를 했지만 열린옷장에 반영되지 않은 것 입니다.

--------------------

두가지의 가능성이 있습니다.

1. 결제후에 iamport 에서 hook 메세지를 보내지 않았다.
2. hook 메세지를 정상적으로 처리하지 못했다.

**Comment by aanoaa** [comment]
결제시각이 `2017-05-21 22:45:03` 인데 로그에는 해당 시각에 들어온 요청이 없습니다.

```
opencloset@opencloset1:~/tmp$ egrep 'webhooks' development.log.11 
[Sun May 21 14:22:50 2017] [debug] POST "/webhooks/iamport"
[Sun May 21 15:17:02 2017] [debug] POST "/webhooks/iamport"
[Sun May 21 16:11:28 2017] [debug] POST "/webhooks/iamport"
[Sun May 21 18:15:09 2017] [debug] POST "/webhooks/iamport"
[Sun May 21 20:38:38 2017] [debug] POST "/webhooks/iamport"
```

**Comment by aanoaa** [comment]
시스템이 정상적으로 동작하고 있었다면 iamport 로 부터 hook 을 받지 못했기 때문에
`입금대기 -> 입금완료` 처리가 되지 못했습니다.

**Comment by aanoaa** [comment]
아임포트에 email 을 통해 문의했습니다.

**Comment by pingpongworks** [comment]
네~ 감사요~^^

2017. 6. 1. 오후 12:43 Hyungsuk Hong <notifications@github.com> 작성:

**Comment by aanoaa** [comment]
문의한 내용에 대해 답을 받았습니다.
서비스가 정상적으로 동작하고 있지 않을때에 결제가 이루어져서 발생한 문제입니다.
서비스의 운영 안정성을 높여서 재발하지 않도록 해야 하겠습니다.

```
안녕하세요, 시옷의 장지윤입니다. 

해당 결제건의 경우 notification 을 보냈을 때 502 gateway 에러를 응답받았습니다. 

    요청시각 : 2017-05-21 22:45:43
    URL : https://share.theopencloset.net/webhooks/iamport
    응답본문 <html>

<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.8.1</center>
</body>
</html>

참고로, 200응답이 아닌 경우 재통지 혹은 관리자 알림기능이 6월 중으로 오픈됩니다. 
이 기능을 활용하시면 위 같은 경우를 보다 빠르게 확인하실 수 있을 것 같습니다. 

감사합니다.
```

**Comment by aanoaa** [comment]
서비스는 `Mojo::Server::Hypnotoad` 를 사용하고 있고, hot deployment 를 지원합니다.
서비스 다운타임없이 재시작 가능합니다.

그런데 위와 같은 응답을 받았다는 것은 서비스가 내려가 있었거나 서버가 정상적인 상태가 아니었음을 의미합니다.

**Comment by aanoaa** [comment]
결제한 고객이 시일내에 의류를 받지 못한 심각한 문제입니다.
재발하지 않도록 노력해야 합니다.
