### ISSUE TITLE
취업날개 쿠폰 사용 후 배송비 결제안내

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#161]
쿠폰 사용후에 바로 결제창으로 이동되지 않아서 혼란스럽다.

는 의견이 있습니다.

1. 쿠폰사용
2. 결제버튼 클릭

인데 쿠폰사용 후에 끝난건가? 싶어서 배송비를 결제하지 않는 상태로 남아 있을 수 있을 것 같다는 의견입니다.

`쿠폰을 사용합니다.` 버튼 위에는 아래와 같은 안내가 있긴 합니다.

- 쿠폰을 사용하신 후에는 배송비를 결제해주세요.
- 대여기간을 연장하셨을 경우 연장비와 배송비를 결제해주세요.

---------------------------

구체적으로 어떻게 변경되면 좋겠는지 고민해서 남겨주시면 좋겠습니다.
지금은 좀 어려우니까 알아서 좋게 바꾸는 건 어려운 일입니다.

cc @10001if @pingpongworks

**Comment by pingpongworks** [comment]
테스트해보면서 '쿠폰을 사용합니다' 버튼을 누른 후 안내를 캐치하지 못했습니다. 대여자가 안내만 잘 볼 수 있으면 문제는 없을 듯 합니다. 아직 취업날개 온라인 이용자가 거의 없으니, 문제가 발생하면 다시 요청드리겠습니다~
