### ISSUE TITLE
추석 연휴기간동안 온라인 주문을 할 수 없도록 함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#163]
https://github.com/opencloset/opencloset/issues/1313

2017-09-21 ~ 2017-10-15 사이를 의류착용일로 지정할 수 없도록 해야 합니다.

**Comment by aanoaa** [comment]
2017-09-21 ~ 2017-10-15 사이를 의류착용일로 지정할 수 없도록 하면,
`Wed, 13 Sep 2017 17:30:21 +0900` 기준으로 2017-09-19, 2017-09-20 말고는 선택할 수 있는 날짜가 없습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
2017-09-25~2017-10-18 사이를 의류 착용일로 지정할 수 없도록 수정 부탁드립니다.

**Comment by 10001if** [comment]
@aanoaa 제가 전달을 잘못 한 것 같네요. 수정 요청드립니다.

**Comment by 10001if** [comment]
![2017-09-22 9 33 42](https://user-images.githubusercontent.com/4696328/30724665-712aee9a-9f7a-11e7-88ca-2d3a576edb53.png)
@aanoaa  요청드린 것과 같이 2017-09-25~2017-10-18 사이를 의류 착용일로 지정할 수 없도록 수정되었습니다. 그러나 의류 착용일이 기본으로 지정되어 있어서 지금도 2017-09-25~2017-10-18 사이에 주문을 할 수 있도록 되어 있습니다. 실제로 오늘 하나의 주문이 들어왔습니다. 2017-09-25~2017-10-18 사이에는 의류 착용일을 누를 수 없게 하는 것 뿐만아니라 아예 지정이 되지 않게 수정을 요청드립니다.

**Comment by aanoaa** [comment]
2017-10-18 이후에는 revert 작업해서 다시 배포해야 합니다.
