### ISSUE TITLE
온라인 주문서 리스트에서 주문서 삭제

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#164]
id | 대여자 | 희망의류 | 종류 | 코멘트 | 발송(예정)일 | 도착(예정)일 | 의류착용일 | 상태
-- | -- | -- | -- | -- | -- | -- | -- | --
65847 | 고** | 없음 | 자켓 스커트 블라우스 구두 |   | 2017-06-27 | 2017-06-29 | 2017-06-30 | 결제완료
71382 | 이** | 없음 | 자켓 스커트 블라우스 구두 |   | 2017-08-23 | 2017-08-25 | 2017-08-28 | 결제완료
74764 | 강** | 없음 | 블라우스 구두 |   | 2017-09-22 | 2017-09-26 | 2017-09-27 | 결제완료
74771 | 황** | 없음 | 자켓 스커트 블라우스 |   | 2017-09-22 | 2017-09-26 | 2017-09-27 | 결제완료

이상의 주문서는 오프라인으로 직접 수령하는 등 다른 루트를 통해 대여가 진행되어서 온라인 주문서에서 반납으로 변경되지 못했습니다. (현재상태는 결제완료) 오프라인으로 주문한 경우 새 주문서를 만들어 진행했습니다. 4개의 주문서는 삭제 요청 드립니다.

**Comment by aanoaa** [comment]
#147, #156 과 같은 작업입니다.

```sql
DELETE FROM `order` WHERE id IN (65847,71382,74764,74771,88445,89921,91306,91870,92212,92759,93232,93437,96847,98107);
```

삭제하였습니다.
