### ISSUE TITLE
특정 사용자의 폰에서 결제가 진행되지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#165]
/orders/76580 주분서의 사용자가 결제를 시도하였으나 결제 창이 뜨지 않아 결제를 하지 못하고 합니다. 안드로이드 스마트폰으로 결제를 진행하였다고 하네요. 지난 주에 결제 실패 문의가 2~3건 들어 왔었습니다. 결제가 되지 않는 주문서는  /orders/758442 주문서도 마찬가지입니다. 확인 부탁드립니다.

**Comment by 10001if** [comment]
그런데 이 경우, 주문서를 주문확정하면 온라인 페에지 주문 목록에 뜨나요? 그렇다면 이런 경우에 급하게 대여를 해야하는 경우라면, 가상계좌로 지급받고 주문을 확정하려고 합니다.

**Comment by aanoaa** [comment]
걱정이 되던 것은 모든 결제 시스템에 문제가 있어서 결제가 안되는 상황인데,
76580 주문서 이후에 온라인으로 결제가 된 주문서가 있는 것으로 보아 결제 시스템은 동작하고 있는 것 같습니다.

**Comment by aanoaa** [comment]
> 그런데 이 경우, 주문서를 주문확정하면 온라인 페에지 주문 목록에 뜨나요? 그렇다면 이런 경우에 급하게 대여를 해야하는 경우라면, 가상계좌로 지급받고 주문을 확정하려고 합니다.

온라인 주문서의 주문을 확정할 수 있는 방법이 있나요?
staff 에서 주문확정한다는 말씀이신가요?


결제가 완료되면, 주문서의 상태가 결제완료로 변경되고, 대여일이 확정됩니다.
추가로 주문서 택배 조회를 위한 작업이 되고 사용자에게 결제내역을 안내하는 SMS 와 email 을 발송합니다.

위 절차를 staff 에서는 지원하고 있지 않습니다.
이런 경우를 대비해서 온라인주문서 에서 가상계좌를 발송하고 입금되면 정상적인 절차를 통해 상태가 변경되는 기능이 더 적절한 것 같습니다.

**Comment by aanoaa** [comment]
![default](https://user-images.githubusercontent.com/170528/31592669-ddf9bb94-b264-11e7-9097-6662259282b6.png)

이 상태에서 주문확정을 하면 어떻게 될지는 안해봐서 모르겠습니다.

주문을 확정할 수 있다고 하더라도
모든 의류코드가 없기 때문에 의류들의 상태를 대여중으로 바꿀 수 없습니다.

**Comment by 10001if** [comment]
@aanoaa 그러네요. 코드가 입력되어 있지 않아 주문 확정이 되지 않겠네요. 이야기 주신 것처럼 결제가 오류 있는 경우에 가상계좌로 대처하는 방법이 적절한 것 같습니다.

**Comment by 10001if** [comment]
@aanoaa 오늘도 /orders/76703 결제 오류라는 안내가 왔습니다. 바로 발송해야 하는 것들이 있어서 그럼 우선~ 해결 될 때까지 주문서를 새로 생성해서 발송하도록 하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 경우에 따라 결제가 진행되지 않는 이유들이 있을 것 같은데요. 

>위 절차를 staff 에서는 지원하고 있지 않습니다.
이런 경우를 대비해서 온라인주문서 에서 가상계좌를 발송하고 입금되면 정상적인 절차를 통해 상태가 변경되는 기능이 더 적절한 것 같습니다.

언급해 주신 것처럼 가상계좌를 통해 전체 프로세스를 이어가도록 요청드립니다.

**Comment by 10001if** [comment]
특정 이슈가 다시 발생하면 그때 다시 열도록 하겠습니다.
