### ISSUE TITLE
결제대기 주문서에 가상계좌를 전송하는 기능

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#166]
#165

staff only 기능으로, 어딘가에 가상계좌를 만들어서 보내는 기능이 필요합니다.
이때에 문자메세지 내용이 정해져야 합니다.

온라인 주문서의 특성상 입금 유효기간의 설정도 고민해봐야 합니다.
착용일을 따져보고 언제까지 입금이 가능할지 고려해봐야 합니다.

**Comment by 10001if** [comment]
/orders/77807 주문서도 결제가 되지 않는다고 합니다. 연휴 이후로 결제가 되지 않는 건이 증가한 것 같습니다. 원래 프로세스로 진행이 되지 않아 소통의 오류가 커지고 있습니다. 빠른 작업 요청드립니다~

**Comment by aanoaa** [comment]
staff 계정으로는 대신 결제를 할 수 있습니다.(결제를 진행합니다 버튼을 누를 수 있습니다)
이때 방식을 가상계좌로 해서 대신 신청해주면 될 것 같습니다.

**Comment by aanoaa** [comment]
지금 이대로 쓸수는 없습니다.
계좌명이 로그인한 계정이름입니다.
주문서의 사용자명이 계좌명이 되어야 합니다.

추가적으로 로그인한 사용자가 아닌 주문서 사용자 정보로 SMS 및 email 이 전달되는지 확인해야 합니다.

**Comment by aanoaa** [comment]
결제를 할 수 없는 주문서가 있을때에는 staff 계정으로 들어가셔서 대신 가상계좌를 신청해주시면 됩니다.
SMS 와 email 이 전송되고 입금되고 난 후에는 다른 주문서와 같이 상태가 자동으로 변경됩니다.

**Comment by aanoaa** [comment]
근데 테스트를 못해봤습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 정상적으로 잘 진행되고 있습니다. 감사합니다. ^^
