### ISSUE TITLE
안양시 쿠폰으로 결제하는 경우, 택배비를 결제하지 않도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#167]
안양시에서 안양시 쿠폰으로 이용하는 모든 대여자들에게는 택배비를 전부 무상으로 진행하게 해달라는 요청이 있었습니다. 현재까지 안양시에서 택배 대여를 진행한 경우가 많지 않아 큰 이슈가 되지 않았는데, 앞으로는 모든 택배비에 대해 후불로 안양시에서 부담한다고 합니다. 따라서 결제시에 택배비를 결제받지 않도록 해야 합니다.

**Comment by 10001if** [comment]
현재는 3,000원의 택배비용을 결제해야 주문이 완료되도록 설정이 되어 있습니다.

**Comment by 10001if** [comment]
중요한 이슈가 아닌데, 시 정책 사항으로 요청한 내용이라 빠른 수정이 필요합니다. 지금 하시는 작업 마무리 하시고 완료되면 이슈 해결 요청드리겠습니다~

**Comment by aanoaa** [comment]
이것도 3000원 우선 결제받고 택배 상자에 3000원 넣어보내드리면 안되나요?

**Comment by 10001if** [comment]
@aanoaa 안되지는 않습니다. 현재도 그렇게 진행하고 있는데요. 문제는 택배비 무료로 알고 있는 상황에서 결제가 필요하기 때문에 결제 행위에 대한 문의가 발생합니다. (무료로 알고 있는데 왜 결제하나요? 와 같은 문의죠~)

3000원을 넣어 보낸다면, 결제 전에 관련한 안내가 필요할 것 같은데요. 
안양시, 군포시는 택배비도 지원합니다. 결제시 지불한 택배비 3,000원은 의류 발송 시 동봉하여 넣어보내드립니다. 
와 같은 이야기가 결제 시에 전달되어야 합니다.

**Comment by aanoaa** [comment]
#200 에서 해결되었기 때문에 쿼리문 한번으로 적용할 수 있습니다.
쿤포시 쿠폰의 테스트가 끝나면 안양시 쿠폰에도 적용하도록 하겠습니다.

**Comment by aanoaa** [comment]
안양시 쿠폰종류가 두개 입니다.

- anyang201801
- anyangyouth

안양시의 청년옷장 이벤트 쿠폰인데 해가 바뀌면서 쿠폰이름도 바뀌었습니다.(https://github.com/opencloset/opencloset/issues/1364)
이러면 통계작업을 다시 해야 해서 번거롭습니다.
여기서 말하는 안양시 쿠폰이란 `anyang201801` 를 말하는 것 입니다.

**Comment by aanoaa** [comment]
내용을 확인해보니 쿠폰사용횟수 제한 때문에 부득이하게 쿠폰이름이 바뀌었습니다.
배송비를 처리하기전에 다시 누락된 통계를 채우고 오늘부터 수집될 수 있도록 작업하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 쿠폰이름이 바뀌면 통계작업을 다시 하셔야 하는군요..
번거롭더라도, 작업 요청드리겠습니다.

**Comment by aanoaa** [comment]
배송비 무료 쿠폰으로 변경하였습니다.

```
mysql> UPDATE coupon SET free_shipping = 1 WHERE `desc` = 'anyang201801';
Query OK, 300 rows affected (0.04 sec)
Rows matched: 300  Changed: 300  Warnings: 0
```

**Comment by 10001if** [comment]
@aanoaa 감사합니다.

**Comment by keedi** [comment]
그런데 쿠폰은 애초에 사용횟수랑 별개로 나누는 것이 적절합니다. 그렇지 않으면 분기별로 쿠폰 구분하기가 어려워집니다. 이리되면 총합을 구할 수 없지만 총합은 더하면 되는 것인데 뭉터기로 있는 것을 구분하기는 더 복잡하기 때문입니다. 또한 사용 제한을 떠나 이전 분기의 발행했다가 남은 쿠폰의 경우 관리도 그렇고 복잡하지요. 쿠폰은 예산에 따라 추가 발행하는 경우를 제외하고 명확히 사업 시즌이 끝나면 쿠폰 이름을 변경하는 것이 옳다고 봅니다.

기존 anyangyouth 이름이 anyang20xxxx 로 변경하는 편이 이후 관리상 편할 듯하지만, 하드 코딩 되는 부분을 다 확인하기 어렵다면 그냥 내버려두는 방법도 있습니다.
