### ISSUE TITLE
신체치수 입력시 나타내는 평균치수와 staff의 신체치수 예측 값이 다름

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#169]
우연히 발견하게 되었는데요. 온라인 이용자 중 한 명이 본인의 신체치수를 입력하지 않고 키와 몸무게를 입력한 뒤 나타나는 평균치수를 그대로 입력한 대여 건이 있었습니다. 치수가 좀 이상하게 입력된 것 같아 유선으로 통화하다가 발견했는데요. https://staff.theopencloset.net/size/guess 메뉴에 173/75/남성을 입력한 결과 

173 / 75 / 남성 | 배꼽 | 윗배 | 가슴 | 팔 | 엉덩이 | 허벅지 | 허리 | 무릎 | 다리 | 발
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
47명 |                 86.3        |           84.1          |       97.8 |                59.9 |              99.7 |                 57.9 |            86.9 |                51.6 |                98.7 |                 262.5

이었지만 온라인 치수측정란에 나타난 평균치수는 

키 cm | 몸무게 kg | 허리둘레 cm | 가슴둘레 cm | 윗배둘레 cm | 팔길이 cm | 허벅지둘레 cm
-- | -- | -- | -- | -- | -- | --
173 | 75 | 84 | 96 | 81 | 61 | 57

이었습니다. 서로 치수가 다른 것을 확인하고 문의드립니다. 

어떤 정보가 정확한 정보인지 모르겠지만 정확한 정보 쪽으로 동일하게 수정을 요청드립니다.

@aanoaa @keedi

**Comment by 10001if** [comment]
@aanoaa 제가 어제 온라인 대여를 맡아서 진행해보니, 평균값 차이로 인해 의류를 찾을 때 문제가 발생하고 있었습니다. 위의 사례에서 보듯이 윗배, 허리가 3cm 차이가 발생하여 어떤 값을 기준으로 해야 하는지 혼동이 있습니다. 확인 부탁드립니다.

**Comment by aanoaa** [comment]
![default](https://user-images.githubusercontent.com/170528/32770163-f69bd7ae-c961-11e7-8ce8-e724c25f52fa.png)

**Comment by aanoaa** [comment]
![default](https://user-images.githubusercontent.com/170528/32770411-e1a31ad2-c962-11e7-8fa2-572923f4d59d.png)

**Comment by aanoaa** [comment]
staff 의 신체 치수 예측과 share 의 치수측정에서의 평균값이 왜 다른지부터 살펴보았습니다.

### staff ###

- 키/몸무게/성별 만 입력
- 열린옷장의 DB 결과를 나타냄
- Bodykit 의 결과를 나타냄
- 기타 추가정보

### share ###

- 열린옷장의 DB 결과만 나타냄
- 키/몸무게/성별
- 허리/가슴/윗배/엉덩이 둘레도 입력가능

------------------------------------------------

위에 비교해주신 사이즈는 열린옷장 DB 의 데이터를 적어주신 것으로 보입니다.
키와 몸무게만 입력했을때에는 staff 와 같은 결과를 얻었습니다.

> 173cm(키) 75kg(몸무게) 86cm(허리) 97cm(가슴) 84cm(윗배) 의 평균 신체 치수입니다.

동일한 모듈을 사용하고 있지만 입력 옵션의 차이가 있습니다.
키/몸무게 이외의 신체치수를 입력했을때의 차이가 아닌가 싶습니다.

**Comment by aanoaa** [comment]
@10001if 확인해보시고 어떻게 해야할지 알려주세요.

**Comment by 10001if** [comment]
@aanoaa 구분해서 구체적으로 설명해주셔서 감사드립니다. https://github.com/opencloset/OpenCloset-Share-Web/issues/114 에서 써주신 내용을 보니 원래 처음부터 이렇게 작동하고 있었네요. 이 이슈는 제가 기능을 정확히 확인하고 있지 못해 작성한 건입니다. 프로그램에 문제가 있는 것이 아니기 때문에 기능 수정이 필요하면 차후에 다시 남기도록 하겠습니다. 

그런데 한가지 궁금한 것이 있습니다.

114번 이슈에 

>키/몸무게/성별을 가지고 신체치수를 추정할 수 있는 기능이 있습니다.
이 기능에 각 신체치수를 더 입력해서 더 정확한 결과를 받고 싶습니다.
신체치수를 더 입력한다고 더 정확한 결과가 나오는 것은 아니라고 합니다.

라는 이야기가 적혀 있는데. 현재 평균 사이즈를 보여주는 방식이
![2017-11-22 11 35 19](https://user-images.githubusercontent.com/4696328/33107471-c195012e-cf7a-11e7-88a0-be7542f82280.png)
빨간 박스와 같은 형식의 추정인가요? 현재 키/몸무게/성별 외에 다른 사이즈를 입력하면 평균값이 변동되는 이유가 궁금합니다.

**Comment by aanoaa** [comment]
추가 정보가 입력될때마다 집단대상의 범위가 좁혀집니다.

**Comment by aanoaa** [comment]
추정아닙니다 평균입니다.
가지고 있는 데이터의 평균값입니다.

**Comment by 10001if** [comment]
@aanoaa 제가 이해하고 있는 것과 동일한 개념이네요. 그렇다면 오히려 share의 평균값이 더 정확하게 나타나겠네요. 내용에 대해 확인했기 때문에 이슈 닫도록 하겠습니다. 친절하게 설명해 주셔서 감사드립니다.

**Comment by aanoaa** [comment]
> 그렇다면 오히려 share의 평균값이 더 정확하게 나타나겠네요. 

꼭 그렇지만도 않습니다.

https://github.com/opencloset/OpenCloset-Share-Web/issues/114#issuecomment-285294012

> 신체치수를 더 입력한다고 더 정확한 결과가 나오는 것은 아니라고 합니다.

**Comment by 10001if** [comment]
@aanoaa 더 정확한 결과라는 표현이 잘못되었네요. share의 집단이 더 좁혀진 상태에서 평균값이 도출되는 것으로 이해했습니다.
