### ISSUE TITLE
메일서버의 구성

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#17]
메일을 보낼 수 있는 SMTP 서버가 필요합니다.

`mail.theopencloset.net` 이면 좋겠습니다.

**Comment by yongbin** [comment]
예전에도 비슷한 이슈가 있었는데 찾아보고 진행하겠습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/volunteer/issues/9#issuecomment-138255481

이때의 문제 때문에 한번 작업해주신적이 있는데 기록이 gh 에는 기록이 남아있지 않습니다.

**Comment by yongbin** [comment]
테스트 서버 로컬에서 메일이 발송하도록 하는 이슈는 Bug 758에 비교적 자세하게 기록되어있습니다. 그 내용을 바탕으로 테스트 서버에서 외부로 메일 발송이 가능하도록 세팅을 완료했습니다.

**Comment by yongbin** [comment]
> mail.theopencloset.net 이면 좋겠습니다.

궁극적으로는 메일 발송을 위한 전용 SMTP 서버 구축이 목적이었지만 현재는 메일 발송양이 많지 않고 SMTP 단독 운영이 번거롭고 복잡하기떄문에 테스트 장비에 SMTP outbound 설정 및 SPF 레코드 등록으로 대체했습니다.

추후 메일발송이슈가 많아지면 별도 이슈에서 진행하도록 하겠습니다.
