### ISSUE TITLE
최근구매내역의 페이지가 정상적으로 뜨지않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#171]
/orders/12602/purchase

에서 보면, 
![2017-11-01 4 21 18](https://user-images.githubusercontent.com/4696328/32264477-2a3c4d54-bf22-11e7-80ce-e7707a83193a.png)

9월 10일 클릭하면 502 Bad Gateway가 뜨면서 정상작동 하지 않습니다. 확인 부탁드릴게요~

**Comment by aanoaa** [comment]
발생하는 오류입니다.

    [Wed Nov 15 06:08:13 2017] [error] Can't call method "sms_bitmask" on an undefined value at template partials/sms-help.html.ep line 1.

에러처리가 제대로 안된 것 인지, 꼭 들어가야 하는 값이 비어있는 것인지 확인해봐야 합니다.

**Comment by aanoaa** [comment]
해당 주문서는 결제방법이 현금이고 반납일이 2015-09-10 입니다.
온라인 서비스가 시작된 것이 2017-01-26 입니다.

아주 예전에 온라인으로 대여했던 주문서이력이 남아있는 것 같습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
