### ISSUE TITLE
당일 발송 목록 주문서만 확인하고자 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#172]
발송예정일로는 검색할 수 없다는 사실은 #113 이슈를 통해 이해했습니다.

이 이슈가 작성될 당시에는 하루에 온라인 건 수가 대부분 5건미만 이어서 큰 문제가 없었다고 판단했는데, 최근에 온라인 대여건수가 늘면서 20건 가까이 되는 날(수요일의 경우) 실수로 당일 발송해야 하는 주문서를 놓치는 경우가 있었습니다. 좋은 방법이 떠오르지 않아 눈으로 분명하게 확인 할 수 있도록 요청드리고자 합니다.

![50b27b90-0fdf-11e7-8f76-a41873e18a0c](https://user-images.githubusercontent.com/4696328/32768825-cff898da-c95c-11e7-8e44-5b8aedf11f80.png)

현재로 당일은 초록색으로 표시해 주고 계시지만, 면적이 작아, 실수가 발생할 여지가 있는 것 같습니다. 당일 발송 목록을 한번에 모아서 보기 힘들다면 다음과 같이 조금 더 분명하게 표시를 해주면 좋을 것 같습니다.

**Comment by 10001if** [comment]
@aanoaa 이렇게 표시하는 것은 확인을 용이하게 할 뿐 적극적인 개선책은 아닌데요.

다시 생각해보니 단순하게 착용일을 하루만 볼 수 있는 것이 아니라 착용일을 and 조건으로 여러날을 동시에 확인할 수 있으면 될 것 같습니다. 주문서 목록 상단에 '당일발송 목록확인' 버튼을 만들고 그 버튼을 누르면 아래와 같은 달력이 나타납니다. 
![2017-11-14 5 19 02](https://user-images.githubusercontent.com/4696328/32769635-0e923418-c960-11e7-80f2-b9413e8ee94a.png)
의류착용일을 누르면 해당 착용일의 주문서가 보이고, 달력을 다시 클릭해 다른 착용일을 누르면 기존 착용일에 더해 추가적으로 주문서가 보이도록 합니다. 착용일을 잘못 누를 경우를 대비하여 착용일을 삭제할 수 있도록 하는 기능도 필요합니다. 

![2017-11-14 5 21 08](https://user-images.githubusercontent.com/4696328/32769956-342f4692-c961-11e7-83e5-1ebcd4947b1b.png)

**Comment by 10001if** [comment]
그리고 주문서 ID 우측에 1, 2, 3 과 같이 순서 넘버링이 되는 것이 필요합니다. 하루에 보낼 양이 몇 건인지 확인하는 것이 필요한데 송장을 뽑거나 의류 포장완료 후 전체 수량을 체크하는데 검수 자료가 되기 때문입니다.

**Comment by pingpongworks** [comment]
이미 의류착용일 클릭으로 당일배송 주문서만 확인가능하므로 이슈 닫습니다.
