### ISSUE TITLE
대여품목을 추가하는 기능

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#177]
최근에 온라인 대여건 수가 많아지면서 조금 다양한 경우들이 발생하였는데요.

가장 대표적인 것이 초기에는 보이지 않던 온라인 주문서 수정 건입니다.

주문서의 품목이나 기간 등을 수정해야 하는 경우. 현재 옷장지기가 할 수 있는 방법은 직원예약을 통해 온라인 체크를 하여 온라인 주문서를 생성하여 포장상태에서 주문서를 확정하는 것인데요. 이 경우에는 share의 주문서 목록에 포함되지 않아 온라인 담당자가 발송을 할 때 기억하고 있다가 온라인 배송주문서와 staff에서 사용자 검색을 통해 주문서를 찾아 발송하는 방법 밖에 존재하지 않습니다.

따라서 요청드리고자 하는 것은 ***담당자가 온라인 주문서를 만들어 확정하면 그 내역을 share 에서도 확인할 수 있도록 하는 것입니다.*** 그런데 이 같은 프로세스가 일반적이지 않는 것처럼 보이기도 하는데요. 그렇다면 share 페이지에서 온라인 주문서를 다시 만들어 임의로 주문서를 확정하여 주문서 목록에서 확인하는 것이 어떨까 싶습니다.

온라인 대여를 하는 사용자 입장에서는 share에서 주문서를 바로 만들어 대여 품목을 입력하여 주문서를 확정하면 기존처럼 주문서 목록에서 확인하도록 하는 방법이 더 효과적으로 보입니다. 간단한 문제가 아닌 것 같아 @aanoaa 께 다시 설명 드리도록 하겠습니다.

**Comment by aanoaa** [comment]
새로 주문서를 만들어서 해결하면 될 것 같다고 생각하신 것 같습니다.
staff 계정으로 접근했을때에는 주문서를 마음대로 수정하는 기능이 더 수월할 것 같다고 얘기하고 동의를 얻었습니다.

**Comment by aanoaa** [comment]
복수의 품목을 주문할 수 없던 문제인 #176 의 오류도 함께 해결되어야 합니다.

**Comment by aanoaa** [comment]
여러벌 대여를 할때에는 쿠폰도 고려되어야 합니다.
자켓 5벌을 단벌쿠폰로 대여할 수는 없어야 합니다.

**Comment by aanoaa** [comment]
해결하고자 하는 것은,
모든품목들을 한개씩만 주문할 수 있는 것이 아니라 각각 여러벌 주문할 수 있도록 하고 싶은 것 입니다.
같은 품목이 여러개가 된다는 것은 치수가 각각 달라야 할 가능성이 큽니다(혼자서 여러벌을 입지는 않으니까)

각각의 치수를 어떻게 할 것인지를 여의치 않는다면 주문확정이나 입금후가 아닌 주문할때에 각각의 품목을
추가할 수 있도록 하는 것이 편리할 것 같습니다.

자켓 x 3
팬츠 x 3

이 된다면 63,000 을 결제해야 합니다.
지금은 63,000 을 결제할 방법이 없습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
