### ISSUE TITLE
취업날개 쿠폰을 통해 온라인 예약을 하는 대여자는 입사 면접만 목적으로 선택할 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#178]
https://github.com/opencloset/opencloset/issues/1324 이슈와 같은 내용입니다.

취업날개의 이용목적은 면접으로만 가능하게 규정이 변경되었기 때문에 오프라인 예약시 취업날개 쿠폰 사용의 경우에는 입사면접만 목적 선택이 가능하도록 고정 값으로 목적을 수정해 주셨는데요. 온라인도 동일하게 적용되어야 합니다. 요청드립니다.

**Comment by aanoaa** [comment]
온라인은 대여목적을 미리 선택하고 결제수단에서 쿠폰을 사용합니다.
대여목적란에 취업날개 쿠폰 이용에 대한 안내가 우선되고,
이후에 쿠폰으로 결제할때에 입사면접이 아닐경우에 대한 에러처리를 하면 되지 않을까 싶습니다.

--------------------------

1. 대여목적에 안내 메세지가 추가

> 서울시 취업날개는 규정상 입사면접 용도로만 이용할 수 있습니다. 다른 용도로 이용해야 한다면 서울시에 문의해주세요.

2. 쿠폰으로 결제하는데 그 쿠폰이 취업날개이지만 대여목적이 입사면접이 아닐때에 결제를 할 수 없도록 하고 같은 메세지를 나타냅니다.

> 서울시 취업날개는 규정상 입사면접 용도로만 이용할 수 있습니다. 다른 용도로 이용해야 한다면 서울시에 문의해주세요.

**Comment by aanoaa** [comment]
@10001if 님에게 피드백을 받아서 메세지내용이 변경되었습니다.

1. 대여목적에 안내 메세지가 추가

> 서울시 취업날개는 규정상 입사면접 용도로만 이용할 수 있습니다. 대여목적을 입사면접으로 선택하는 경우에만 취업날개 쿠폰 이용이 가능합니다.

2. 쿠폰으로 결제하는데 그 쿠폰이 취업날개이지만 대여목적이 입사면접이 아닐때에 결제를 할 수 없도록 하고 같은 메세지를 나타냅니다.

> 대여목적이 입사면접이 아니므로 취업날개 쿠폰을 이용할 수 없습니다.
> 다른목적으로 이용하길 원하는 경우 대여주문서를 다시 작성해주세요.

**Comment by aanoaa** [comment]
OpenCloset::Plugin::Helpers 의 `transfer_order` 의 기능은 OpenCloset::API 의 `transfer_order` 로 마이그레이션 되었습니다.

남아있기는 하지만 deprecate 되었습니다. share 에서는 여전히 `OpenCloset::Plugin::Helpers::transfer_order` 를 사용중입니다.

**Comment by aanoaa** [comment]
![2017 11 15 14 11 50](https://user-images.githubusercontent.com/170528/32819918-2306dfde-ca0f-11e7-8408-5d144004719d.png)

**Comment by aanoaa** [comment]
![default](https://user-images.githubusercontent.com/170528/32820075-ea330326-ca0f-11e7-9de6-224fd4d083ea.png)

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
