### ISSUE TITLE
결제마감시한이 지났을 경우에도 결제를 진행할 수 있도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#182]
현재 결제 마감시한은 https://github.com/opencloset/OpenCloset-Share-Web/issues/173 이슈에서 수정한 바와 같이 9시 입니다. 따라서 9시가 지난 주문서는 아래와 같은 문구와 함께 안내가 되고 있습니다. 
![32940715-ca0d39be-cbc6-11e7-8159-a86500008aa5](https://user-images.githubusercontent.com/4696328/33113218-a1f4a9e4-cf9a-11e7-91ec-478e92c599e0.png)

그런데 실제로 온라인 대여를 진행하다보면 9시 넘어서 대여를 해야하는 경우가 많이 발생하고 있다고 합니다. 그런데 이 경우에는 주문서를 새로 만들어야 하고 이런 경우에도 share 목록엔 뜨지 않아 발송을 하는 입장에서 번거로운 상황이 발생한다고 합니다. 따라서 이를 해결하기 위해 요청드리고자 합니다.

제가 생각한 방법은 2가지 입니다.

1. 주문서의 상태를 옷장지기가 결제완료로 바꿀 수 있도록 합니다. 이 경우 주문서 상태를 바꾸기 전에 가상계좌로 입금을 안내하고 입금이 완료되면 수동으로 주문서를 변경하고자 합니다. 주문서를 변경하면 share 주문서 목록에 나타나도록 합니다.

2. 결제 마감시한이 지났을 경우에라도 연장 버튼을 누르면 결제 마감시한이 1시간 연장되도록 하고자 합니다. 그래서 그 대여자가 결제를 진행할 수 있고 이렇게 결제를 완료하면 정상적인 결제가 되도록 하는 것입니다. 

보시고 의견 남겨주시면 좋을 듯 합니다~

**Comment by 10001if** [comment]
제 생각엔 마감시한이 1시간 연장되는 것이 더 적절할 것 같은데요. 1시간 연장 된 상황에서 대여자가 금액을 입금하면 ㅈ문서는 결제완료 상태로 변경되는 것입니다.

**Comment by aanoaa** [comment]
당일 출발하는 택배의 마지막 주문은 AM 9시 까지만 받되, 결제는 AM 10시 까지로 하고 싶으신 건가요?

**Comment by 10001if** [comment]
일반적으로는 말씀하신 것처럼 결제만 1시간 뒤로 하면 문제가 해결될거라 생각했는데. 이용자가 10시 이후에도 연락을 주고 있다고 하네요. 택배를 보내는 마지막 마감시한이 명확하지 않지만 12:00 ~ 13:00 까지도 택배를 발송할 수가 있어서 담당자 판단에 따라 보낼 수 있다면 바로 입금기한을 연장하여 주문서를 결제완료 상태로 변경하려고 합니다. 연장시간을 1시간 뒤로 하려는 이유는 한 시간이면 결제를 하는데 문제가 없다고 생각하기 때문입니다.

**Comment by aanoaa** [comment]
staff 의 역량껏 입금할 수 있도록 해주는 방법이 필요한 것 같습니다.
가상계좌로 입금하려는 경우가 문제가 될 수 있을 것 같습니다.

한시간이니 두시간이니 이런 것 보다는 버튼 한번으로 입금마감시간이
지난 주문서일지라도 입금할 수 있도록 변경해주는 기능이 어떨까 싶습니다.

검색도 거의 안쓰실 것 같은데, 검색창에 사용자 이름, 주문서번호, 핸드폰번호, 이메일로 검색해서
바로 주문서로 들어가고 거기에서 버튼 한번 누르는 것으로 처리될 수 있도록 하는 방법은 어떤가요?

**Comment by 10001if** [comment]
>검색도 거의 안쓰실 것 같은데, 검색창에 사용자 이름, 주문서번호, 핸드폰번호, 이메일로 검색해서
바로 주문서로 들어가고 거기에서 버튼 한번 누르는 것으로 처리될 수 있도록 하는 방법은 어떤가요?

-> 이런 방법이면 제가 요청드린 문제를 정확하게 해결할 수 있을 것 같습니다. 이야기 주신 것처럼 시간 단위로 진행하면 또 같은 문제가 반복될 가능성이 있다고 생각합니다.

**Comment by aanoaa** [comment]
입금이 허용된 주문서를 가상계좌로 결제할 경우 현재시간 + 2h 로 설정해주도록 하겠습니다.
다른 결제수단은 입금마감시간이 결제에 영향을 주지 못합니다.

**Comment by aanoaa** [comment]
입금기한이 지났음에도 입금을 허용한다 라는 뜻의 적절한 단어의 조합이 있으면 좋겠는데..
이런경우는 일회성 데이터라서 schema 를 변경하지 않고 해결하고 싶습니다.
redis 를 이미 쓰고 있으니 redis 쓰면 어떨까 합니다.

**Comment by 10001if** [comment]
>입금이 허용된 주문서를 가상계좌로 결제할 경우 현재시간 + 2h 로 설정해주도록 하겠습니다.
다른 결제수단은 입금마감시간이 결제에 영향을 주지 못합니다.

제가 잘 이해를 못한 것 같네요. 

검색을 통해 주문서로 들어가고, 그 곳에서 버튼을 누르면

1. 가상계좌 : 현재시간 + 2h 로 입금 마감시한이 늘어나고
2. 다른 결제수단(신용카드 등) : 입금마감시한이 결제에 영향을 미치지 않기 때문에 버튼을 누르지 않아도 관계가 없게 변경되는 건가요?

**Comment by aanoaa** [comment]
![screenshot-2017-11-23 2017-11-20 19 01 42](https://user-images.githubusercontent.com/170528/33164463-49eaa654-d076-11e7-922c-edf72d52cc9b.png)
![screenshot-2017-11-23 2017-11-20 19 01 42 1](https://user-images.githubusercontent.com/170528/33164464-4a158090-d076-11e7-9518-b5de1b0fe93a.png)

**Comment by aanoaa** [comment]
결제대기가 아니라 입금대기일때에도 위 버튼이 나타나야 합니다.

**Comment by 10001if** [comment]
@aanoaa 아시는 것처럼 입금대기 상태인 경우에 문제가 훨씬 더 많이 발생합니다. 신용카드 결제는 거의 즉시 이뤄지는 경우가 많은데에 반해 가상계좌(무통장입금)은 차후에 하는 빈도가 훨씬 자주 발생하기 때문입니다. 입금대기 일때도 위 버튼이 나타나도록 수정 요청드립니다~

**Comment by aanoaa** [comment]
입금대기의 경우라면 이미 발급된 가상계좌의 입금만료시간이 지난 것 입니다.
다시 결제할 수 있도록 해주는 방법도 가능하지만 이미 발급된 가상계좌의 마감시간을 늘려주는 방법도 가능합니다.

사용자입장에서는 결제수단을 스스로 선택할 수 있는 첫번째 옵션이(다시 결제할 수 있도록 해주는 방법) 더 좋을 것 같습니다.

---------------------------------

하나의 주문서에 가상계좌가 두개이상 발급되었을때에 서비스에 영향이 없는지 검토해봐야 합니다.

**Comment by 10001if** [comment]
@aanoaa 입금대기 상태에서 결제마감시한이 지났을 때 결제를 다시 진행할 수 있는 방법이 생긴건가요? 이슈에서는 내용을 확인할 수 없어 문의드립니다~

**Comment by aanoaa** [comment]
네 맞습니다.
입금대기 이지만 입금마감시간이 지난 주문서에 대해서 다시 결제를 할 수 있도록 관리자용 버튼을 추가하였습니다.
방법은 결제대기 주문서와 비슷합니다.

**Comment by 10001if** [comment]
결제대기, 임금대기자의 주문서를 직접 확인하지 못했습니다. 확인 후 이슈우선순위에서 제거하도록 하겠습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
