### ISSUE TITLE
취업날개 온라인 대여자 집계가 잡히지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#183]
취업날개 인원이 정산되는 서울시 제공 홈페이지를 보면
![2017-11-20 10 55 21](https://user-images.githubusercontent.com/4696328/33002795-bc395874-cdf9-11e7-8e6f-c7d0b9e20dd9.png)
8월 이후로 9월 10월 11월에 온라인(택배) 수가 나타나지 않고 있습니다. 

실제로 온라인 누적 인원 수가 표시되는 통계에서 살펴보아도
![2017-11-20 10 55 32](https://user-images.githubusercontent.com/4696328/33002825-e981f174-cdf9-11e7-9412-8b774570337e.png)
9월 이후에도 택배 대여는 진행이 되었습니다.

이와 관련해서 서울시 정산 페이지와 우리 통계페이지 간의 정보가 일치하지 않는 부분이 있는지 확인 요청드립니다.
숫자 관련해서 1,2명씩 차이가 나는 부분은 시점 차이가 있어 발생하고 있는 것으로 이해 했는데요. 저희 입장에서는 전체 인원 수만 일치하면 되는 문제인데. 이 경우처럼 애초에 집계가 안되는 건 또 다른 문제라고 판단되어 이슈로 남깁니다. 확인 요청드립니다~

**Comment by aanoaa** [comment]
11월에 취업날개 서비스로 온라인 대여한 건을 찾아보았습니다.

![screenshot-2017-11-20 2017-11-19 23 41 55](https://user-images.githubusercontent.com/170528/33003136-1f455862-cdfc-11e7-88f0-d21f65540206.png)

https://share.theopencloset.net/orders/82287

이 사용자의 코드번호를 가지고 취업날개 예약내역에서 검색해봤더니 결과가 없습니다.
왜 없는지를 알아봐야 할 것 같습니다.(있어야 합니다)

열린옷장에서는 이와 같은 취업날개를 통한 온라인 대여 건수가 집계되고 있습니다.

**Comment by aanoaa** [comment]
취업날개 통계에서 온라인 대여가 대여이력은 검색이 되지만 통계에는 누락되고 있습니다.
@10001if 님이 취업날개쪽에 연락해보신다고 합니다.

**Comment by 10001if** [comment]
메일 답변을 받았습니다.

8월까지는 저희 시스템 통계 내 택배건이 집계가 안되서 '택배추가건:00건'처럼 추가건으로 표시하도록 해드린겁니다.
9월부터는 택배건이 집계가 포함되서 위처럼 별도 추가건으로 표시를 해드리지 않은겁니다.
 
표현방식만 다른 것일뿐 시스템 통계는 정상이며 다시한번 정리해 말씀드리자면 아래와 같습니다.
 
- 8월까지는 전체건(택배집계누락)+택배추가건
- 9월부터는 전체건(택배집계포함)

메일 내용에 따르면 온라인(택배)가 표현되지 않을 뿐 집계가 되고 있다고 합니다.
확인 완료 했고 이슈 닫도록 하겠습니다.
