### ISSUE TITLE
취업날*의 경우 배송지가 서울시만 가능하도록 함  

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#187]
취업날*로 인해 따로 변경해야 하는 기능들이 자꾸 발생하고 있네요.

취업날* 이용자가 배송주소를 서울 이외의 지역으로 작성한 경우 온라인 담당자가 전화로 서울시 이외의 지역은 대여가 되지 않음을 안내하는 과정에서 사소한 언쟁이 오고 간다고 하네요. 이 경우 배송지를 서울 이외의 지역으로 설정하는 경우 배송지 입력이 되지 않도록 요청드립니다. 그리고 이와 함께 안내도 추가해주세요.

`취업날* 온라인(택배)대여는 서울 지역으로만 배송이 가능합니다. 배송 받을 주소를 서울시 주소로 입력해주세요.`

**Comment by aanoaa** [comment]
배송지를 먼저 입력하고 이후에 쿠폰을 사용하는 구조입니다.
대여목적과 비슷하게(#178) 배송지가 서울이 아니라면 쿠폰을 사용할 수 없도록 하고,
관련된 안내메세지를 추가하겠습니다.

> 취업날개 온라인(택배)대여는 서울 지역으로만 배송이 가능합니다. 배송 받을 주소를 서울시 주소로 입력해주세요.

**Comment by aanoaa** [comment]
![screenshot-2017-11-23 2017-11-20 19 07 50](https://user-images.githubusercontent.com/170528/33165429-264fb88e-d07a-11e7-8dd9-6fcc4d7f95f6.png)
![screenshot-2017-11-23 2017-11-23 18 11 49](https://user-images.githubusercontent.com/170528/33165430-267b7c1c-d07a-11e7-936b-1320ac3be6ca.png)

**Comment by 10001if** [comment]
@aanoaa 취업날개 때문에 특이한 변수가 많네요. 귀찮아 하지 않고 작업해 주셔서 감사드립니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
