### ISSUE TITLE
서울시 쿠폰 이용자가 쿠폰 입력시 정상적으로 적용이 되지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#189]
![81253ebd4c6987f18d6f6457b8a8dbe2](https://user-images.githubusercontent.com/4696328/33192921-2f3d727c-d108-11e7-8ff4-735c0b43ab09.jpg)

서울시 쿠폰 이용자가 쿠폰을 입력하면 저 창에서 멈춘상태로 진행이 되지 않는다고 하네요. 확인 부탁드립니다. 이 건은 어제 서울시 쿠폰 테스트 하는 과정에서 확인했는데, 동일한 증상으로 진행이 안된다는 대여자가 오늘 있었다고 합니다.

**Comment by aanoaa** [comment]
어제 테스트할때는 됐는데 이용자가 안되는건가요? 양쪽 모두 안된건가요?

**Comment by 10001if** [comment]
어제 테스트 할 때도 되지 않았다고 하네요. 어제 된 건 서울시 이외의 배송지를 입력했을 때 결제가 되지 않고 안내가 된 부분은 확인했다고 하는데요. 이 이슈는 정상적인 취업날개 쿠폰 입력 건(배송지 서울시임)입니다. 옷장지기, 이용자 모두 안된다고 합니다~

**Comment by aanoaa** [comment]
주소지가 없는 것 같습니다.
모든 경우에 해당하는 건지 특정유형에만 해당되는 건지 확인해봐야 합니다.

    [Fri Nov 24 10:25:19 2017] [error] Can't call method "address2" on an undefined value at /path/to/../lib/OpenCloset/Share/Web/Controller/Coupon.pm line 44.

**Comment by aanoaa** [comment]
테스트를 충분히 하지 못해서 발생한 문제입니다.
기본 배송주소 이외의 경우에는 문제가 없지만, 기본 배송 주소를 사용할때에 문제가 발생하고 있습니다.

**Comment by aanoaa** [comment]
수정해서 바로 배포하였습니다.
이제는 문제가 발생하지 않을 거라 믿습니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^

**Comment by 10001if** [comment]
![346b14530faf2dae65c81e81aa25f538](https://user-images.githubusercontent.com/4696328/33203068-2f559bce-d142-11e7-895a-79495ccc02db.jpg)
그림과 같이 대여품목 총액이 안내되어 있지 않은데요. 
총액이 함께 안내되면 이해하기 더 쉬울 것 같다는 의견이 있습니다.
저도 총액이 표시되는 게 더 좋을 것 같네요.
작업 요청드릴게요.

**Comment by 10001if** [comment]
쿠폰 적용은 정상적으로 적용됩니다~

**Comment by aanoaa** [comment]
[대여품목의 총액표시](#193) 에서 진행합니다.
