### ISSUE TITLE
온라인 품목이 다른 경우 대여진행이 되지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#191]
대여희망품목과/ 포장품목이 일치하지 않는 경우 포장 및 대여가 진행되지 않습니다. 

예) 대여희망 품목 : 자켓, 스커트, 구두
     포장 품목 : 자켓, 바지, 구두 

이렇게 희망 품목(대여자가 선택한 품목)과 포장 품목이 하나라도 다른 경우 대여 자체가 진행되지 않는 오류가 발생하였습니다.

오늘 온라인 취소건인 orders/83013/purchase 주문서로 위의 상황을 다시 시도해보았습니다.
1 대여희망 품목 : 자켓,스커트,구두
2 옷장지기가 포장하는 품목 : 자켓. 바지, 블라우스
3 선택한 의류를 대여합니다 버튼 클릭
4 주문품목과 대여품목이 다릅니다. 계속하시겠습니까? 안내창 
5 확인 클릭
6 아무 변화가 없습니다.

-> 대여 진행이 안되고 아무 변화 없이 다시 원래 상태가 되어버립니다.

주문서 그대로 상황을 제가 직접 확인하지 못해 캡쳐 하지 못하고 말로 설명 드립니다. 추가로 궁금한 점 있으면 남겨주세요.

**Comment by pingpongworks** [comment]
제가 확인해보니까 품목이 다른 경우
"주문품목과 대여품목이 다릅니다. 계속하시겠습니까?" 안내창이 뜬 후 
아무 변화없이 다시 원래 상태로 입력창이 뜹니다. 

오프라인 대여 진행할 때와 같이 
"품목이 다릅니다. 계속하시겠습니까?" 확인안내창이 뜬 후
`확인`하면 진행이 되도록 해야 할 듯 합니다. 

여러벌을 대여하여 품목이 많은 경우에는 
처음부터 다시 찍어야하므로 은근히 업무가 번거롭습니다. 

간단한 작업이라면 바로 부탁드립니다.

**Comment by pingpongworks** [comment]
발송 담당자가 불편을 호소하고 있습니다. 
오래된 이슈인데, 작업이 가능한지 확인부탁드립니다. 
작업이 어렵다면 다른 방도를 생각하겠습니다.

**Comment by aanoaa** [comment]
개발환경에서는

"품목이 다릅니다. 계속하시겠습니까?" 후에 확인 버튼 누르면 대여중 상태로 변경됩니다.
혹시나 서버에서 코드가 build 가 안된게 아닐까 해서 다시 build 하였습니다.

제가 테스트용으로 주문서 맨들어서 한번 확인해보겠습니다.

**Comment by aanoaa** [comment]
확인했습니다.
품목이 모자라는 경우에는 무시하고 진행되지만 품목이 다를경우에는 변화없이 화면만 새로 고침 되네요.

**Comment by aanoaa** [comment]
주문서와 의류품목이 다르더라도 staff 이 승인 했다면 배송대기중으로 변경하도록 했습니다.
이제는 되리라고 믿습니다.

**Comment by pingpongworks** [comment]
잘 됩니다~ 감사합니다^^
