### ISSUE TITLE
서울시 온라인 쿠폰 유효기간의 수정

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#194]
서울시에서 오늘 연락이 왔습니다. 쿠폰 사용을 2017년 12월 13일까지로 제한하겠다는 내용인데요. 일자리 포털에서 취업날개 예약을 진행할 때 이에 대한 안내를 실시하고 방문 예약일이 13일까지만 예약이 되도록 하겠다고 합니다. 우리의 경우에는 예약 프로세스가 별도로 진행되고 있기 때문에 서울시 가이드라인에 따라 수정이 필요할 것으로 보여지는데요.

온오프라인 모두 대여일이 13일까지 이용 가능합니다. 온라인은 대여일(착용일 -1일)이 13일까지인 경우만 이용할 수 있어야 합니다. 따라서 착용일이 14일 인 경우까지만 선택이 가능하도록 요청드립니다. 착용일이 15일부터는 이용할 수 없도록 착용일 버튼을 누를 수 없도록 수정 요청드립니다.

오프라인은 https://github.com/opencloset/opencloset/issues/1366#issuecomment-349903624 에서 작업 요청을 드린 상태입니다.

**Comment by aanoaa** [comment]
일자리 포털을 통하지 않고서는 취업날개 쿠폰을 사용해서 온라인 주문을 할 수 없습니다.
일자리 포털에서 서비스를 종료하면 됩니다.

하지만 이미 발급된 쿠폰을 가지고 있고 이를 13일 이후에 사용하려고 할때에 사용할 수 없도록 하는 방법이 필요할 것 같습니다.

- 대여목적이 입사면접이 아닌경우
- 배송주소가 서울이 아닌경우

와 마찬가지로 쿠폰코드를 입력하였을때 13일 이후에는 사용할 수 없다는 적절한 안내메세지가 보여진다면 괜찮을 것 같습니다.

**Comment by aanoaa** [comment]
> 온오프라인 모두 대여일이 13일까지 이용 가능합니다. 온라인은 대여일(착용일 -1일)이 13일까지인 경우만 이용할 수 있어야 합니다. 따라서 착용일이 14일 인 경우까지만 선택이 가능하도록 요청드립니다. 착용일이 15일부터는 이용할 수 없도록 착용일 버튼을 누를 수 없도록 수정 요청드립니다.

쿠폰의 유효기간은 2017년 까지이지만 조기 종료입니다.
쿠폰의 유효성 검사는 오늘을 기준으로 유효기간이 지났는지 판단합니다.
쿠폰의 유효기간을 13일로 변경한다고 해결되는 문제가 아닙니다.

이 경우에는 의류착용일이 14일까지만 쿠폰을 사용할 수 있도록 허용해야 합니다.

**Comment by aanoaa** [comment]
오늘 배포한다고 해도 가장이른 의류착용일이 15일 이라서 쿠폰을 사용할 수 없습니다.
모든 경우에 대해서 쿠폰을 사용할 수 없도록 해도 괜찮습니다.
하지만 올바르게 적용하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 현재까지 온라인 취업날개로 14일 이후 이용하려는 대여자가 없었습니다. 이제 온라인에서도 2017-12-31 까지는 취업날개 이용자가 없겠네요. 감사합니다~!

**Comment by aanoaa** [comment]
`2017년도 취업날개 서비스가 종료되어서 해당 쿠폰은 사용할 수 없습니다.`

제가 임의로 안내메세지를 생각해봤습니다.

**Comment by 10001if** [comment]
@aanoaa 네! 이 정도 안내면 충분합니다~
