### ISSUE TITLE
안양시 쿠폰을 사용했음에도 단벌할인이 되지 않음

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#195]
orders/86478 주문서 입니다.

대여금액 27,000원 배송비 3,000원 하여 30,000원 결제인데
안양시 쿠폰을 사용했기 때문에 단벌할인 쿠폰이 적용되어 3,000원만 결제 되어야 합니다.

하지만 30,000원 결제를 요청하였습니다.

![2017-12-19 3 30 43](https://user-images.githubusercontent.com/4696328/34143836-25452c82-e4d2-11e7-966b-23be9dfbf33d.png)

![2017-12-19 3 30 32](https://user-images.githubusercontent.com/4696328/34143843-2a58fa3c-e4d2-11e7-8a32-cff37bb77ba8.png)

확인 요청드립니다.

**Comment by pingpongworks** [comment]
시즌이 지난 이슈이므로 닫습니다.
