### ISSUE TITLE
추천의류

### ISSUE THREAD

**Issue by yongbin** [opencloset/OpenCloset-Share-Web#2]
![screen shot 2016-05-30 at 4 45 50 pm](https://cloud.githubusercontent.com/assets/52704/15643111/697bca3e-2686-11e6-8116-fd0de507fee9.png)

- 대여서비스 메인화면입니다. 로그인후 이 화면으로 이동합니다.
- 원래 별도의 index 화면을 구성하려했지만 기획단계에서 불필요하다고 생각해서 뺐습니다.
- 대여서비스에 로그인한 사용자는 바로 본인의 치수정보를 기준으로 잘 맞을 의류를 표시해줍니다.
- `XXX` 님을 위한 맞춤 추천
- `치수정보 수정하기` 를 누를경우 회원의 치수정보를 수정할수 있는 별도 화면으로 이동합니다.(#4)
- 키 `XXXcm` 몸무게 `XX`kg 기준( `XX`일전 ) 
  - 현재 `측정일`로 표시되고 있지만 가능하면 timeago 형식으로 표현되면 더 좋겠습니다.
- 추천의류 목록에서 가장 앞은 기존에 대여했던 의류입니다. 화면에서 보면 파란색 라벨이 붙어있습니다. 
- 기존대여의류가 한벌 이상이라면 그 옷이 모두다 앞에 표시됩니다.
- 그 외 나머지 정장은 모두 의류검색을 통한 추천 정장입니다.
- 초기에 3벌만 표시하려고 했지만 전체다 표시하기로 변경했습니다.
- 대여자의 성별에 따라서 화면구성이 달라질 가능성이 있습니다. 현재까지 확정된건 남성뿐입니다. 
- 가슴 `XX` / 허리 `XX` `XX` `XXX` (가슴 99 / 허리 88 블랙 솔리드)
- 의류를 클릭하면 의류상세화면(#3) 으로 이동합니다.

**Comment by aanoaa** [comment]
markup 에 스타일 속성도 너무 많고, 레이아웃 grid 도 없어서 이대로 사용하기 어려울 것 같습니다.
내용만 참고하고 디자인을 최소화하고 진행하는게 더 나아보입니다.

**Comment by aanoaa** [comment]
타이틀이 없습니다.(저는 중요하게 생각합니다)

**Comment by aanoaa** [comment]
90625c299261fe34d006d54b157bd98d0e4e634d 에서 디자인파일을 가지고 왔습니다.
이대로 사용하기는 어려울 것 같고, 본 이슈를 바탕으로 만들어나가겠습니다.

**Comment by aanoaa** [comment]
이건 로그인한 이후에 대한 내용인데, 처음 방문자에 대한 내용이 필요합니다.

**Comment by yongbin** [comment]
> 이건 로그인한 이후에 대한 내용인데, 처음 방문자에 대한 내용이 필요합니다.

현재 로그인 / 회원가입 부분은 기획이 전부다 정리가 안된점도 있고 기존 예약이나 Story 등과 연결되는 이슈가 있어서 시간이 좀 걸릴것 같습니다. 이쪽에서는 그부분은 제외하고 진행하다가 완료되면 적용하는 방식이 되어야 합니다.

> 타이틀이 없습니다.(저는 중요하게 생각합니다)

넵 각 페이지마다 타이틀 고민해보겠습니다.

> markup 에 스타일 속성도 너무 많고, 레이아웃 grid 도 없어서 이대로 사용하기 어려울 것 같습니다.
> 내용만 참고하고 디자인을 최소화하고 진행하는게 더 나아보입니다.

넵 기존 사용했던 화면을 그대로 구현할 필요는 없을것 같습니다. 레이아웃만 참고하고 여기서 다시 구성해야할 것 같습니다. 하지만 구조적으로 다르더라도 보이는 최종 결과물은 지금 보이는것과 최대한 비슷하게 진행하는것은 필요할것 같습니다. 왜냐하면 그렇지 않으면 추후에 별도로 또 디자인작업을 진행해야하기 때문입니다.

**Comment by aanoaa** [comment]
앞으로 어떻게 하겠다보다는
코멘트의 질문에 답을 달아주시기 바랍니다.

예로,

> 타이틀이 없습니다.(저는 중요하게 생각합니다)

이거에 대한 답이 필요합니다.
나아가서 다른 화면들에 대해 구성할때도 타이틀을 고민해서 적으면 좋겠습니다.

타이틀은 *메인 화면* 입니다.

같은 식으로요.

> 이건 로그인한 이후에 대한 내용인데, 처음 방문자에 대한 내용이 필요합니다.

이런건, 처음 방문자에 대한 이슈를 열고 거기에 내용을 채워주는 것이 더 바람직합니다.

**Comment by yongbin** [comment]
넵 알겠습니다

**Comment by aanoaa** [comment]
메인화면에서 사용될 이미지들은 어딘가에 업로드되어야 합니다.
이를 위해서 지난번에 자원봉사자의 사진을 업로드하기 위해서
작업하던 avatar 프로젝트를 완성하도록 하겠습니다.

**Comment by aanoaa** [comment]
avatar 프로젝트는 완성되었고,
https://avatar.theopencloset.net/ 서비스로 운영합니다.

**Comment by aanoaa** [comment]
메인화면이라는 용어는 사용하지 않겠습니다.
메인=? 인지 모르겠고, 적절한 용어로 대체하겠습니다.

메인 대신에 의류추천 으로 하겠습니다.

**Comment by aanoaa** [comment]
로그인한 사용자만 사용할 수 있고, 경로는

    https://share.theopencloset.net/

입니다.

타이틀은 `홍길동님 추천의류 · 열린옷장` 으로 하겠습니다.


로그인하지 않은 사용자는 로그인할 수 있는 form 화면과
첫방문자를 위한 어떤 화면이 필요합니다.

    https://share.theopencloset.net/welcome/    # 혹은 guide
    https://share.theopencloset.net/login/

으로 할까 합니다.

**Comment by aanoaa** [comment]
오프라인대여는 로그인 없이 진행되지만
온라인대여는 회원가입을 해서 로그인해야만 진행할 수 있어야 합니다.
(그렇게 하기로 한걸로..)

이부분이 중요할 것 같습니다.
어떻게 회원가입을 하고, 어떻게 로그인을 할 것인지,
로그인후에 보여지는 첫화면이 추천의류 화면인지 등등

**Comment by aanoaa** [comment]
사용자를 추가할때에 재고관리 서비스의 API 를 이용해야 할까요?
모듈화해서 사용한다면 모를까 따로 만들어야 한다면 가입경로가 두개가
되어버려서 데이터 관리가 힘들고 오류가 발생할 여지도 있습니다.

**Comment by aanoaa** [comment]
#5 에서 서비스소개 화면을 진행합니다.

**Comment by aanoaa** [comment]
치수 측정일을 추적할 수 없습니다.
`user_info` 에 `update_date` 컬럼이 없기 때문입니다.

**Comment by aanoaa** [comment]
초기 버전에서는 대여자가 직접 옷을 고르지 않습니다.
해서 아직은 필요없는 기능입니다.
