### ISSUE TITLE
배송비를 받지 않는 쿠폰 타입을 지원

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#200]
군포시에서 군포시 쿠폰으로 이용하는 모든 대여자들에게 택배비를 전부 무상으로 진행하게 해달라는 요청이 있었습니다.  따라서 결제시에 택배비를 결제받지 않도록 해야 합니다. 현재는 3,000원의 택배비용을 결제해야 주문이 완료되도록 설정이 되어 있습니다. https://github.com/opencloset/OpenCloset-Share-Web/issues/167 이슈와 같은 내용입니다. 현재 택배비 결제를 하지 않아도 되는데 결제가 되어 부득이 하게 현금을 택배 안에 넣어 발송하고 있습니다. 빠른 수정 요청드립니다.

**Comment by aanoaa** [comment]
택배 상자에 3000원 넣어보내면 안되나여?

**Comment by 10001if** [comment]
@aanoaa 안되지는 않습니다. 현재도 그렇게 진행하고 있는데요. 문제는 택배비 무료로 알고 있는 상황에서 결제가 필요하기 때문에 결제 행위에 대한 문의가 발생합니다. 3000원을 넣어 보낸다면, 결제 전에 관련한 안내가 필요할 것 같은데요. 안양시, 군포시는 택배비 결제 후에 의류 발송 시 3,000원을 넣어보내드립니다. 와 같은 이야기가 결제 란에 들어가야 합니다.

**Comment by aanoaa** [comment]
- default (금액)
- suit (단벌)
- rate (비율)

현재 이러한 쿠폰 종류가 있습니다.
단벌이면서 택배비까지 무료인 쿠폰의 종류를 추가하고(suit-free-shipping)
기존에 발급된 군포시 쿠폰의 종류를 이것으로 변경합니다.
온라인에서 쿠폰을 입력했을때에 free-shipping 타입의 쿠폰이라면 배송비를 결제받지 않도록 합니다.

이방법이 괜찮을까요?

**Comment by 10001if** [comment]
택배비를 무료로 하기 위해서는 쿠폰 종류의 추가가 필요 했었네요. 
free-shipping 타입의 쿠폰이라면, 배송비를 결제받지 않도록 하는 방법이 적절할 것 같습니다. 
이 방법으로 요청드릴게요.

**Comment by aanoaa** [comment]
coupon 테이블의 스키마를 변경하는 방법으로 하겠습니다.

    `free_shipping` INT DEFAULT 0 COMMENT 'null and 0 are false, otherwise true'

**Comment by keedi** [comment]
스키마 변경없이 쿠폰 타입 변경으로는 해결이 어렵나요?

**Comment by aanoaa** [comment]
온라인 주문서의 가격 책정방법입니다.

- 대여품목별 대여비
- 배송비 3,000 고정
- 3회 이상 대여했다면 할인
- 추가 연장비용
- 쿠폰 타입별 할인가 적용(3회 이상 대여 중복할인 안됨)

--------------------------

    자켓                10,000
    팬츠                10,000
    배송비                3,000
    단벌 할인쿠폰         -20,000

여기에서 무료배송쿠폰이라면 무료배송 쿠폰

    무료배송쿠폰           -3,000

이 되어야 하고 결제바로 배송대기 상태로 넘어가야 합니다.
다만 무조건 이렇게 되면 아니됩니다.

연장비가 있을 수 있기 때문에 추가 연장을 한 경우라면 연장비를 따로 결제 받아야 합니다.

    4박5일 +1일 연장(+20%) 4,000

쿠폰의 할인가를 적용할때에 sum 이 0 원인 경우에는 할인과 동시에 배송대기 상태로 변경해주고,
sum 이 0 보다 클때에는 지금과 마찬가지로 나머지 금액을 결제후에 진행할 수 있도록 해야 합니다.

**Comment by keedi** [comment]
문득 생각이 났는데요. 쿠폰에 이것을 추가하는 것과 별개로 무료 배송 버튼을 두고 클릭시 무료배송쿠폰이라는 항목이 들어가면 어떨까 생각을 해보았습니다. 대신 담당자는 어떤 쿠폰인지 파악한 뒤 무료배송 버튼을 클릭할지 말지를 판단하는거죠. 하지만 너무 늦게 생각이 났네요. 생각의 정리 및 기록차 남겨놓습니다.

**Comment by aanoaa** [comment]
온라인의 경우 쿠폰사용과 동시에 결제가 완료되는 것이 아니라,
쿠폰을 적용해서 금액을 할인받고 나머지 금액을 결제해야 합니다.

관리자가 무료배송 버튼을 클릭할때까지 대여자가 결제를 기다리는 것은 어려울 것으로 보입니다.

**Comment by keedi** [comment]
아 오프라인 기준으로 생각을 해버렸네요. 온라인이라면 말씀처럼 불가능한 방법이군요.

**Comment by aanoaa** [comment]
이 쿠폰은 통계를 수집하고 있지 않습니다.
정산을 위해서라도 다른 이벤트들과 마찬가지로 사용량을 수집해야 합니다.

**Comment by 10001if** [comment]
해당 쿠폰의 경우 https://github.com/opencloset/opencloset/issues/1412 를 통해 통계 페이지를 요청드린 상태입니다.

**Comment by aanoaa** [comment]
배포하였습니다.
테스트용 쿠폰은 이메일로 전달해드렸습니다.

**Comment by 10001if** [comment]
@aanoaa 테스트 진행해보았습니다. 정상적으로 배송비 결제 없이 결제가 완료됩니다. 감사합니다.

**Comment by 10001if** [comment]
확인 하였습니다. 감사합니다. ^^
