### ISSUE TITLE
6월 13일 선거공휴일로 인한 온라인대여 발송예정일 제외 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#202]
6월 13일 (수) 지방선거로 업무 휴무합니다. 

온라인대여 신청시 6월 13일 발송할 수 없습니다.

발송예정일에서 제외될 수 있도록 요청드립니다. 

이미 들어와있는 주문은 12일에 미리 발송할 예정입니다. 

* 이번처럼 날짜 관련한 요청인 경우에 어떤 방식으로 요청드리는게 업무에 편하신지 잘 모르겠네요. 알려주시면 다음에 요청할 때 참고하겠습니다. @aanoaa

**Comment by aanoaa** [comment]
지금처럼 말씀해주시면 됩니다.
2018-06-13 일을 임시공휴일로 지정하였습니다.
선택이 안되게 되어야 하는게 아닌가 싶지만 그렇지 않습니다.
애초에 이런 경우를 고려해서 제작되었습니다.
변화는 없어보이지만 발송일에 차이가 생깁니다.
13일 하루전에 의류를 받을 수 있게 됩니다.


예로 13일이 의류착용일 일때,

발송(예정)일
2018-06-08

도착(예정)일
2018-06-12

의류착용일
2018-06-13

반납택배발송일
2018-06-14

-------------------

14일이 의류착용일 일때,

발송(예정)일
2018-06-08

도착(예정)일
2018-06-12

의류착용일
2018-06-14

반납택배발송일
2018-06-15

이렇게 됩니다.

**Comment by pingpongworks** [comment]
확인은 그저께 벌써 했는데, 답변이 늦었네요. 감사합니다~
