### ISSUE TITLE
‘결제를 진행합니다’ 버튼에서 넘어가지않는 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#203]
현재 온라인 결제가 되고 있지 않습니다. 
‘쿠폰을 사용하겠습니다’ 버튼만 정상이고,
‘걀제를 진행합니다’ 버튼은 반응하지 않고 있습니다. 
빠른 복구 부탁드립니다.

**Comment by pingpongworks** [comment]
iamport.payment-1.1.7.js 가 릴리즈되었습니다.

아임포트 javascript SDK 1.1.7 버전이 신규 릴리즈되었습니다. 사용자 인터페이스 개선을 위해 추가된 기능을 활용해보세요. 

릴리즈노트(가이드) : https://docs.iamport.kr/javascript/1.1.7
신규로 추가된 기능은, 

Paypal 결제 시 팝업방식 지원 + 결제 후 콜백함수 동작 지원
본인인증(다날) 종료시 일부 콜백함수 미지원 버그 수정 (레이어 내 X버튼)
이며, 그 외에도
네이버페이(결제형) 신규 버전 업데이트
엑심베이 팝업창 결제방식 전환 (엑심베이 보안가이드 준수)
다날 휴대폰 결제 / 다날 본인인증 동시 사용 시 결제창이 잘못 열리는 버그 수정
Chrome68 보안가이드 준수
등의 기능개선도 포함되어있습니다. 
( 기능개선항목들은 1.1.7버전 뿐 아니라 1.1.6 이하 버전도 패치되어있습니다 )

기존에 RC버전으로 이용하시던 분들은, 정식버전에 관련 기능들이 모두 포함 및 개선되어있으니 릴리즈노트 참고하셔서 모두 정식버전으로 전환해주시면 됩니다.
(Paypal 팝업방식은 콜백함수 지원까지 추가되어있으니 RC버전보다 정식버전이 사용에 용이합니다.)
iamport.payment-1.1.7-rc20180206.js
iamport.payment-1.1.7-rc20180406.js
iamport.payment-1.1.7-rc20180615.js
 
아임포트 CDN을 활용해주세요.

보다 원활한 서비스 제공을 위해 아임포트 javascript SDK는 별도의 CDN에서 운영되고 있습니다.
https://service.iamport.kr/js/iamport.payment-1.1.6.js 와 같이 https://service.iamport.kr 도메인을 통해 아임포트 javascript SDK를 사용하시던 분들은 
https://cdn.iamport.kr/js/iamport.payment-1.1.6.js
과 같이 CDN주소로 변경해주시길 권장합니다. 

특히, 브라우저의 보안정책 변경 및 PG사 연동방식 변경 등의 이슈로 부득이하게 기존에 배포된 버전의 아임포트 javascript SDK를 패치하게 되는 경우들이 아주 간혹 있습니다. 
(ex. Chrome68 보안패치, 엑심베이 팝업창 결제방식 전환 등)

빠른 반응속도를 위해 아임포트 javascript SDK를 배포되는 앱 내에 별도로 저장해 사용하시는 경우에는 이 같은 패치가 반영되지 못하므로, 가급적 CDN을 활용해 아임포트 javascript SDK를 사용하시길 권장합니다. 

 
Deprecated 아임포트 javascript SDK

아임포트 초기(2015~2016년)에 릴리즈된 javascript SDK인 1.1.1버전 혹은 그 이하의 버전은 더이상 패치 등의 업데이트 지원이 이뤄지지 않습니다. 
복수PG등의 기능이 부족한 버전이라 현재 사용 중인 경우는 많지 않은 것으로 파악하고 있습니다만, 아직 적용된 경우가 있다면 상위 버전으로 업데이트를 권장합니다. 

Deprecated 버전은 아래 4가지입니다.
iamport.min.js ( 1.0.0 과 동일한 버전 )
iamport.payment-1.0.0.js
iamport.payment-1.1.0.js
iamport.payment-1.1.1.js

관련해서 문의사항있으시면 언제든지 아임포트 고객센터(1670-5176) 또는 support@iamport.kr 로 연락주세요. 

감사합니다.

**Comment by pingpongworks** [comment]
오늘 오전 9시 16분에 아임포트에서 온 메일입니다. 이번 결제오류와 연관성이 있지않나 해서 공유합니다.

**Comment by aanoaa** [comment]
![screenshot-localhost 5002-2018-08-02-20-53-10](https://user-images.githubusercontent.com/170528/43582110-2cf7327e-9696-11e8-87fc-75ec83472a17.png)

이 화면으로 넘어가지 않는건가요?

**Comment by aanoaa** [comment]
제 PC linux - firefox 에서는 동작하지만 모바일(iPhone - safari) 에서는 동작하지 않습니다.

**Comment by aanoaa** [comment]
> 아임포트 초기(2015~2016년)에 릴리즈된 javascript SDK인 1.1.1버전 혹은 그 이하의 버전은 더이상 패치 등의 업데이트 지원이 이뤄지지 않습니다.

저희가 사용중인 버전은 `iamport.payment-1.1.1.js` 입니다.
이번 아임포트의 변경사항에 영향이 있을 수 있을 것 같습니다.

시기도 맞아떨어지고요.

**Comment by aanoaa** [comment]
a605e48607e016748bec9fc2b01d0fe0567435a8 에서 결제 팝업이 뜨지 않는 문제를 해결하였습니다.

**Comment by aanoaa** [comment]
@pingpongworks  휴대폰에서 동작하는 것을 확인하였습니다.
적용했으니 오늘이나 익일 테스트해 보시고 문제가 없으면 닫아주세요.

**Comment by pingpongworks** [comment]
웹에서나 모바일에서도 모두 정상 결제됨을 확인했습니다. 감사합니다~
