### ISSUE TITLE
품목 추가시 대여료 계산 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#204]
![image](https://user-images.githubusercontent.com/17288038/43831156-230022b0-9b3e-11e8-8376-6bbf5cc553ae.png)
각 품목당 하나씩 기본품목만 선택했을 때는 문제가 없습니다

![image](https://user-images.githubusercontent.com/17288038/43831206-5655d33a-9b3e-11e8-878c-5f62cf071903.png)
품목을 추가할 경우, 연장비/ 3회이상 대여 할인 등이 전혀 적용되지 않고 품목 기본단가로만 금액이 추가됩니다. 

품목 추가시에도 할인 또는 기간이 적용되어 계산되도록 수정 부탁드립니다.

**Comment by aanoaa** [comment]
할인되는 조건이 있었던 것 같은데 확인해보겠습니다.
기억으로는 자켓+팬츠+셔츠 이상 대여했을때 적용했던 것 같습니다.

**Comment by pingpongworks** [comment]
**1. 3회 이상 대여자 할인정책**

대여 횟수를 감안할 때 각각의 대여시 무엇을 빌렸는지를 고려하지 않습니다. 실제 대여를 수행했으면 대여 1회라고 판단합니다. 다만 쿠폰을 사용해 대여한 경우는 대여 횟수에 포함하지 않습니다. 쿠폰을 사용할때 추가 비용을 지불했다 하더라도 대여 횟수에 포함하지 않습니다.
상기 두 항목을 고려해서 3회 대여하러 오는 경우 부터 비용 할인 대상입니다.

재킷+바지+ α 인 경우 재킷1벌, 바지1벌을 제외한 나머지 종류별로 1개 항목씩은 비용을 받지 않음. 즉 2만원.
재킷+치마+ α인 경우 재킷1벌, 치마1벌을 제외한 나머지 종류별로 1개 항목씩은 비용을 받지 않음. 즉 2만원.
재킷+바지만 대여할 경우 30% 할인. 즉 1.4만원
재킷+치마만 대여할 경우 30% 할인. 즉 1.4만원
자켓1+바지1 대여일 경우, 셔츠1, 타이1, 구두1, 벨트1 만 무료 (코트, 조끼, 원피스 등 다른 품목은 적용제외)
자켓2+바지2 대여일 경우, 셔츠2, 타이2, 구두2, 벨트2 만 무료 (코트, 조끼, 원피스 등 다른 품목은 적용제외)
자켓1+스커트1 대여일 경우, (셔츠1 또는 블라우스1), 타이1, 구두1 만 무료 (코트, 조끼, 원피스 등 다른 품목은 적용제외)
자켓2+스커트2 대여일 경우, (셔츠2 또는 블라우스2), 타이2, 구두2 만 무료 (코트, 조끼, 원피스 등 다른 품목은 적용제외)
이외의 경우 추가되는 항목은 30% 할인을 적용
자켓3벌 이상이거나, 바지3벌 이상이거나, 스커트3벌 이상이거나, 기본 대여일 기준 대여금액이 10만원 이상이면 단체 대여로 간주하고 무상 대여 품목 또는 30% 할인을 적용하지 않음

헷갈릴 수 있으니 쿠폰 사용 제외 3회째 방문을 기준으로 예를 들면 다음과 같습니다.

재킷1벌, 바지1벌 -> 14,000원
재킷1벌, 바지1벌, 타이1벌, 신발1켤레, 셔츠1벌 -> 20,000원
재킷1벌, 바지1벌, 타이1벌, 신발1켤레, 셔츠2벌 -> 20,000원 + 3500원(셔츠1벌 30%)
재킷1벌, 치마1벌 -> 14,000만원
치마1벌, 블라우스1벌 -> 10,500원 ( 10000 + 5000 값에 30% )
재킷2벌, 바지2벌 -> 28,000만원 ( 40,000원의 30% )
재킷2벌, 치마1벌, 바지1벌, 셔츠2벌, 구두2벌 -> 20,000원 + 20,000원
재킷2벌, 치마1벌, 바지1벌, 셔츠2벌, 구두2벌, 타이 3벌 -> 20,000원 + 20,000원 + 1400원 (타이1벌의 30%)

**3회이상 대여자 할인조건은 위와 같습니다. 아마도, 품목을 추가하는 경우의 할인기능이 없는 것 같습니다.** 



**2. 여러 품목 선택시 헷갈려서 계산이 어려움**
![image](https://user-images.githubusercontent.com/17288038/44717905-55ed6500-aaf9-11e8-92ae-492745a29c76.png)
현재는 여러 품목을 선택할 경우, 몇 개를 선택했는지도 구분하기가 어렵습니다. 그래서 이번 기회에 수량과 가격을 좀더 보기편하게 개선하는 작업을 동시에 하면 어떨까 생각이 듭니다. 수량 선택 수정 방향은 별도의 이슈로 올리겠습니다.

**Comment by aanoaa** [comment]
to @keedi

```perl
    my $discount = $order->sale_multi_times_rental( \@details );
    if (my $price = $discount->{before} - $discount->{after}) {
        $self->log->info("[discount] 기존대여료: " . $discount->{before});
        $self->log->info("[discount] 할인금액: " . $price);
        for my $od (@details) {
            $self->log->info(
                sprintf(
                    "[discount] %s: %d %s",
                    $od->{clothes_category},
                    $od->{final_price},
                    $od->{desc} || '',
                )
            );
        }
    }
```

대여품목을 바꿔가면서 테스트했고 이런 방식으로 로그를 남겼습니다.
`sale_multi_times_rental` 을 통한 계산입니다.

    -- 자켓 + 팬츠
    [Sun Sep 30 15:14:47 2018] [info] [discount] 기존대여료: 20000
    [Sun Sep 30 15:14:47 2018] [info] [discount] 할인금액: 6000
    [Sun Sep 30 15:14:47 2018] [info] [discount] jacket: 7000 3회 이상 방문(30% 할인)
    [Sun Sep 30 15:14:47 2018] [info] [discount] pants: 7000 3회 이상 방문(30% 할인)
    
    -- 자켓 + 팬츠 + 셔츠
    [Sun Sep 30 15:15:41 2018] [info] [discount] 기존대여료: 15000
    [Sun Sep 30 15:15:41 2018] [info] [discount] 할인금액: 5000
    [Sun Sep 30 15:15:41 2018] [info] [discount] jacket: 5000
    [Sun Sep 30 15:15:41 2018] [info] [discount] pants: 5000
    [Sun Sep 30 15:15:41 2018] [info] [discount] shirt: 0 3회 이상 방문(셋트 이외 무료)
    
    -- 자켓 + 팬츠 + 셔츠 + 구두
    [Sun Sep 30 15:16:44 2018] [info] [discount] 기존대여료: 20000
    [Sun Sep 30 15:16:44 2018] [info] [discount] 할인금액: 10000
    [Sun Sep 30 15:16:44 2018] [info] [discount] jacket: 5000
    [Sun Sep 30 15:16:44 2018] [info] [discount] pants: 5000
    [Sun Sep 30 15:16:44 2018] [info] [discount] shirt: 0 3회 이상 방문(셋트 이외 무료)
    [Sun Sep 30 15:16:44 2018] [info] [discount] shoes: 0 3회 이상 방문(셋트 이외 무료)
    
    -- 자켓 + 팬츠 + 셔츠 + 구두 + 타이 (타이에 대한 로그가 없음?)
    [Sun Sep 30 15:16:44 2018] [info] [discount] 기존대여료: 20000
    [Sun Sep 30 15:16:44 2018] [info] [discount] 할인금액: 10000
    [Sun Sep 30 15:16:44 2018] [info] [discount] jacket: 5000
    [Sun Sep 30 15:16:44 2018] [info] [discount] pants: 5000
    [Sun Sep 30 15:16:44 2018] [info] [discount] shirt: 0 3회 이상 방문(셋트 이외 무료)
    [Sun Sep 30 15:16:44 2018] [info] [discount] shoes: 0 3회 이상 방문(셋트 이외 무료)
    
    -- 자켓 + 팬츠 + 셔츠 + 구두 + 타이 + 벨트
    [Sun Sep 30 15:24:09 2018] [info] [discount] 기존대여료: 12000
    [Sun Sep 30 15:24:09 2018] [info] [discount] 할인금액: 8000
    [Sun Sep 30 15:24:09 2018] [info] [discount] jacket: 2000
    [Sun Sep 30 15:24:09 2018] [info] [discount] pants: 2000
    [Sun Sep 30 15:24:09 2018] [info] [discount] shirt: 0 3회 이상 방문(셋트 이외 무료)
    [Sun Sep 30 15:24:09 2018] [info] [discount] shoes: 0 3회 이상 방문(셋트 이외 무료)
    [Sun Sep 30 15:24:09 2018] [info] [discount] tie: 0
    [Sun Sep 30 15:24:09 2018] [info] [discount] belt: 0 3회 이상 방문(셋트 이외 무료)

3회 이상 대여자가 `자켓 + 팬츠 + 셔츠` 를 대여했을때에,

    jacket: 5000
    pants: 5000
    shirt: 0 3회 이상 방문(셋트 이외 무료)

인데, 

    jacket: 10000
    pants: 10000
    shirt: 0 3회 이상 방문(셋트 이외 무료)

이 맞지 않을까요?

**Comment by aanoaa** [comment]
제 테스트에서는 실제 주문서(`$order`) 정보가 전달되는데, @keedi 님의 sample 코드에서는
예측 값 만이 사용되고 있습니다.

    $order->sale_multi_times_rental( \@details );

실제 코드에서는 `$order` 의 영향을 받는게 아닐까 합니다.

**Comment by aanoaa** [comment]
`sale_multi_times_rental` 에서는 `$order` 를 사용하는 것은 쿠폰없이 몇번째 대여인지를 계산하는 곳 말고는 없습니다.
제가 테스트를 잘못한 것 같습니다.

**Comment by aanoaa** [comment]
같은 코드로 테스트했는데 맥부기와 리눅스에서의 결과가 다릅니다.
뭐야..지금은 맞는 것 같습니다.

**Comment by aanoaa** [comment]
3박4일 기본 대여일 이외에 추가 연장일이 있다면,
다시 책정된 대여료를 기준으로 연장비가 계산되어야 합니다.

**Comment by pingpongworks** [comment]
확인했습니다. 품목추가시에도 계산이 맞습니다. 감사합니다~

**Comment by pingpongworks** [comment]
**오류케이스1>**
<img width="886" alt="11" src="https://user-images.githubusercontent.com/17288038/46589410-35df9700-cae4-11e8-8387-c0ac845e7ee5.PNG">

타이 추가시에 계산 오류가 발견되어 이슈 다시 열었습니다. 
위의 경우, 수트 한벌 대여자이기 때문에 타이 1개는 0원이 맞지만
타이를 1개 더 추가했을 때는 2,000원이 추가되어야 하는데
0원으로 계산되고 있습니다. 


**오류케이스2>**
![image](https://user-images.githubusercontent.com/17288038/46589470-f6fe1100-cae4-11e8-8c29-dabcf8fae723.png)

3회 이상 대여자인 경우에는 역시 타이 1개는 0원이 맞지만
타이를 1개 더 추가했을 때는 1,400원이 추가가 되어야 하는데 
전체 가격에서 600원이 할인되고 있습니다. 


타이 가격의 30% 할인이 전체대여비에서 할인되는 것으로 잘못 적용된 듯 합니다. 
오류 수정 부탁드립니다.

**Comment by aanoaa** [comment]
넥타이 가격에 대해 추적하던 이슈가 있었는데, 못찾겠습니다.
기록차 남깁니다.

타이의 가격이 2000 원이 아니라 0 원인게 문제인 것 같습니다.
이게 상황에 따라 다르게 고려되어야 하는데 그러지 못하고 있습니다.

3회이상 대여 할인금액은 올바르게 계산되고 있습니다.

**Comment by keedi** [comment]
https://github.com/opencloset/opencloset/issues/790#issuecomment-236512262
https://github.com/opencloset/opencloset/issues/790#issuecomment-238156279

예전 이슈에서 타이 관련 이야기가 있었었는데요... 위에 추출했던 코드도 그렇고 병합되었던 당시 코드도 그렇지만 타이 값을 0원에서 조정하는 코드가 있습니다. 의류 품목 중 타이 한정으로 예외처리해서 셋트 무료인 경우를 제외한 타이의 경우 2,000원에서 30% 할인이 되도록 처리했었습니다.
