### ISSUE TITLE
기간 연장시 선택항목 표현 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#205]
![image](https://user-images.githubusercontent.com/17288038/43831447-1eb4bae4-9b3f-11e8-9542-e7e27cd7c336.png)

대여기간을 연장하는 경우 현재는 다음과 같은 항목을 선택하도록 되어 있습니다.

>3박4일
>4박5일+1일 연장 (20%)
>5박6일+2일 연장 (40%)
>6박7일+3일 연장 (60%)
>7박8일+4일 연장 (80%)
>8박9일+5일 연장 (100%)
>9박10일+6일 연장 (120%)

=> 이는 잘못된 표현입니다. 다음과 같이 수정되어야 합니다.

>3박4일
>4박5일 = 3박4일+1일 연장 (20%)
>5박6일 = 3박4일+2일 연장 (40%)
>6박7일 = 3박4일+3일 연장 (60%)
>7박8일 = 3박4일+4일 연장 (80%)
>8박9일 = 3박4일+5일 연장 (100%)
>9박10일 = 3박4일+6일 연장 (120%)

**Comment by aanoaa** [comment]
적용하였습니다.

**Comment by pingpongworks** [comment]
확인했어요~ 감사합니다^^

**Comment by aanoaa** [comment]
반영하였습니다.

**Comment by pingpongworks** [comment]
확인했어요, 감사합니다~
