### ISSUE TITLE
2018 추석 연휴 동안 온라인 대여 신청을 할 수 없게 함

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#206]
택배 발송이 가능한 날짜를 고려하여 추석연휴 동안 
9월 23일부터 10월 4일까지 의류 착용일인 경우에는 배송을 할 수 없습니다. 
따라서 아래와 같이 요청드립니다.

2018-09-23 ~ 2018-10-04의 의류 착용일을 누를 수 없게 하여 
아예 지정이 되지 않게 수정을 요청드립니다.

**Comment by pingpongworks** [comment]
벌써부터 9월 22일 이후 착용하려는 대여자의 신청이 들어오고 있어 우선적인 작업 부탁드립니다. @aanoaa

**Comment by aanoaa** [comment]
#163 과 같은 이슈입니다.

**Comment by aanoaa** [comment]
aa0f4d31183fb6995122d33918cb41ae3336a41d 에서 해결되었습니다.
배포해서 적용까지 하였습니다.

**Comment by aanoaa** [comment]
새로운 배포는 건너띄고 `develop` 브랜치에만 적용하였습니다.
바뀐 내용은 서버에 직접 반영하였습니다.

이 변경은 다음 배포에 포함될 것 입니다.
