### ISSUE TITLE
가상계좌 입금기한 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#212]
어제 결제 관련해서 발생한 오류가 있었습니다. 오류의 개요는 이렇습니다. 

10월 27일에 온라인 신청을 하려던 `orders/119793` 주문자가 
가상계좌 결제가 원활히 되지 않아서 못하고 있었습니다. 
(주소도 검색이 되지않아서 한참 애를 먹었다고 합니다)
발송일이 10월 29일 (월)인 주문이라 
월요일 오후 1시경에 가상계좌 입금을 다시 해보니 입금이 되고 주문이 완료되었습니다. 
스태프는 오전에 당일 발송 작업을 마쳤는데,  
오후 4시 경에 당일 주문건이 들어와있는 것을 발견하고 급하게 발송하기는 했습니다. 

원래 가상게좌 결제는 주문일 다음날 오전 9시 30분까지만 가능한데, 
orders/119793 대여자의 경우는 입금기한이 11월 6일로 되어 있었습니다. 

입금기한이 말도 안되게 긴 가상계좌가 생성된 것에 대해서 아임포트쪽에 문의하여 받은 답변입니다. 

    안녕하세요, 아임포트 고객지원팀입니다.

    문의하신 가상계좌 입금기한 관련 안내 드립니다.

    해당 거래 확인시 모바일에서 진행된 거래로 확인되었는데요,

    열린옷장의 거래내역을 확인해보면, 
    - PC에서 진행되는 가상계좌 건은 전달주신대로 가상계좌 발급 후 입금기한이 익일 오전 9시30분까지로 발행되고 있으나,

    - 모바일에서 진행되는 가상계좌 거래의 경우 해당 이슈가 발생되는 것으로 확인되었습니다.
     모바일에서 vbank_due 파라메터를 지정할 때 "문자열"로 파라메터를 전달해야 하는데 "숫자"로 파라메터 전달하고 있는 것이 아닌지 체크를 부탁 드립니다.

    원래 vbank_due의 스펙이 "문자열"인데, "숫자"로 전달되는 경우에도 대응할 수 있도록 보완하도록 하겠습니다.

모바일에서 vbank_due 파라메터를 숫자로 전달하고 있는지 체크를 바란다는 내용입니다. 체크 부탁드립니다~

**Comment by aanoaa** [comment]
vbank_due 데이터는 `201810300900` 형식인데 이걸 딱히 포맷팅하는 것에 대해 신경쓰지 않았습니다.
문자열로 전달하도록 하겠습니다.

**Comment by aanoaa** [comment]
이제야 발견된 것이 놀랍습니다.
