### ISSUE TITLE
3회 할인 대상자가 기간연장시 대여료 계산 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#214]
![image](https://user-images.githubusercontent.com/17288038/49266881-39b3e800-f49b-11e8-9cdd-348dda0a0d66.png)

위 대여자의 경우, 3회 이상 할인 대상자이므로 
기본 대여비 20,000원 + 5일 연장비 20,000원 (4,000원 x 5) + 택배비 3,000원 = 43,000원이 맞는 계산입니다. 

현재는 연장비를 계산할 때 3회 이상 할인을 고려하지 않고 계산되고 있습니다.  
오류 수정 부탁드립니다.

**Comment by aanoaa** [comment]
복잡한 할인 조건에 대해 검토해보도록 하겠습니다.
연장비는 할인가격이 아닌 정상가격으로 계산하는 것 같습니다.
이게 복잡한 계산식이 있는데 거기를 만족하는 것인지 아니면 소령님 말씀대로 계산되는 것이 맞는 것인지,
검토가 필요한 것 같습니다.

**Comment by aanoaa** [comment]
주문서 번호를 적어주시지 않아서 확인이 어렵습니다.

할인금액을 기준으로 연장비를 계산하지 않고, 할인 전 금액으로 연장비를 계산합니다.
이슈를 찾아봐야 하지만 제 기억으론 그러합니다.

**Comment by pingpongworks** [comment]
주문서는 따로 없습니다. 
담당자가 3회 이상 대여자가 기간 연장을 할 경우 계산오류가 있다고 해서 대여과정을 테스트하면서 캡처한 화면입니다. 
지금 다시 테스트 해봐도 여전히 같은 오류가 나타나고 있습니다.

<img width="949" alt="스크린샷 2019-06-08 오후 7 07 24" src="https://user-images.githubusercontent.com/17288038/59145578-cb8b4780-8a20-11e9-9269-cb46ac843f43.png">

**Comment by pingpongworks** [comment]
>할인금액을 기준으로 연장비를 계산하지 않고, 할인 전 금액으로 연장비를 계산합니다.

그렇지 않습니다. 3회 이상 할인 대상자인 경우, 할인 후 금액을 연장비를 계산합니다. 
그래서 오프라인 대여의 경우는 같은 조건으로 연장했을 때 40,000원이 나옵니다. 

<img width="560" alt="스크린샷 2019-06-08 오후 7 29 48" src="https://user-images.githubusercontent.com/17288038/59145821-09d63600-8a24-11e9-92e8-a33c1746e82a.png">

`orders/141911`
테스트로 방문대여한 주문서니까 확인해보시면 됩니다.

**Comment by aanoaa** [comment]
소령님 말씀이 맞습니다.
할인된 금액에서 연장료를 계산합니다.

기존 대여료에서 할인금액을 제외하고 연장일 마다 20% 씩 더합니다.

`30,000` 에서 `10,000` 할인 되었으니 대여료는 `20,000`
5일 연장이니 `20,000 x 0.2 x 5`

대여료(`20,000`) + 연장료(`20,000`) + 배송비(`3,000`) 이라서 `43,000` 이 나와야 합니다.

---

    [Sat Jun  8 21:05:30 2019] [info] [discount] 기존대여료: 30000
    [Sat Jun  8 21:05:30 2019] [info] [discount] 할인금액: 10000
    [Sat Jun  8 21:05:30 2019] [info] [discount] jacket: 10000
    [Sat Jun  8 21:05:30 2019] [info] [discount] shirt: 0 3회 이상 방문(셋트 이외 무료)
    [Sat Jun  8 21:05:30 2019] [info] [discount] shoes: 0 3회 이상 방문(셋트 이외 무료)
    [Sat Jun  8 21:05:30 2019] [info] [discount] skirt: 10000

<https://github.com/opencloset/OpenCloset-Share-Web/blob/develop/lib/OpenCloset/Share/Web/Controller/Order.pm#L182>

application 의 버그가 맞습니다.
대여비에서 할인금액을 제외해야 하는데, 더해주고 있습니다.
5일 연장료가 `20,000 x 0.2 x 5` 이 아닌 `40,000 x 0.2 x 5` 가 되었습니다.
