### ISSUE TITLE
서울시 쿠폰(seoul-2018-1)의 온라인 주문을 마감함

### ISSUE THREAD

**Issue by keedi** [opencloset/OpenCloset-Share-Web#215]
https://github.com/opencloset/opencloset/issues/1511

> @pingpongworks:
> 2018년 마감시한에 대해 담당부서에서 **12월 20일 경으로 예상**할 뿐 아직 명확한 날짜를 결정하지 못하고 있습니다. 마감방법에 대해서도 마감날짜를 명확히 하여 이후로 아예 이용을 못 하게 하는 방법과 일단 12월 31일까지 예약이 가능하여 이용한 후 이월하여 내년 1월에 정산하는 방법 두 가지 중 선택을 고려하고 있습니다. 며칠 내에 마감시한과 정산방법을 결정한다고 하니 **일단은 13일 이후로 예약이 가능하도록 마감시한을 변경**해야 할 듯 합니다.
> 
> 2017년의 경우에는 예산이 완전 소진되었기 때문에 급하게 12월 13일에 마감을 했지만(opencloset/opencloset#1366) 올해는 추가 예산을 편성한 덕분에 담당부서에서 여유있게 마감하여 최대한 많이 이용할 수 있도록 배려하고자 합니다. 그런데 그렇다고 지금부터 12월 31일까지 완전히 열어놓으면 나중에 뒷감당이 불안합니다.
> 
> 20일 경이라고 이야기하고 있는 것으로 보아, 일단은 12월 19일 이후로 방문예약이 안 되도록 부탁드립니다. **온라인 이용자는 배송일이 12월 19일 (착용일은 12월 20일) 이후로 쿠폰 주문이 안되도록 부탁드립니다.**

**Comment by pingpongworks** [comment]
마감일 변경으로 요청사항도 변경합니다. 

**착용일이 12월 26일**까지만 선택 가능하도록 부탁드립니다.

**Comment by aanoaa** [comment]
> 착용일이 12월 26일까지만 선택 가능하도록 부탁드립니다.

그럴 수 없습니다.
의류착용일을 선택할때에는 어떤 방식으로 결제할지 모르기 때문입니다.

온라인의 경우에는 최종결제할때에 쿠폰을 입력하는 방식입니다.

오프라인은 현장에서 방문하는 날이 결제하는 날이지만,
온라인은 결제먼저 하고 지정일에 의류를 대여합니다.

27일 마감이라면 27일까지 사용할 수 있도록 쿠폰에 기간을 정해두면 됩니다.
기간이 만료된 쿠폰으로는 결제를 할 수 없습니다.

온라인에서는 +1m 까지는 의류착용일을 선택할 수 있기 때문에, `2019-01-15` 일 대여가 된다고 하더라도
`2018-12-27` 일에 쿠폰을 사용할 수 있습니다.

**Comment by aanoaa** [comment]
쿠폰의 생명주기는 지급/예약/사용 혹은 지급/만료 입니다.

    provided -> reserved -> used
    provided -> expired

예약된 쿠폰은 모두 사용할 수 있습니다.
이 쿠폰이 만료된 쿠폰인지 확인하는 시점은

-   오프라인: 예약할때
-   온라인: 결제할때

입니다.

**Comment by aanoaa** [comment]
지금 시스템에서는 대여일 기준으로 마감시간을 정할 수 없습니다.
예약일기준으로 마감시간을 정해야 합니다.

모든 쿠폰이 마찬가지 입니다.

**Comment by pingpongworks** [comment]
온라인은 12월 16일 (일) 까지만 쿠폰결제가능하게 부탁드립니다. 
그래야 시에서 제한한 23일 전에 반납까지 마무리가 될 거 같아서 조금 이르게 마감하려고 합니다.

**Comment by pingpongworks** [comment]
요청이 이행된 사안이므로 이슈 닫을게요~
