### ISSUE TITLE
다시 대여하기

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#22]
반납된 주문서에 대해서 편리하게 다시 대여할 수 있도록 하면 좋지 않을까 합니다.

**Comment by aanoaa** [comment]
다시대여하기 는 빌렸던 옷을 다시 대여한다는 의미가 있지만, 그렇게 하기 어렵습니다.
가능하다면 같은 옷을 보내주지만, 대여가능하지 않다면 비슷한 옷을 보내줄 수 밖에 없습니다.

이와 관련한 설명이 필요할 것 같고, 의류착용일과 배송주소를 입력받으면 될 것 같습니다.

**Comment by aanoaa** [comment]
그 와중에 몇개만 골라서 할 수 있음 좋겠음

**Comment by 10001if** [comment]
@aanoaa 설명에 관한 내용은 다시 입력하도록 하겠습니다.

**Comment by aanoaa** [comment]
주문서 작성 시점에 지난 대여기록을 연결해서 선택할 수 있도록 하면 좋을 것 같습니다.
라는 의견이 있습니다.

**Comment by aanoaa** [comment]
지난 대여기록의 의류가 의류선택할때에 강조되어서 가장 앞에 보여지도록 하는 의견도 있습니다.

**Comment by 10001if** [comment]
당장 필요한 기능은 아닌 것 같습니다. 마일스톤 수정하도록 하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 제가 잘 이해를 못했던 것 같은데.. 기존에 오프라인에서 대여한 기록이 있으면 이게 보여지는 건가요?

**Comment by aanoaa** [comment]
배송문의입력하는 곳에 지난 대여기록을 보여주고,
거기에서 선택하도록 하는 것이 어떨까 합니다.

대여품목은 바뀔 수 있어서 그대로 다시 대여하기는 불편함이 있습니다.

- 다시 주문서 작성
- 의류선택과정을 지나서
- 주소입력하고
- 대여했던 의류중에 선택할 수 있도록(옵션)

**Comment by aanoaa** [comment]
새로운 아이디어 입니다.

- 대여품목 선택 과정에서 의류품목과 상관없이 지난의류 대여기록을 보여주고 선택할 수 있도록 합니다.
  - 지난번에 구두, 타이만 빌렸고 이번에 자켓, 팬츠, 타이를 빌린다면 타이에 대해 재대여 한다고 볼 수 있는거죠.
- 만약 선택했다면 의류추천과정을 skip.
- 지난 의류대여기록을 다시 선택할 수 있게 할 것인가는 고민해봐야..

**Comment by aanoaa** [comment]
`OpenCloset::Plugin::Helpers::recent_orders` 를 가지고 최근 주문서들을 조회하는데,

    recent_orders( $order, $limit? )

입니다.
사용자의 주문서를 조회하기 위해 arg로 주문서를 받습니다.
해당 주문서를 제외하기 위한 조건이기는 하나, 사용자의 최근주문서를 조회하는 것이기 때문에,

    recent_orders( $user, $limit? )

이 되어야 하지 않나 싶습니다.
하지만 하위호환성을 위해서 

    recent_orders( $order_or_$user, $limit? )

로 변경하는게 좋을 것 같습니다.

**Comment by aanoaa** [comment]
[OpenCloset-Plugin-Helpers-v0.0.16.tar.gz](https://cpan.theopencloset.net/YONGBIN.YU@GMAIL.COM/OpenCloset-Plugin-Helpers-v0.0.16.tar.gz) 배포하였습니다.

    recent_orders($user, $limit?)

으로도 사용할 수 있습니다.

**Comment by 10001if** [comment]
작업 하시는 것 보았는데, 좋은 접근 인 것 같습니다. 그런데 정확히는 이해하지 못했습니다. 나중에 설명 한번 부탁드릴게요~
