### ISSUE TITLE
GA 적용

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#221]
어느 시점에 유저가 이탈했는지를 알아보기 위해 데이터를 쌓아야 합니다.
예상하기에는 신체치수 입력일 것 같지만..

**Comment by aanoaa** [comment]
이것을 적용하려면 열린옷장의 Google 계정(개인계정 아닙니다)으로 https://marketingplatform.google.com/about/analytics/ 에서 코드를 발급받아야 합니다.

하고 나시면 해당 코드를 알려주세요. @pingpongworks

**Comment by pingpongworks** [comment]
행아웃으로 열린옷장 구글계정 로그인방법 전달했습니다.

**Comment by pingpongworks** [comment]
GA 적용 언제쯤 가능할지 작업 일정 알려주세요.

**Comment by aanoaa** [comment]
금주 토요일에 작업하겠습니다.

**Comment by aanoaa** [comment]
fca4a5edca678c587b924d6de8a73ab95f59d7bf

어떻게 분석하는지는 주변에 잘 아는분한테 여쭤보겠습니다.
일단은 데이터가 쌓이는지 여부를 담주에 모니터링 하겠습니다.

**Comment by aanoaa** [comment]
사용한 추적코드 입니다.
어차피 노출되는 것이라 공개되어도 상관없습니다.

2015 new opencloset > 온라인대여 > 전체 웹 사이트 데이터

을 사용하였습니다.
설정에서 변경한 것은 site 주소 뿐 입니다. 

`UA-57268220-3`

**Comment by pingpongworks** [comment]
확인했습니다.
