### ISSUE TITLE
온라인대여 사이트의 "반납 1일전 안내" 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#224]
여기저기 수정해야할 게 숨어있네요. 
온라인 대여 사이트에서 착용일 선택할 때 날짜 하단에 있는 안내 삭제 바랍니다. 
**택배로 반납하실 경우 반납일 하루 전에 보내주셔야 합니다**

![택배반납 1일전](https://user-images.githubusercontent.com/17288038/56476206-5a72ed80-64cf-11e9-9088-42b9ba52510c.JPG)

**Comment by pingpongworks** [comment]
![Jandi_20190523_182321](https://user-images.githubusercontent.com/17288038/58242925-a47b1780-7d8a-11e9-9549-74936ccda043.PNG)

택배배송 시 도착하는 문자에도 1일전 발송 내용이 있었습니다. 빨간 줄 부분, 아래 내용으로 수정 요청드립니다. 

    택배는 기간 내에 늦지않게 발송해주세요.

**Comment by aanoaa** [comment]
작업했던 PC 에서 `develop` 브랜치에 push 를 하지 않았습니다.
해당 PC 에서 마무리 하겠습니다.
