### ISSUE TITLE
5/1 근로자의 날 온라인 발송 불가

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#226]
5/1 근로자의날 의류 발송이 불가능합니다. 
발송일에소 제외될 수 있도록 부탁드립니다.

**Comment by aanoaa** [comment]
지금시간을 기준으로 이미 주말과 버퍼기간이 고려되어서 5/2 일까지 의류착용일로 선택할 수 없습니다.
그래도 5/1일을 의류착용일로 선택할 수 없도록 하였습니다.

**Comment by pingpongworks** [comment]
확인했어요. 감사합니다.
