### ISSUE TITLE
단벌 할인 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#229]
<img width="949" alt="스크린샷 2019-06-03 오전 10 40 05" src="https://user-images.githubusercontent.com/17288038/58770808-012ccc80-85ec-11e9-9015-1c11bc163874.png">

`orders/139337`

온라인으로 서울시쿠폰 대여한 경우인데, 
30,000원이 아니라 27,000원 할인이 되었습니다. 
이유가 뭔지 확인 부탁드립니다.

**Comment by aanoaa** [comment]
품목의 합이 `27,000` 입니다.
배송비 `3,000` 은 할인 되지 않습니다.
발송 택배비는 쿠폰타입에서도 지원되지 않는 값 입니다.

**Comment by pingpongworks** [comment]
??? 오류가 아닌데 제가 왜 오류 확인해달락 올렸을까요??? 이 이슈는 무시하셔도 됩니다. 죄송합니다 ㅠㅠ
