### ISSUE TITLE
결제취소 및 환불

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#23]
결제가 완료된후에 주문서의 상태를 환불로 변경해야 할 필요가 있을 수 있습니다.
환불절차는 staff 의 역량껏 하고, 환불이 완료되었다면 해당 주문서의 상태를 환불로 변경해서
주문서를 정리할 필요가 있습니다.

**Comment by aanoaa** [comment]
기존 재고관리의 환불 기능을 활용할 수 있습니다.
기존 시스템에서 기능을 줄이고자 하기 때문에 이 기능도 migration 될 수도 있습니다.

`결제완료` 상태일때는 주문서가 `대여중` 이 아니기 때문에 환불을 할 수 없습니다.

의류를 선택해서 대여중으로 변경한 다음에 환불이 가능합니다.

**Comment by aanoaa** [comment]
주문서정리뿐 아니라 결제금액의 환불 및 취소도 이루어져야 합니다.

**Comment by aanoaa** [comment]
쿠폰을 사용한 주문서도 취소가 가능해야 할까요?

**Comment by aanoaa** [comment]
발송예정일이 지난 주문서는 취소되면 아니되겠습니다.
21일 발송예정이면 20일까지는 취소 가능 그 이외에는 불가

이게 AM 10:00 기준으로 해야 할지 24:00 기준으로 해야할지 모르겠습니다.
일단은 24:00 기준으로 작업하겠습니다.

**Comment by aanoaa** [comment]
#59 이슈가 해결되지 않으면 가상계좌로 결제한 주문서는 취소할 수 없습니다.

**Comment by aanoaa** [comment]
결제완료 상태의 주문서만 취소가 가능해야 합니다.
결제완료 중에서도 발송예정일이 지나지 않은 주문서.

취소절차

- iamport API 를 사용해서 취소
- 주문서의 상태를 취소로 변경
- 취소안내 알림(문자, 이메일등)

**Comment by aanoaa** [comment]
- 가상계좌입금이 아니라면 취소가능
- 쿠폰으로 결제했다면 쿠폰의 상태를 다시 사용가능하도록 변경

을 고려해야 합니다.

**Comment by aanoaa** [comment]
쿠폰은 테스트해봤지만 다른 결제수단으로는 테스트해보지 못했습니다.

**Comment by aanoaa** [comment]
@10001if @yongbin 카드하고 가상계좌를 통해서 테스트 해주세요.
환불이 되는지 말입니다.

**Comment by aanoaa** [comment]
test-share, share 양쪽에 적용하였습니다.

**Comment by yongbin** [comment]
test-share 에서 카드 결제후 취소 실패화면입니다.

![screenshot 2017-02-16 18 11 22](https://cloud.githubusercontent.com/assets/52704/23014705/6479536a-f473-11e6-9d55-d3cc6a63bc0d.png)

**Comment by aanoaa** [comment]
``` perl
my $iamport = Iamport::REST::Client->new( key => $key, secret => $secret );
my $json = $iamport->cancel( { imp_uid => 'imp_525175876130' } );
print "$json\n";
```

스크립트를 만들어서 취소를 시도해 보았습니다.

```
$ perl a.pl 

```

결과가 아무것도 안나옵니다.
에러가 발생했다면, `상태코드: 이유` 가 warn 으로 찍여야 합니다.

**Comment by aanoaa** [comment]
`curl` 로 살펴보았습니다.
에러가 발생했는데, 200 OK 로 응답해서 정상적인 처리로 여겼습니다.

그렇다고 하더라도 script 에서 응답 json 결과를 못받는 것은 이상합니다.

```
> POST /payments/cancel?imp_uid=imp_525175876130 HTTP/1.1
> Host: api.iamport.kr
> User-Agent: curl/7.52.1
> Accept: */*
> Authorization: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
< Date: Thu, 16 Feb 2017 09:24:18 GMT
< Server: Apache/2.4.7 (Ubuntu)
< Content-Length: 207
< Connection: keep-alive
< 
{"code":1,"message":"\ucde8\uc18c\ud560 imp_uid \ub610\ub294 merchant_uid\ub97c \uc9c0\uc815\ud574\uc8fc\uc154\uc57c\ud569\ub2c8\ub2e4. \uc694\uccad imp_uid : , \uc694\uccad merchant_uid : ","response":null}
```

**Comment by aanoaa** [comment]
```
$ ./c.sh 
* Could not resolve host: api.iamport.kr
* Closing connection 0
curl: (6) Could not resolve host: api.iamport.kr
```

도메인에서 문제가 있엇을 수 있습니다.

**Comment by aanoaa** [comment]
서버에서 돌려도 결과는 같습니다.

**Comment by aanoaa** [comment]
왜 script 와 curl 의 결과가 다른지 모르겠습니다.

**Comment by aanoaa** [comment]
``` javascript
var str = "\ucde8\uc18c\ud560 imp_uid \ub610\ub294 merchant_uid\ub97c \uc9c0\uc815\ud574\uc8fc\uc154\uc57c\ud569\ub2c8\ub2e4. \uc694\uccad imp_uid : , \uc694\uccad merchant_uid : ";

function unicodeToChar(text) {
   return text.replace(/\\u[\dA-F]{4}/gi, 
          function (match) {
               return String.fromCharCode(parseInt(match.replace(/\\u/g, ''), 16));
          });
}

console.log(unicodeToChar(str));

// 취소할 imp_uid 또는 merchant_uid를 지정해주셔야합니다. 요청 imp_uid : , 요청 merchant_uid : 
```

**Comment by aanoaa** [comment]
```
$ curl -v -X POST --header "Authorization: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -d "imp_uid=imp_525175876130" https://api.iamport.kr/payments/cancel
```

이렇게 요청해서 정상응답을 받았습니다.

`Iamport::REST::Client` 에서 token 을 저장해놓고 사용하는데, 매번 요청해서 처리할 필요가 있습니다.
token 요청에 대한 결과가 바뀌네요.

**Comment by aanoaa** [comment]
`imp_525175876130` 는 제가 curl 로 취소하였습니다.
iamport admin 에서도 취소된 것을 확인하였습니다.
(하지만 우리 시스템에서는 아직 취소된 것을 모르니 취소버튼을 눌렀을때 제대로 동작하지 않을 것입니다)

매 요청마다 token 을 요청하도록 바꾸었습니다.
다시 한번 테스트부탁드립니다.

**Comment by aanoaa** [comment]
5b0052c2d96cf02f4cedcc92c88168b88dd7a66f

**Comment by aanoaa** [comment]
생각해보니,
이제 환불이 된다고 했으니 제가 테스트 못할 이유가 없습니다

**Comment by aanoaa** [comment]
iamport-rest-client 모듈에서 취소 조건을 체크할때에 실수가 있었습니다.

``` diff
-    return unless ( !$opts->{imp_uid} && !$opts->{merchant_uid} );
+    return if ( !$opts->{imp_uid} && !$opts->{merchant_uid} );
```

수정해서 반영하도록 하겠습니다.

**Comment by aanoaa** [comment]
가상계좌로 결제한 주문서를 취소할 수 있습니다.
아직 환불계좌로 입금되지는 않았지만 iamport admin 에서 취소되었음을 확인 하였습니다.

@yongbin 카드결제 취소를 확인해주세요.

**Comment by yongbin** [comment]
신용카드를 이용한 결제 취소 2번 진행했는데 두번 모두 아임포트와 카드사 문자통지를 통해서 정상적으로 잘 처리된것을 확인했습니다.

추가적으로 진행하면서 궁금한거 두가지 문의드립니다.

1. 신용카드 결제 취소가 되었을때 특별히 열린옷장에서 문자로 통지하는 내용은 없는게 맞는건지?
2. 결제정보의 '자세히' 화면 하부의 '결제취소' 버튼 말고 `대여기록`(/orders) 에서 주문서별 목록에서 '취소'를 누를경우 아래처럼 주문서가 삭제되었다는 메시지만 나오고 취소 버튼은 사라지지만 실제 결제취소가 되지는 않습니다. 이 부분이 의도한 동작이 맞는지 

![screenshot 2017-02-17 19 14 48](https://cloud.githubusercontent.com/assets/52704/23061614/ed377d58-f545-11e6-96d8-341005a301de.png)

이상이입니다. 가상계좌 환불도 테스트해보고 결과 남기겠습니다.

**Comment by yongbin** [comment]
![screenshot 2017-02-17 19 23 56](https://cloud.githubusercontent.com/assets/52704/23061852/c37f4efe-f546-11e6-8013-a80223588c94.png)

가상계좌를 통한 환불처리역시 테스트완료했고 특별한 문제가 없는것을 확인했습니다. 한가지 개인적인 의견은 '결제취소' 버튼을 아래로 내리면 좀 더 알아보기 쉬울것 같습니다.

**Comment by aanoaa** [comment]
> 신용카드 결제 취소가 되었을때 특별히 열린옷장에서 문자로 통지하는 내용은 없는게 맞는건지?

결제취소에 대한 알림을 사용자에게 어떤 내용, 어떤 방식으로 전달할지는 @10001if 님이 정해주셔야 합니다.

**Comment by aanoaa** [comment]
> 결제정보의 '자세히' 화면 하부의 '결제취소' 버튼 말고 대여기록(/orders) 에서 주문서별 목록에서 '취소'를 누를경우 아래처럼 주문서가 삭제되었다는 메시지만 나오고 취소 버튼은 사라지지만 실제 결제취소가 되지는 않습니다. 이 부분이 의도한 동작이 맞는지

취소를 누를 수 있는 상태가 정해져 있습니다.
결제완료된 주문서는 `자세히` 만 있고, `취소` 는 없습니다.

어떤 상태의 주문서를 취소하셨나요?

**Comment by yongbin** [comment]
당시에는 `결제완료`인 주문서를 취소했던것으로 기억이 나는데 지금 다시 확인해보면 `결제완료`인 주문서는 목록에서 `자세히`버튼밖에 보이지 않습니다. 특별히 수정하신게 아니라면 제가 착각한것일수 있습니다. 무시하셔도 됩니다.

**Comment by aanoaa** [comment]
변경된 점이 없습니다.

https://github.com/opencloset/OpenCloset-Share-Web/issues/23#issuecomment-281257641

가 해결되면 닫혀도 될 것 같습니다.

**Comment by yongbin** [comment]
@10001if  대표님 사용자가 결제를 취소했을때 문자로 어떤내용을 알려주어야 할지 문구를 결정해주세요

**Comment by 10001if** [comment]
[열린옷장] 안녕하세요. 000님. 2000-00-00, 00:00:00 에 대여신청한 자켓, 바지(대여품목)의 대여주문이 정상적으로 결제취소 되었습니다. 대여를 원하시는 경우 대여절차에 따라 다시 결제해주시기 바랍니다.

**Comment by aanoaa** [comment]
> [열린옷장] 안녕하세요. 홍형석님. 2017-01-26, 18:36:28 에 대여신청한 자켓, 팬츠, 셔츠의 대여주문이 정상적으로 결제취소 되었습니다. 대여를 원하시는 경우 대여절차에 따라 다시 결제해주시기 바랍니다.
