### ISSUE TITLE
온라인 대여 계산 오류 확인요망

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#230]
/orders/142108/purchase

3회이상 대여자 연장 주문건인데, 대여비용이 어떤 과정으로 계산된 건지 궁금합니다.
3회이상 대여자 연장일 경우, 할인전 연장비용으로 계산되는 오류만 있는 줄 알았는데 
이 경우는 어떤 이유로 대여비용이 계산되었는지 알수가 없습니다.
확인해주세요.

**Comment by pingpongworks** [comment]
3회 이상 대여자가 온라인대여를 이용하는 경우가 많아지고 있어서 계산 오류를 빨리 수정해야 할 듯 합니다. 주문이 들어올 때마다 일일히 수기로 계산하고 계좌를 받아서 입금해야해서 상당히 번거롭고, 서비스 자체의 신뢰도에 심각한 문제가 되고 있습니다. 빠른 수정 부탁드립니다. 

짧은 생각으로 오프라인 주문서의 계산 로그를 그대로 가져오면 좋을 거 같은데, 그렇게는 안되는지요?

**Comment by aanoaa** [comment]
#214 랑 같은 이슈입니다.

연장비가 잘못 계산되었습니다.

`32000 - 12000 = 20000` 원을 기준으로 계산된게 아니고,
`32000 + 12000 = 44000` 원을 기준으로 연장비가 계산되었습니다.

`44000` 의 40% `17600`

`20000(대여비) + 17600(연장비) + 3000(배송비)` 해서 `40600` 이 나온 겁니다.

**Comment by aanoaa** [comment]
이미 모듈화해서 같은 코드 같은 로직을 사용하고 있습니다.
결과에 대한 더하기 빼기 실수입니다.
아직 배포되지 않은 건데 오늘 중으로 배포하겠습니다.

**Comment by pingpongworks** [comment]
아, 거꾸로 12000원이 플러스 된 거네요. 
배포 부탁드릴게요.

**Comment by pingpongworks** [comment]
계산 오류 수정 확인했습니다. 감사합니다.
