### ISSUE TITLE
[쿠폰 오류] gimpo201901 쿠폰, 온라인 주문시 쿠폰할인 오류

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#232]
`orders/146033`
김포시 쿠폰으로 온라인 주문을 한 경우인데 쿠폰할인 전체가 되지 않고 
2,000원 결제가 살아있어서 택배비 포함 총 5,000원 결제비용이 나오는 오류입니다. 
오프라인에서는 문제가 없었는데 온라인 쿠폰할인 적용할 때 잘못된 부분이 있는지 확인부탁드립니다.
문제있으면 배송비 외 할인되도록 수정 요청드립니다.

더불어서, 확인요청드릴 부분은 
위 사용자가 쿠폰을 입력하고 주문을 하다가 품목을 변경하려고 다시 처음부터 다시 했는데
중복쿠폰으로 처음에 오류가 나서 김포시에 다시 다른 쿠폰을 요청해서 받은 후 진행을 했습니다. 
처음에 결제완료를 하지 않았는데도 "중복쿠폰"으로 뜬 이유가 궁금합니다. 
쿠폰번호를 입력한 후 어느 단계에서부터 사용한 쿠폰으로 상태가 바뀌는건지 궁금합니다.
 
<img width="1014" alt="스크린샷 2019-07-25 오후 12 02 23" src="https://user-images.githubusercontent.com/17288038/61842752-4676c780-aed4-11e9-9a4f-5603181f5a93.png">

**Comment by aanoaa** [comment]
온라인은 결제단계에서 쿠폰을 사용하기 때문에 쿠폰코드를 입력한 순간부터 사용된 쿠폰으로 구별됩니다.

이건 벨트 값이 포함된 것으로 보입니다.

**Comment by pingpongworks** [comment]
> 온라인은 결제단계에서 쿠폰을 사용하기 때문에 쿠폰코드를 입력한 순간부터 사용된 쿠폰으로 구별됩니다.

오프라인처럼 결제완료가 되었을 때 쿠폰이 사용되는 것으로 바꾸기는 어려울까요? 한 번 생각해봐주세요. 일단 원인을 알았으니까 문제 생겼을 때 설명을 할 수 있을 것 같습니다. 감사합니다.

**Comment by pingpongworks** [comment]
>이건 벨트 값이 포함된 것으로 보입니다.
벨트 값이 갑자기 왜 포함되었을까요? 김포시 쿠폰 발행할 때 문제가 있었던 걸까요?
