### ISSUE TITLE
2019년 추석 연휴 동안 온라인대여 신청을 할 수 없게 함

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#235]
택배 발송이 가능한 날짜를 고려헀을 때 추석연휴  전후하여 다음의 날짜가 의류착용일인 경우 배송을 할 수 없습니다.

2019-09-12 ~ 2019-09-18 의 의류 착용일을 누를 수 없게 하여 주문이 되지 않게 수정을 요청드립니다.

**Comment by aanoaa** [comment]
3d4aaca4471888107cf07157044a731203a0f273

패치하여서 적용하였습니다.

**Comment by pingpongworks** [comment]
감사합니다
