### ISSUE TITLE
[택배대여] 여성 팬츠 주문 방법 추가

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#236]
비즈니스캐주얼 면접이 많아지면서 여성이 팬츠를 주문하는 경우가 많아졌습니다. 

현재 택배대여 사이트에는 여성품목에 팬츠가 없다보니, 문의하는 분이 많습니다. 현재는 문의하는 경우 스커트를 선택해서 결제한 후 주문메모에 스커트가 아니라 바지라고 남겨달라고 안내하고 있습니다.  대여자의 불편함이 크므로 개선을 요청드립니다. 

![image](https://user-images.githubusercontent.com/17288038/67630346-a9a83980-f8c9-11e9-94e9-6eadab44f14a.png)

개선방법 1> 위 그림과 같이 품목선택시 여성 품목에 **여성팬츠** 항목 추가
개선방법 2> 품목 하단에 설명 추가 **팬츠를 대여하고자 하는 여성은 스커트를 선택해서 결제한 후 주문메모에 "스커트가 아니라 바지로 보내주세요"라고 남겨주세요**

`방법1`이 가능하면 좋겠지만, 작업시간이 오래 걸린다면 
`방법2`처럼 문구 추가라도 바로 부탁드립니다. 

11월 성수기에  불편함이 클 것으로 예상됩니다.

**Comment by aanoaa** [comment]
사나이 마크가 있다고 해서 남성전용의 것은 아닙니다.
팬츠를 대여하고자 하는 여성대여자는 팬츠를 선택하면 지금 원하시는 것과 꼭 맞습니다.
스커트를 선택하고 바지로 보내주세요 대신에 팬츠를 선택하면 됩니다.

대여자 입장에서는 앞에 사나이 마크가 혼란이 있을 수 있을 것 같은데,

1. 사나이 대신에 unisex symbol 을 넣거나
2. 여성팬츠 품목을 추가하거나(남성 팬츠를 누르는 것과 동작은 같음)
3. 도움메세지를 추가하거나

하는 방법이 있습니다.

> 팬츠를 대여하고자 하는 여성은 스커트를 선택해서 결제한 후 주문메모에 "스커트가 아니라 바지로 보내주세요"라고 남겨주세요

대신에,

> 팬츠를 대여하고자 하는 여성은 "스커트" 대신에 "팬츠"를 선택해주세요.

가 더 적절하지 않나 생각됩니다.

여성팬츠 항목을 추가하는 것은 팬츠+여성팬츠 둘다 선택하는 경우에는 팬츠를 2개 대여하는 것인지 헛갈릴 것 같습니다.

이 부분이 고려되어서 알려주시면 적용토록 하겠습니다.

---

어떠한 문구를 남길 것인지 결정해서 알려주시면 적용하겠습니다.(이걸 우선 적용)
여성팬츠 항목 추가에 대해서 위에 제가 염려하는 부분을 고민해서 알려주시면 이후에 적용하겠습니다.

**Comment by pingpongworks** [comment]
![image](https://user-images.githubusercontent.com/17288038/68083345-fad8a000-fe6a-11e9-9873-1df7c895ed73.png)

여성의 경우는 '팬츠'가 품목선택에 아예 안 뜨고 있어서요. 성별이 여성일 때도 '팬츠'가 뜨도록 해주시면 가장 좋을 거 같습니다.

**Comment by aanoaa** [comment]
아 #93 에서 그리되었습니다
여성의 경우 팬츠가 스커트 옆에 노출되도록 하겠습니다

**Comment by aanoaa** [comment]
@pingpongworks 배포되었습니다.

**Comment by pingpongworks** [comment]
확인했어요. 감사합니다.
