### ISSUE TITLE
결제를 취소하지 못했습니다 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#239]
온라인 주문 과정에서 결제를 취소하려고 했으나
다음의 메시지가 뜨면서 더이상 진행이 어려웠던 경우입니다. 

`orders/158336`

어떤 경우에 결제 취소가 되지 않는지 확인부탁드립니다. 

![결제를 취소하지 못했습니다](https://user-images.githubusercontent.com/17288038/70298647-b0fe2380-1835-11ea-9495-1f6e72ed2fbd.png)

**Comment by aanoaa** [comment]
pg 와의 사정이 있는 것 같습니다 아임포트 콘솔에서 추가 정보를 확인해봐야 하겠습니다.
살펴보겠습니다

**Comment by aanoaa** [comment]
PG 에서는 환불되었습니다.
PG 에서 환불이후에 아임포트 -> share 로 알림을 주고 받은 것도 이상없습니다.
현재 주문서의 상태도 환불 입니다.

열린옷장 서버에서 아임포트로 환불 API 를 호출했는데, 이때에 정상적인 응답을 받지 못해서 발생한 문제가 아닌가 싶습니다.

**Comment by pingpongworks** [comment]
현재 환불은 스태프가 아임포트 관리자 페이지에서 환불조치를 해서 그렇습니다.  
답변주신 것처럼 일단은 서버가 잠시 불안정했던 것으로 생각해볼 수 있을 거 같습니다. 
같은 현상이 또 발생하면 다시 확인요청드릴게요.
