### ISSUE TITLE
의류추천 단계 제거

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#242]
특정 신체 치수에 의류가 많아지다 보니 검색시간이 너무 오래걸려서 사용성을 해치는 경우가 발생하고 있습니다.

의류 추천 단계를 제거하고 추천대여 프로세스가 기본 동작으로 대체 된다면 좋을 것 같다고 합니다.
아이디어가 있다면 남겨주세요. @pingpongworks 

의류착용일을 선택 한 이후의 step 에서 바로 주소선택 단계로 이동되는 프로세스입니다.

**Comment by pingpongworks** [comment]
<img width="396" alt="스크린샷 2020-01-18 오후 6 39 17" src="https://user-images.githubusercontent.com/17288038/72661813-3a526980-3a22-11ea-92fa-d3bbce12d7ee.png">

3번의 내용이 바뀌면 좋을 거 같습니다.
=> **3. 대여내역을 확인합니다


<img width="396" alt="스크린샷 2020-01-18 오후 6 41 16" src="https://user-images.githubusercontent.com/17288038/72661821-5d7d1900-3a22-11ea-92b8-f4893691d54e.png">
추천검색 부분은 삭제되고요.
`대여내역 확인` 버튼이 있어서 누르면 4번 배송주소 입력 페이지로 넘어가도록 하면 어떨까요?

**Comment by pingpongworks** [comment]
>계속 "추천의류 검색 중" 이라고만 뜨네요..

라는 이유로 택배대여 주문을 하지 못하고 문의하는 대여자가 계속 생기고 있어서
`추천의류 검색 `단계를 제거하는 작업이 필요할 듯 합니다. 
빠른 시일내에 작업 요청드립니다.

**Comment by aanoaa** [comment]
추천의류 검색 기능을 제거 하였습니다.
확인해주세요.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다^^

**Comment by pingpongworks** [comment]
![택배대여-대문-수정_2020](https://user-images.githubusercontent.com/17288038/74896578-f6170800-53d7-11ea-8923-2889f42e4467.jpg)

의류추천 단계를 제거하면서 첫 페이지의 내용도 수정되어야하네요. 수정하는 김에 간단하게 만들었는데 교체가 가능할까요?

**Comment by aanoaa** [comment]
제가 디자인이 젬병이라 이건 각 잡고 고쳐야 합니다.

**Comment by pingpongworks** [comment]
네~ 각 잡힐 때 해주세요.

**Comment by aanoaa** [comment]
![Screenshot](https://user-images.githubusercontent.com/170528/76138093-751e6880-6087-11ea-9952-e005e10829a5.png)

**Comment by aanoaa** [comment]
![Screenshot(1)](https://user-images.githubusercontent.com/170528/76138105-93846400-6087-11ea-8163-59c26f559c4e.png)

**Comment by aanoaa** [comment]
내용 확인해주시면 적용하겠습니다.

**Comment by aanoaa** [comment]
피드백을 좀 기다리다가 적용했습니다.

**Comment by pingpongworks** [comment]
<img width="1280" alt="스크린샷 2020-03-07 오후 8 31 27" src="https://user-images.githubusercontent.com/17288038/76142619-c1cb6900-60b2-11ea-84ce-af5f05c21daf.png">
웹에서는 이렇게 보이네요ㅜㅜ  하단 푸터까지 이미지처럼 올라붙어 버렸어요. 방법이 없을까요? 중간의 프로세스 설명도 그냥 타이포 같아요ㅜ

**Comment by pingpongworks** [comment]
![택배대여-대문-수정_2020---복사본](https://user-images.githubusercontent.com/17288038/76143019-aa8e7a80-60b6-11ea-818e-a3fa303d6cd1.jpg)

중간에 문구들 다 뺴고 위와 같이 더 심플하게 하면 작업이 비슷하게 좀더 나올까요?

**Comment by pingpongworks** [comment]
![택배대여-로고](https://user-images.githubusercontent.com/17288038/76143173-8d5aab80-60b8-11ea-9697-b1ffce2b1cfe.jpg)

로고 역할을 하는 이미지 하나만 사이트 중앙에 넣어 주세요.

**Comment by pingpongworks** [comment]
닫고 새로운 이슈로 옮겨서 요청할게요.
