### ISSUE TITLE
택배대여 사이트 안내문구 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#244]
<img width="366" alt="스크린샷 2020-02-20 오후 4 14 44" src="https://user-images.githubusercontent.com/17288038/74913778-ad297880-5404-11ea-904d-ad562c33e083.png">

1. 착용일 하루전에 옷을 받을 수 있도록 준비해드립니다 =>
**착용일 하루전에 배송됩니다.**

2. 의류준비부터 배송까지 최소 5일이 소요됩니다. => 
**-발송부터 도착까지 배송기간 최소 3일 소요 (주말은 배송기간 제외)** 
**-당일 주문 / 당일 배송 불가**

안내문구 오인으로 인한 문의가 많아 문구 수정 및 문구 추가 요청드립니다.

**Comment by aanoaa** [comment]
변경했습니다.

**Comment by pingpongworks** [comment]
확인했어요. 감사합니다.
