### ISSUE TITLE
택배대여 "인트로 페이지" 디자인 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#247]
<img width="1280" alt="스크린샷 2020-03-07 오후 8 31 27" src="https://user-images.githubusercontent.com/17288038/76165399-2c0b0900-619a-11ea-8d12-54a0fc202825.png">

![IMG_0556](https://user-images.githubusercontent.com/17288038/76165488-c408f280-619a-11ea-89f9-a65a821a8b86.png)

택배대여 인트로 페이지가 현재 위와 같이 보입니다. 

- 웹 : 하단 푸터가 애매하게 위로 붙어 있습니다. 중간 카피들은 줄 바꿈도 이상하고 행간도 다 붙어있어서 내용 인지가 전혀 되지 않습니다. 
- 모바일 : 많지않은 내용인데 한 화면에 보이지도 않고 이상하게 보입니다.

**Comment by pingpongworks** [comment]
타이포가 들어간 페이지 디자인 작업이 어렵다면 다 빼고 더 심플하게 작업 부탁드립니다.

**Comment by aanoaa** [comment]
웹화면은 소령님 브라우저의 페이지 캐시 때문에 저랑 다르게 보입니다.
제가 보는 화면이 맞습니다.

그렇다고 하더라도 더 심플한 화면이 낫겠다고 생각하신걸로 이해하겠습니다.
전달해주신 이미지는 너무 작습니다.
사이즈를 조절 할 수 있으니 벡터 이미지파일이 아니라면 큰 이미지가 낫습니다.

그리고 텍스트는 포함되지 않는 이미지를 주시는게 좋습니다.
텍스트를 이미지안에 넣어버리면 고정비율로 표현되기도 하고 변경도 어렵습니다.
박스안에 옷들어가는 이미지만 크게 전달해주시면 그리 하겠습니다.
그걸 원하시는게 아니라면 위에 이미지를 크게 주세요.

**Comment by pingpongworks** [comment]
![택배대여-이미지](https://user-images.githubusercontent.com/17288038/76180015-19c3b600-6200-11ea-9de3-be24348ac963.png)

타이틀은 타이포가 아니라 이미지로 봐도 될 거 같아요. 이 정도 크기면 되나요?

**Comment by pingpongworks** [comment]
![11111](https://user-images.githubusercontent.com/17288038/76180673-f39f1580-6201-11ea-9ff9-e66e1f6230c9.jpg)

![22222](https://user-images.githubusercontent.com/17288038/76180680-fd287d80-6201-11ea-8321-df6535cfe73d.jpg)

완성본은 이 정도가 될 거 같아요.

**Comment by aanoaa** [comment]
변경했습니다.

**Comment by pingpongworks** [comment]
훨씬 깔끔해 보이네요. 확인했습니다.
