### ISSUE TITLE
블라우스의 종류 및 셔츠의 색상

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#25]
셔츠의 색상
- 하늘색
- 흰색

블라우스의 종류
- 라운드 반팔
- 라운드 민소매
- 탑
- 셔츠
- 승무원

---

사용자가 선택할 수 있게 해야합니다.
저장하는 컬럼이 없어서 컬럼을 추가해야 합니다.

**Comment by aanoaa** [comment]
order_detail.name 을 활용할 수도 있습니다.

    shirt|하늘색
    blouse|라운드블라우스

**Comment by aanoaa** [comment]
order 테이블에 컬럼을 하나 추가하고자 합니다.

`order.shirt_type`

셔츠 와 블라우스 모두 사용가능한 컬럼으로 텍스트를 저장

`하늘색셔츠`, `라운드블라우스`

등을 저장하는 용도입니다.

**Comment by aanoaa** [comment]
@yongbin @keedi 위와 같이 하고자 합니다.
다른 의견이 있다면 말씀해주세요.

**Comment by yongbin** [comment]
`order_detail`에 있는걸 쓰는게 더 좋지 않을까요? 따로 추가해야할 이유를 잘 모르겠습니다.

**Comment by aanoaa** [comment]
@yongbin order_detail 의 어떤 컬럼을 쓰나요?

**Comment by aanoaa** [comment]
대여품목에 관한 문제입니다 `pre_category`
자켓, 팬츠, 셔츠, 블라우스 등은 `pre_category` 에 기록하지만,

하늘색 셔츠, 라운드 블라우스등은 오프라인 대여에서는 주로 `order.desc` 를 이용해왔습니다.

위의 컬럼을 그대로 사용하지에는 적절치 않아서 새로 추가하고자 합니다.

order_detail 을 사용하기 어려울 수 있는 것이, 실제 품목이 바코드 찍혀서 대여상태가
되기까지 order_detail 은 존재하지 않을 수도 있습니다.

**Comment by yongbin** [comment]
네 그러네요 좀 더 생각해보니 블라우스가 특정되지 않은 상태에서 원하는 주문서의 속성을 저장해야하니까 컬럼이 필요하겠네요 앞으로 `shirt_type` 과 같은 컬럼이 앞으로 계속 생길꺼 같은 예감이 듭니다. 그때마다 컬럼을 추가할지, `online` 같은 컬럼에 JSON 인코딩 형태로 저장하는게 더 나을지는 잘 모르겠습니다.

**Comment by aanoaa** [comment]
@yongbin 특정되었다고 가정한다면, order_detail 에서 어떤 컬럼을 쓰려고 하셨나요?

**Comment by yongbin** [comment]
`clothes_code` 값이 없는 환불 같은 일종에 메타정보가 `order_detail`에 저장되니까 온라인 관련 특정되지 않은 정보고 `order`에 저장하지 말고 order_detail에 name 이나 desc 그런쪽에 추가했다가 특정되때 삭제하는건 어떨까요?

**Comment by aanoaa** [comment]
온라인 주문서의 경우에는 `order.pre_category` 를 이용하지 않고,
`order_detail` 을 `pre_category` 처럼 사용합니다.

`order_detail.desc` 를 대신해서 사용할 수 있을 것 같습니다.
`desc` 컬럼은 대여가능하지 않게 되었을때를 대비해서 남겨두려고 했는데
셔츠나 블라우스의 경우에는 활용이 가능합니다.

**Comment by yongbin** [comment]
넵 처음 스키마를 만들때는 지금 처럼 상품이 특정되지 않은 경우나 온라인 대여를 염두하지 않았기 때문에 스키마상 제약이 좀 있는데 추후 개편때는 이부분도 고려해서 스키마 구조가 변경되어야 할거 같습니다.

**Comment by 10001if** [comment]
남성의 경우 셔츠를 선택한 때에는 `흰색셔츠` 혹은 `하늘색셔츠` 중 반드시 한가지를 선택해야 완료가 될 수 있도록 수정 요청드립니다. 이는 여성의 경우도 마찬가지입니다. 블라우스 선택 시 `라운드 반팔` `라운드 민소매` `탑` `셔츠` `승무원` 중에 한 가지를 선택해야만 넘어갈 수 있도록 요청드립니다. 또한 여성의 경우 블라우스 종류 중 `라운드 긴소매`의 종류 를 추가 요청드립니다.
