### ISSUE TITLE
신체치수 입력_새로운 기성사이즈화에 맞춰 수정 (전체 설명)

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#254]
https://share.theopencloset.net/measurements
새로 정립된 기성사이즈 기준과 현재 사이트에 노출되어 있는 여성 사이즈표 기준이 달라 빠른 수정이 필요합니다. 또한 택배대여자가 주문시 기성사이즈로 옷을 대여할 수 있도록 신체치수 측정 페이지의 수정이 필요합니다. 한꺼번에 다 작업이 가능하면 좋겠지만, 단계적으로 작업을 한다면 중요 순으로 정리했습니다. 

1. 현재 노출되어 있는 여성 사이즈표 수정
2. 남성 사이즈표 추가
3. 사용자정보에 구현된 기성사이즈 추천 기능 적용
4. 관리자 페이지에서 발송할 기성사이즈를 확인가능하도록 추가
5. 신체치수 측정 방법 안내 페이지 내용 간략하게 수정

**Comment by pingpongworks** [comment]
1. 현재 노출되어 있는 여성사이즈표는 다음의 표로 수정 요청합니다.

_
**여성자켓 (cm)**

사이즈 호칭 | 자켓 윗배둘레 | 자켓 가슴둘레
-- | -- | --
33 | 68 이하 | 77 이하
44 | 70 | 80
55 | 74 | 84
66 | 78 | 86
66반 | 82 | 88
77 | 86 | 92
88 | 88 | 96
88반 | 92 | 98
99 | 94 | 106
110 | 100 | 110
110 | 106 | 112
120 | 110 | 116
130 | 114 | 120 이상

_
**여성 치마/바지 (cm)**

사이즈 호칭 | 하의 엉덩이둘레 | 하의 허리둘레
-- | -- | --
33 | 85 이하 | 60 이하
44 | 86 | 64
55 | 90 | 66
66 | 94 | 68
77 | 98 | 73
88 | 102 | 80
99 | 108 | 85
100 | 114 | 94
110 | 118 | 101
120 | 122 | 108

**Comment by pingpongworks** [comment]
2. 남성 사이즈표 추가
_
**남성 자켓 사이즈 참조표 (cm)**

사이즈 호칭 | 자켓 윗배둘레 | 자켓 가슴둘레
-- | -- | --
90 | 84 이하 | 94 이하
95 | 88 | 98
100 | 94 | 104
105 | 100 | 108
110 | 104 | 112
115 | 112 | 116
120 | 118 | 124
125 | 124 | 130
130 | 128 | 138
135 | 130 이상 | 140 이상


_
**남성 바지 사이즈 참조표 (cm)**

사이즈 호칭 | 바지 허리둘레
-- | --
26 | 74이하
28 | 76
30 | 80
32 | 84
34 | 88
36 | 92
38 | 96
40 | 100
42 | 104
44 | 108
46 | 112
48 | 116
50 | 122

**Comment by pingpongworks** [comment]
3. 사용자정보에 구현된 기성사이즈 추천 기능 => 온라인 치수측정 페이지에도 적용
- 동영상 오류화면 / 팔길이 / 인치변환표 삭제
- 키 / 몸무게 / 가슴둘레 / 윗배둘레 / 허리둘레 / 허벅지둘레 / 구두사이즈 순으로 수정
- 기성사이즈 기입란 추가
- 의류사이즈 참조표 추가


**현재 페이지 모습**

![image](https://user-images.githubusercontent.com/17288038/79838720-63521400-83ee-11ea-8382-d7bf6e96cf2e.png)


_
**수정 페이지 시안**

![image](https://user-images.githubusercontent.com/17288038/79838823-8f6d9500-83ee-11ea-83a6-57822636a4cb.png)

**Comment by pingpongworks** [comment]
4. 관리자 페이지에서 발송할 기성사이즈를 확인가능하도록 추가
_
![image](https://user-images.githubusercontent.com/17288038/79839339-584bb380-83ef-11ea-9ae1-fbf32bf8215b.png)

**Comment by pingpongworks** [comment]
5. 신체치수 측정 방법 안내 페이지 내용 간략하게 수정

_
**현재 페이지 모습**

![image](https://user-images.githubusercontent.com/17288038/79839529-9648d780-83ef-11ea-99a0-0b5532807d84.png)


_
**수정 페이지 시안**

<img width="732" alt="스크린샷 2020-04-21 오후 4 46 58" src="https://user-images.githubusercontent.com/17288038/79839696-dd36cd00-83ef-11ea-8736-b98067c9ef78.png">
<img width="603" alt="스크린샷 2020-04-21 오후 4 48 26" src="https://user-images.githubusercontent.com/17288038/79839740-f0499d00-83ef-11ea-83eb-9c2947ca59d2.png">

**Comment by pingpongworks** [comment]
본 이슈는 전체적인 설명을 위해 정리한 것입니다. 요청 드릴 작업별로 이슈 따로 올리겠습니다.

**Comment by aanoaa** [comment]
- 입력에 따른 추천 치수 표시
- 참초표 팝업 추가
- 기성복 치수 입력 받을 수 있도록 함
- 관리자 페이지에 추천 치수와 기성복 치수 표시

![Screenshot](https://user-images.githubusercontent.com/170528/90306420-0f70bb00-df08-11ea-816e-bd46c6cbc205.png)
![Screenshot(1)](https://user-images.githubusercontent.com/170528/90306422-10a1e800-df08-11ea-94fd-eba574be6394.png)

---

![Screenshot(2)](https://user-images.githubusercontent.com/170528/90306423-11d31500-df08-11ea-85d1-82a121212f1f.png)
![Screenshot(3)](https://user-images.githubusercontent.com/170528/90306424-126bab80-df08-11ea-8082-0858ef87afec.png)

---

![Screenshot(4)](https://user-images.githubusercontent.com/170528/90306437-30391080-df08-11ea-9c7d-c430530430e5.png)

**Comment by pingpongworks** [comment]
![택배대여 사이즈입력](https://user-images.githubusercontent.com/17288038/90330867-f987f680-dfea-11ea-9530-281c040f0532.png)


- 상의 inch => 상의 (size)
- 하의 inch => 하의 (허리 inch)

이 부분만 수정해주세요. 나머지는 좋은 거 같습니다.

**Comment by aanoaa** [comment]
아 상의는 cm 네요. 가슴둘레니까
근데 여성의 경우는 또 44,55 이러니까 cm 라는 단위가 어울리지 않네요.

단위표시를 제거하고 배포하겠습니다.

**Comment by aanoaa** [comment]
배포했습니다.
반드시 테스트해보시고 이상한 점을 말씀 해주세요.

**Comment by aanoaa** [comment]
필수 입력 값이

- 키
- 몸무게
- 가슴둘레

인데 여전히 윗배둘레, 팔길이등을 체크하고 있었고 수정해서 배포했습니다.

**Comment by pingpongworks** [comment]
<img width="635" alt="스크린샷 2020-08-17 오후 5 34 29" src="https://user-images.githubusercontent.com/17288038/90375846-77fa9c00-e0b0-11ea-8907-cd6bb8cce80a.png">

1) 대여자가 신체치수를 입력한 후 `저장`을 누르면 입력한 치수를 바탕으로 추천사이즈가 바뀐다
2) 대여자가 신체치수를 수정하고 싶은 경우, 수정해서 입력한 후 `저장`을 누르면 바뀐 치수를 바탕으로 추천사이즈가 바뀐다
3) 신체치수 입력과 확인을 끝냈으면 `다음`페이지로 넘어간다. 

이렇게 되어야 할 거 같아서 다음과 같이 버튼 부분 수정과 추가 요청합니다. 

`신체치수 저장 ` `다음`

**Comment by pingpongworks** [comment]
<img width="635" alt="스크린샷 2020-08-17 오후 5 32 51" src="https://user-images.githubusercontent.com/17288038/90376141-f6efd480-e0b0-11ea-9102-c02c21c58c3d.png">

이런 형태면 될 거 같아요.

**Comment by pingpongworks** [comment]
<img width="1280" alt="스크린샷 2020-08-17 오후 8 59 34" src="https://user-images.githubusercontent.com/17288038/90393996-c74ec580-e0cc-11ea-8731-e0f0fe9d1b0f.png">
 윗배둘레 설명, 다음의 내용으로 교체해주세요.  

    윗배둘레는 열린옷장 만의 사이즈로 자켓 단추가 잠기는 위치의 둘레입니다. 배꼽에서 6cm 위의 둘레를 수평으로 측정합니다.

**Comment by aanoaa** [comment]
신체치수를 변경해도 추천 사이즈가 바로 변경되지 않는 버그가 있네요.
제가 예측하던 거랑 다르게 동작하고 있었는데 인지하지 못하고 있었습니다.
그래서 대안을 제시해주신 거군요.
(숫자를 replace 하려고 시도했기 때문)

원래 의도대로 입력이 변경되면 추천 사이즈가 변경되도록 동작할 수 있도록 패치하겠습니다.

**Comment by pingpongworks** [comment]
네, 감사합니다!

**Comment by aanoaa** [comment]
배포했습니다.
Ctrl + Shift + R 페이지 새로고침 하신 다음에 테스트해보세요.

**Comment by pingpongworks** [comment]
테스트 해보니까 잘 됩니다~

**Comment by pingpongworks** [comment]
본 이슈에서는 윗배둘레 설명만 수정하면 될 거 같아요.

**Comment by aanoaa** [comment]
5dcc97847e962e78cb29fa3a9b7032a0d9e6f9a8

다음 배포에 포함됩니다.
닫겠습니다.
