### ISSUE TITLE
의류착용일에 따라 배송방법을 선택할 수 있도록 함

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#256]
현재 일반택배로만 배송하다보니 최소 5일전에 주문을 해야하는 문제점이 있습니다. 개선을 위해 배송방법을 선택하고 그에 맞는 결제를 할 수 있도록 보완 요청드립니다. 

1) 일반택배
2) 우체국 익일배송
3) 당일 퀵배송

**Comment by pingpongworks** [comment]
본 이슈는 전체적인 설명을 위해 정리한 것입니다. 요청 드릴 작업별로 이슈 따로 올리겠습니다.

**Comment by aanoaa** [comment]
@pingpongworks 우체국 익일 발송은 주말/공휴일 상관 없나요?
아니면 고려해야 하나요?

**Comment by pingpongworks** [comment]
주말, 공휴일 고려해야하네요. 
금요일 발송하면 월요일 도착한다고 봐야합니다.

**Comment by aanoaa** [comment]
한번씩 작업할때에 막히는 부분이 있기도 했고, 제가 게을러서 못했습니다.

- [x] 날짜 계산
- [ ] UI 빌드
- [ ] 결제 테스트

등의 작업이 남았습니다.

제가 UI 작업하는데 어려움을 느끼고 있고, 남는 시간 운용이 어떻게 될지 몰라서 죄송하게도 데드라인을 적기가 부담스럽습니다.
부지런히 살펴보겠습니다.

**Comment by pingpongworks** [comment]
앞뒤가 안 맞지만 너무 부담은 갖지 마시고 부지런히 부탁드려요~

**Comment by aanoaa** [comment]
배송방법에 따라 결제 마감시간을 고려해야 합니다.
일반택배는 지금과 같이 주문시간이후 ~ AM 09:00 까지 결제되어야 하지만,
우체국택배와 퀵서비스는 PM 02:00 까지 결제되어야 합니다.

주문시간에 따라 정책이 변경되는데,
14:00 이후에 주문했다면 당일에는 발송할 수 없고,
익일 14:00 까지 입금할 수 있습니다.
이후에는 입금할 수 없습니다.

14:00 이전에 주문했다면 당일 14:00 까지 입금할 수 있습니다.
단 주문날짜가 공휴일이면 당일은 불가능하고, 다음 영업일 14:00 까지 입금할 수 있습니다.

**Comment by aanoaa** [comment]
주문서에 배송방법에 대해 저장하는 컬럼이 없습니다.
주문서 스키마를 변경해야 합니다.

`shipping_misc` 라는 컬럼이 이미 사용되고 있으므로, `shipping_method` 컬럼을 추가할까 합니다.

**Comment by aanoaa** [comment]
관리메뉴의 목록마다의 날짜 계산이 모두 일반 택배 기준으로 되어 있습니다.
배송방법을 고려해서 관련된 부분들을 모두 변경해주어야 합니다.

**Comment by aanoaa** [comment]
주문할때에 배송방법을 변경하는 작업과 별개로 뒤에서 업무처리를 위해 해야할 일들을 가늠해야 합니다.
배송비와 배송방법에 따라 날짜계산하는 부분들을 살펴야 합니다.

스키마도 변경되었고 처음 예상보다 작업 범위가 넓습니다.

**Comment by pingpongworks** [comment]
작업시간이 좀 걸릴 듯하네요. 급하게 필요한 분이 있을 경우를 위해 안내문구라도 넣어야하지 않을까 합니다. 

>- 발송부터 도착까지 배송기간 최소 3일 소요 (주말은 배송기간 제외)
>- 당일 주문 / 당일 배송 불가

위 문구를 아래 문구로 수정 요청 드립니다. 

- 안전한 배송을 위해 배송기간 2박3일 소요 (주말은 배송기간 제외)
- 당일 퀵배송, 익일 우체국 배송이 필요하신 경우 전화 or 카톡 문의주세요.

**Comment by pingpongworks** [comment]
다음 사항 보완 부탁합니다.

1. 문구 수정

**- [ ] 일반택배(3,000원)**
   배송기간 평균 2일 소요 
   도서산간 지역, 주말 예외

**- [ ] 당일 퀵배송 (서울, 경기만 / 착불)**
   평일 오후 2시 이전에만 신청 가능 
   주말/공휴일 신청불가 
   배송비 10,000원부터 지역에 따라 다름  

**- [ ] 우체국 익일배송 (6,000원)**
   오후 2시 이전 결제 완료시 익일도착
   도서산간 지역, 주말 예외 


- 본문과 구분되도록 제목은 볼드체로 해주세요



2. 당일퀵 배송 >> 주말 착용일 선택 제외 


3.결제시 안내 문구 수정

**2021년 5월 10일 오후 2시까지 결제가 완료되어야 5월 11일 배송이 가능합니다. 기한내 미결제시 배송이 불가능하며 해당시각 이후에는 결제 할 수 없습니다.**

**Comment by aanoaa** [comment]
생각해보면 안될 것도 없습니다.
주말이나 공휴일 전날 보낼 수도 있기 때문입니다.

2021년 5월 달력입니다.

오늘을 5/3 일 이라고 가정했을때에 quick service 로 5/8 일을 의류 착용일로 선택 못할 이유가 없습니다.
5/6 일날 보내면 됩니다.
물론 일반택배로 보내도 되지만 사용자의 선택입니다.

예외는 있습니다.
오늘이 5/7 일 이고 오후 3시 일때에 5/8 일을 의류착용일로 할 수 없습니다.
이때에는 퀵서비스로 선택했을때에 가장 빠른 배송일이 5/10 입니다.

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-right" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-right">Su</th>
<th scope="col" class="org-right">Mo</th>
<th scope="col" class="org-right">Tu</th>
<th scope="col" class="org-right">We</th>
<th scope="col" class="org-right">Th</th>
<th scope="col" class="org-right">Fr</th>
<th scope="col" class="org-right">Sa</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-right">&#xa0;</td>
<td class="org-right">&#xa0;</td>
<td class="org-right">&#xa0;</td>
<td class="org-right">&#xa0;</td>
<td class="org-right">&#xa0;</td>
<td class="org-right">&#xa0;</td>
<td class="org-right">1</td>
</tr>


<tr>
<td class="org-right">2</td>
<td class="org-right">3</td>
<td class="org-right">4</td>
<td class="org-right">5</td>
<td class="org-right">6</td>
<td class="org-right">7</td>
<td class="org-right">8</td>
</tr>


<tr>
<td class="org-right">9</td>
<td class="org-right">10</td>
<td class="org-right">11</td>
<td class="org-right">12</td>
<td class="org-right">13</td>
<td class="org-right">14</td>
<td class="org-right">15</td>
</tr>


<tr>
<td class="org-right">16</td>
<td class="org-right">17</td>
<td class="org-right">18</td>
<td class="org-right">19</td>
<td class="org-right">20</td>
<td class="org-right">21</td>
<td class="org-right">22</td>
</tr>


<tr>
<td class="org-right">23</td>
<td class="org-right">24</td>
<td class="org-right">25</td>
<td class="org-right">26</td>
<td class="org-right">27</td>
<td class="org-right">28</td>
<td class="org-right">29</td>
</tr>


<tr>
<td class="org-right">30</td>
<td class="org-right">31</td>
<td class="org-right">&#xa0;</td>
<td class="org-right">&#xa0;</td>
<td class="org-right">&#xa0;</td>
<td class="org-right">&#xa0;</td>
<td class="org-right">&#xa0;</td>
</tr>
</tbody>
</table>

**Comment by aanoaa** [comment]
### 퀵배송인 경우

- 금일이 주말/공휴일인 경우 배송불가
- 익일이 주말/공휴일이고 현재시간이 14:00 이후라면 익일 배송불가
- 착용일이 주말/공휴일인 경우 주말/공휴일 - 1 일 전에 배송
  16일 의류착용일을 선택했다면, 14일 배송
  단 현재시간이 14일 14:00 이후라면 17일 부터 의류착용일을 선택가능

다른 예외사항이 있는지 고민해봐야 합니다.
좀 더 명확한 기준으로 정리해야 합니다.

**Comment by aanoaa** [comment]
제 추론에 틀린 부분은 없는지랑 더 고려해야 할 부분에 대해 검토해야 합니다.

**Comment by aanoaa** [comment]
> 2021년 5월 10일 오후 2시까지 결제가 완료되어야 5월 11일 배송이 가능합니다. 기한내 미결제시 배송이 불가능하며 해당시각 이후에는 결제 할 수 없습니다.

이건 퀵서비스에만 해당하는 건가요?
일반택배의 경우에는 오전 9시가 결제 마감시간 이었습니다.

**Comment by aanoaa** [comment]
> 이건 퀵서비스에만 해당하는 건가요?
> 일반택배의 경우에는 오전 9시가 결제 마감시간 이었습니다.

지난 번 작업때에 일반택배와 우체국 택배는 기존처럼 `09`시를 결제 마감시간으로 했고,
퀵서비스의 경우에만 `14`시로 했습니다.

**Comment by aanoaa** [comment]
@pingpongworks 배포했습니다.
주말이라서 퀵서비스 배송이 차주 월요일부터 가능합니다.
테스트해보시고 이상한 부분은 말씀해주세요.

택배대여 워크플로우가 변하기 때문에 담당 옷장지기에게 각 배송방법에 대한 내용을 인스톨해야 합니다.

**Comment by pingpongworks** [comment]
테스트 해보았어요. 현재로는 발견되는 문제점 없습니다.
앞으로는 담당자가 아침과 오후 2시, 2회 택배대여 주문을 확인할 예정입니다. 
잘 사용하겠습니다. 감사합니다~
