### ISSUE TITLE
네이버페이 가입을 위한 하단 푸터 내용 추가

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#257]
<img width="735" alt="스크린샷 2020-07-10 오후 4 24 09" src="https://user-images.githubusercontent.com/17288038/87128162-1fbec600-c2ca-11ea-9d9a-a8a70ed2784e.png">

<img width="1145" alt="스크린샷 2020-07-10 오후 4 25 48" src="https://user-images.githubusercontent.com/17288038/87128183-26e5d400-c2ca-11ea-8aad-98468795bd87.png">

위의 네이버 규정에 따라 택배대여사이트 하단 푸터에 입금계좌 추가해주세요.

    (국민은행) 205737-04-003013 (예금주:사단법인 열린옷장)

**Comment by aanoaa** [comment]
입금계좌는 네이버페이의 기본 정보가 아닌데요?
사업자정보확인 페이지가 외부 링크로 제공되어야 하는데 그 정보를 알려주셔야 합니다.

**Comment by pingpongworks** [comment]
https://teht.hometax.go.kr/websquare/websquare.html?w2xPath=/ui/ab/a/a/UTEABAAA13.xml
이미지에 나와 있어서 넣어야할 거 같았어요. 사업자 정보 확인 페이지 주소입니다.

**Comment by aanoaa** [comment]
추가하였습니다.

**Comment by pingpongworks** [comment]
감사합니다.
