### ISSUE TITLE
추천대여 에 관한 설명

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#26]
```
열린옷장의 누적 대여기록과 신체치수를 바탕으로 의류가 추천되었습니다.
마음에 드는 자켓사진을 선택해서 진행하시거나 `추천대여` 버튼을 눌러주세요.
추천된 의류가 없으면 추천대여 버튼을 눌러주세요.
추천대여란? 옷장지기가 주문서를 보고 의류를 대신 골라 드립니다. 
```

대여품목을 선택하고 자켓+팬츠가 선택되었을때 의류가 추천됩니다.
이때에 맘에 드는 의류가 없거나 추천된 의류가 없을때를 대비해서 `추천대여` 라는 개념을
만들었습니다.

이에 대한 설명이 부실해서 진행하기가 어렵다는 의견이 있습니다.

**Comment by 10001if** [comment]
@aanoaa 추천대여의류를 보여줄 때 로딩하는 시간 동안 아래와 같은 이미지가 나타납니다.
![2016-12-14 4 33 07](https://cloud.githubusercontent.com/assets/4696328/21173447/10ab8706-c21b-11e6-954a-4aad09a82ce7.png)

그런데 로딩하는 시간이 꽤 길어서 정상적으로 의류를 보여주는 상태인지 판단하기 어려울 것 같습니다. 본 이미지 아래에 "추천 의류를 찾고 있는 중입니다. 의류 검색량에 따라 소요시간이 길어질 수 있습니다. 잠시만 기다려 주세요" 라는 멘트 삽입을 요청드립니다.

**Comment by aanoaa** [comment]
#70 에서 추천대여에 관한 설명을 새롭게 받아서 적용하였습니다.
로딩 이미지는 필요하다면 다시 등록해서 진행하겠습니다.
