### ISSUE TITLE
치수측정 가이드_내용 간략하게 수정 요청

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#260]
_
[현재 페이지 모습]

![image](https://user-images.githubusercontent.com/17288038/89758112-fb9d1180-db21-11ea-9128-9b2afdae46c0.png)

_
[수정 요청안]

![치수측정-수정안](https://user-images.githubusercontent.com/17288038/89758813-a95cf000-db23-11ea-80cd-f6b0d8bbad2f.jpg)

**Comment by aanoaa** [comment]
#254 에서 진행하겠습니다.
