### ISSUE TITLE
치수측정 페이지 중 필요없는 정보 삭제 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#261]
- [ ] 남성 치수측정 페이지

<img width="1020" alt="스크린샷 2020-08-10 오후 5 22 38" src="https://user-images.githubusercontent.com/17288038/89778447-8133b800-db48-11ea-92e1-3fd63e633803.png">

- [ ] 여성 치수측정 페이지
<img width="852" alt="스크린샷 2020-08-10 오후 8 34 59" src="https://user-images.githubusercontent.com/17288038/89779345-184d3f80-db4a-11ea-99a6-a72f49b2c0e2.png">

-----
1. 빨간 박스 내용 모두 삭제해주세요.
2. 파란 박스의 치수측정 사진, 새로 찍은 걸로 교체해주세요. => 사진데이터는 @aanoaa 메일로 보냈습니다.

**Comment by aanoaa** [comment]
#254 에서 같이 진행하겠습니다.
