### ISSUE TITLE
안산 쿠폰 단벌할인이 되지 않음

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#263]
`orders/174606`
--------
<img width="1280" alt="스크린샷 2020-08-27 오후 3 53 05" src="https://user-images.githubusercontent.com/17288038/91408994-bac22e00-e87f-11ea-970d-f0cf26db1e59.png">
안산쿠폰으로 택배주문한 건인데, 단벌할인이 되지 않았습니다.
일단 제가 결제하고 주문확정 처리는 했는데, 쿠폰 번호에 문제가 있는 건지 확인 부탁드립니다.

**Comment by aanoaa** [comment]
온라인사용자이고 결제대기 상태에서 쿠폰을 적용하였습니다.
이는 정상적인 케이스입니다.

15시 34분 <- 결제대기 상태로 변경
15:37:14 <- 이때 쿠폰 적용; 단벌 할인쿠폰인데 0원으로 적용됨
15시 43분 <- 입금대기 상태로 변경

데이터가 변해버려서 추적할 수 없고, 로그에도 별 내용이 없습니다.
특이 사항은 없었나요?

**Comment by aanoaa** [comment]
같은 대여 품목으로 안산 쿠폰을 사용해서 테스트 해봤을때는 단벌 할인 쿠폰이 올바르게 적용되었습니다.

제가 테스트한 거랑은 다른 케이스 일 것 같은데..
쿠폰 적용하기 전 상태의 데이터가 없어서 재현이 안될 수 있습니다.

**Comment by aanoaa** [comment]
쿠폰에 무슨 이상이 있는 것은 아닙니다.

**Comment by aanoaa** [comment]
제가 추측하는 단벌 할인쿠폰이 0원으로 떨어지는 케이스 입니다.

- `jacket`
- `skirt`
- `pants`
- `blouse`
- `shoes`

대여품목이 이러한데,
결제대기 상태인 주문서에 쿠폰을 적용하기 전에 staff 가 개입해서 대여품목을 지정했다고 가정하면..

- `J0WH - 자켓`
- `P1OS - 팬츠`
- `A1LA - 구두`
- ...

대여품목의 이름이 이렇게 변경되는데, 이러한 상황에서 쿠폰을 적용하면 단벌 할인쿠폰 0원 이 됩니다.

**Comment by aanoaa** [comment]
근본적으로 이런 오류를 해결하려면..
꼼꼼하게 검증하는 프로세스가 있어야 합니다.
시간과 작업 볼륨이 매우 크고 혼자서는 안됩니다.

지금 상황에서는 이렇게 작업하기는 어렵고..
이런 케이스가 발생할때마다 로그를 더 남겨서
다음에 같은 케이스에 의한 오류가 발생할때에 원인을 파악할 수 있다면 다행이겠습니다.

**Comment by pingpongworks** [comment]
네, 아마도 스태프가 개입한 과정이 있을 거 같아요. 다음에 같은 케이스 있을 때 다시 이야기할게요.

**Comment by aanoaa** [comment]
할인 전에 주문서와 주문서 상세정보를 로그에 남기도록 했습니다.
다시 발생했을때는 원인을 찾는데 더 도움이 되겠습니다.
