### ISSUE TITLE
배송지역 제한 문구 삭제 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#268]
<img width="664" alt="스크린샷 2020-10-09 오전 12 17 36" src="https://user-images.githubusercontent.com/17288038/95479032-41ad0f00-09c5-11eb-9d8e-57232cc6cb7e.png">

서울시쿠폰으로 대여하는 경우, 
서울 외 지역으로도 배송이 가능하도록 지침이 변경되었습니다.
위 박스내 문구 삭제해주세요.

**Comment by aanoaa** [comment]
삭제했습니다.
