### ISSUE TITLE
쿠폰 주문인데 단벌 할인이 되지 않은 오류 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#283]
`orders/188995`

안양쿠폰으로 택배주문을 했는데 
택배비 3,000원만 제외하고 대여비 25,000원이 결제금액으로 나와서
대여자가 카드결제를 한 경우입니다. 
확인 부탁드립니다. 

같은 대여자가 2018년에도 쿠폰대여인데 단벌할인이 되지 않아 결제 후 다시 환불했었습니다. 

원인 확인 부탁드립니다.

**Comment by aanoaa** [comment]
이분 성별이 비어있습니다.
쿠폰 타입의 경우 남성의 경우 32,000 까지 할인되고, 여성의 경우 30,000 까지 할인이 되는데
이분은 성별을 알수 없어서 할인금액이 0원으로 계산되었습니다.
성별없이 가입할 수 없는데 어떻게 가입한 건지 알아봐야 합니다.

**Comment by aanoaa** [comment]
사용자 정보를 보면 성별이 "남자" 로 나타나긴 하는데, 성별이 비어있을 경우에 "남성" 으로 간주한 것이고, 실제 데이터는 비어 있습니다.
사용자의 성별 정보를 업데이트 해주어야 하겠습니다.

**Comment by aanoaa** [comment]
15만명 중에 성별이 비어있는 사용자가 3만명입니다.
어느 경로를 통해서 이렇게 사용자등록이 되는지 살펴봐야 합니다.

**Comment by aanoaa** [comment]
`gender` 가 비어있는 사용자들은 대부분 email 과 password 또한 비어 있습니다.
하루에 적게는 1 or 2건, 많을때는 10건 정도 꾸준하게 발생하고 있습니다.

offline 에서 유입되는 사용자 같습니다.
visit 혹은 취업날개를 통해 유입되는 사용자 일 것으로 추정합니다.

**Comment by aanoaa** [comment]
성별 정보가 없이 사용자등록이 된 특이한 케이스 입니다.

1. 이러한 경우에도 suit 쿠폰이 0원으로 판별되지 않도록 패치하거나,
2. 어떻게 성별 정보 없이 사용자등록이 되었는지 추적해야 합니다.

2번은 추적하기가 쉽지 않습니다.
1번은 당장에 대응할 수 있는 방법이라서 그렇게 하겠습니다.

**Comment by aanoaa** [comment]
성별정보가 없는 사용자의 suit 쿠폰 최대가격을 30,000 원으로 반영했습니다.
