### ISSUE TITLE
택배대여 주문 등록시 CJ / 우체국 선택가능하도록

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#286]
![스크린샷 2021-05-20 오후 7 52 03](https://user-images.githubusercontent.com/17288038/118968058-6e3af780-b9a6-11eb-9ecd-e0a47a89a0a8.png)

스태프가 택배대여 발송 후 주문서에 운송장번호 입력을 할 때

- CJ 대한통운
- 우체국

두 가지 중 하나를 선택할 수 있도록 요청드립니다.  

![스크린샷 2021-05-20 오후 8 01 18](https://user-images.githubusercontent.com/17288038/118968149-8874d580-b9a6-11eb-9469-7c043c40eaf2.png)
![스크린샷 2021-05-20 오후 8 06 54](https://user-images.githubusercontent.com/17288038/118968934-7182b300-b9a7-11eb-81d1-817a6e13f8f0.png)

우체국 익일택배, 퀵배송 선택기능을 추가하자마자 이용자가 예상보다 많아서 운송장번호 등록시 구분해서 등록할 필요가 있을 듯 합니다.

**Comment by aanoaa** [comment]
우체국택배로 구분해서 운송장을 입력할 수 있도록 하고 배포하였습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
