### ISSUE TITLE
우체국 택배인 경우, 발송문자 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#288]
![IMG_3018](https://user-images.githubusercontent.com/17288038/119448284-0b61ab80-bd6c-11eb-8ffa-607103fb7f82.PNG)

우체국택배로 발송한 경우, 
우체국택배로 등록을 하고 `배송완료 `로 변경하면 
CJ대한통운이 아닌 `우체국택배`로 문자 안내가 발송되도록 요청드립니다.

**Comment by aanoaa** [comment]
배포되었습니다.

**Comment by pingpongworks** [comment]
발송할 때 확인하겠습니다. 감사합니다.
