### ISSUE TITLE
우체국택배, 2시 이전 착용일 선택 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#291]
![스크린샷 2021-06-01 오전 10 01 43](https://user-images.githubusercontent.com/17288038/120252789-7ce7af80-c2c0-11eb-9acf-171d244e6061.png)

`우체국 익일배송`으로 배송받고자 할 경우, 
2시 이전에 주문하면 당일 발송이 가능하므로 
착용일은 3일이 착용일인 대여자도 주문이 가능해야 합니다. 

현재는 4일부터 가능한 상태라 수정 부탁드립니다.

**Comment by aanoaa** [comment]
이건 의도된 기능입니다. 도착일은 맞을 수 있지만 고착시간은 예상할 수 없습니다.

해서, 의류배송을 받은 다음날 부터 의류착용일 입니다.

**Comment by pingpongworks** [comment]
퀵 당일배송과 마찬가지로 2시를 기점으로 가장 가까운 의류착용일 선택이 달라져야하는게 아닐까요?

**Comment by aanoaa** [comment]
위 캡쳐를 보면 도착예정일이 3일 이면 착용일은 4일이 맞습니다.
위 캡쳐의 시간이 14:00 이전이라 가정했을때에 

- 발송예정일
- 도착예정일
- 의류착용일
- 반납택배발송일

이 어떻게 되어야 하나요?

**Comment by pingpongworks** [comment]
위 캡처가 6월1일 오전 11시라고 가정하면

- 발송예정일_6월 1일
- 도착예정일_6월 2일
- 의류착용일_6월 3일
- 반납택배발송일_6월 5일

**Comment by aanoaa** [comment]
탐구생활을 해봤는데 이는 버그입니다.

우체국 택배의 결제마감시간이 14시 이고, 사용자의 현재시각이 `2021-06-01 14` 이전이라고 가정했을때에,
소령님이 적어주신 예상날짜가 맞습니다.

일반 택배의 결제마감시간은 09시 입니다.
배송날짜를 계산하는 부분에서 우체국 택배의 결제마감시간을 일반 택배의 결제마감시간으로 사용했습니다.

이 부분을 수정하면 의도한 대로 동작할 것으로 믿습니다.

**Comment by aanoaa** [comment]
수정해서 배포했습니다.
아직 추석연휴의 영향을 받고 있어서 몇 일 후에 확인할 수 있겠습니다.

**Comment by pingpongworks** [comment]
네~ 며칠 후에 테스트해보겠습니다

**Comment by aanoaa** [comment]
아 며칠이 맞는 표현이군여; 한글 넘 어렵습니다.

**Comment by pingpongworks** [comment]
확인했어요~
