### ISSUE TITLE
우체국 배송 이용가능으로 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#294]
#292 에서 작업했던 우체국 익일발송 불가를 다시 주문가능하도록 요청드립니다. 
다만, 안산지역은 우체국 직원 코로나 확진으로 익일배송이 불가능합니다. 

`우체국 배송 파업 관계로 당분간 이용불가`문구를
`안산지역, 코로나19로 익일배송 불가`로 수정해주시고
우체국 익일발송 기능은 주문가능하도록 되살려주시기 바랍니다.

**Comment by aanoaa** [comment]
복구했습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
