### ISSUE TITLE
안산지역 배송불가 문구 삭제

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#296]
1. 
`안산지역, 코로나19로 익일배송 불가`
안산지역 우체국택배 정상화 되었습니다. 
문구 삭제 요청 드립니다. 

2.
 `서울시 취업날개는 규정상 입사면접 용도로만 이용할 수 있습니다. 대여목적을 입사면접으로 선택하는 경우에만 취업날개 쿠폰 이용이 가능합니다.`
대여목적 하단의 취업날개 안내 문구 삭제요청 드립니다.

**Comment by aanoaa** [comment]
배포되었습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
