### ISSUE TITLE
우체국 익일택배 일부 지역 배송제한 안내문구 삽입

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#299]
<img width="459" alt="스크린샷 2021-07-28 오후 4 54 19" src="https://user-images.githubusercontent.com/17288038/127285549-3954d29b-7349-4a65-8f7b-225a57fa2043.png">

우체국 하계휴가로 위와 같이 우체국 익일택배 신청이 제한됩니다. 

배송방법 선택 중 `우체국 익일택배 `하단에 문구 삽입 부탁드립니다.

문구 삽입 기간 : 오늘 ~ 7월 30일 (금)  오후 2시 

    [집배원 하계휴가로 인한 배송제한 지역] 
    - 서울(강남, 강동, 성북)
    - 경인(인천, 남인천, 서인천, 하남, 평택, 안양, 안산)
    - 전북(전주, 군산)

**Comment by aanoaa** [comment]
![Screenshot_2021-07-29 주문서 작성 · 열린옷장](https://user-images.githubusercontent.com/170528/127346100-bfa241aa-75bd-489e-9a31-db1fa092e5e4.png)

**Comment by aanoaa** [comment]
문구 다시 삭제했습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
