### ISSUE TITLE
의류정보 상세

### ISSUE THREAD

**Issue by yongbin** [opencloset/OpenCloset-Share-Web#3]
![screen shot 2016-05-30 at 4 59 43 pm](https://cloud.githubusercontent.com/assets/52704/15643379/087be6c2-2688-11e6-8cb1-bf5f8ac1d211.png)
![screen shot 2016-05-30 at 4 59 55 pm](https://cloud.githubusercontent.com/assets/52704/15643382/08bba442-2688-11e6-863f-b50a4d9aec96.png)
![screen shot 2016-05-30 at 5 00 04 pm](https://cloud.githubusercontent.com/assets/52704/15643384/08c5ddcc-2688-11e6-9c46-4c1af19cebc2.png)

**Comment by aanoaa** [comment]
의류 사진이 많은데 어떻게 업로드 할지 고민해야 합니다.

**Comment by yongbin** [comment]
기증편지, 감사편지를 처리했던 방식과 비슷하게 열린옷장에서 규칙에 맞춰서 파일을 주면 저희가 자동으로 올리는 방식으로 이야기했습니다.

**Comment by aanoaa** [comment]
`대여하기` 를 누르면 주문서가 만들어지거나 대여를 위한 새로운 화면이 필요합니다.

**Comment by aanoaa** [comment]
궁극적으로는 대여자가 옷을 선택해서 주문하는 방식이 될테지만 아직은 이르다고 생각해서
이 과정없이 진행합니다.

대신 staff 가 주문서를 보고 직접 옷을 고릅니다.
