### ISSUE TITLE
8/16 대체휴무로 인해 택배사 휴무로 착용일 선택 수정이 필요함

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#303]
**1. 우체국 익일발송**
8월 17일, 18일 _착용일 선택 불가
 
**2. 일반 택배**
8월 19일 _착용일 선택 불가

**Comment by aanoaa** [comment]
공휴일로 지정하긴 할건데, 일찍 주문하는 사람의 경우 적어주신 날짜가 착용일이 안될 이유가 없습니다.

**Comment by pingpongworks** [comment]
공휴일로 지정하면 착용일 상관없이 문제가 없긴 하겠네요. 확인했습니다. 감사합니다.
