### ISSUE TITLE
9월 추석연휴 및 10월 대체휴무로 인해 착용일 선택 수정이 필요함

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#304]
_
1. 택배대여

- 일반택배 발송
착용일 선택 불가 기간 : 9/21~9/27

- 우체국 익일발송
착용일 선택 불가 기간 : 9/10-9/28

- 퀵 발송
착용 선택 불가 :  9/18~9/22

_
2. 대체공휴일 휴무일 지정
- 10월 4일
- 10월 11일

**Comment by aanoaa** [comment]
#274 처럼 단순한 요청이 아니네요.
택배사마다의 사정을 고려해서 반영하려면 추가작업이 필요합니다.

**Comment by aanoaa** [comment]
적용했습니다.

**Comment by pingpongworks** [comment]
감사합니다.
