### ISSUE TITLE
주문서 목록_대여자의 코멘트가 있을 때 까맣게 표시 되도록

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#307]
![스크린샷 2021-10-03 오전 1 54 48](https://user-images.githubusercontent.com/17288038/135725626-726bd453-24ba-468a-ba30-f493f54203b6.png)
온라인주문서 '결제완료' 주문서 목록에서 주문서 메모가 있어도 코멘트 표시가 되지 않습니다. 보통 의류나 배송 관련 중요한 내용이 많아 결제완료 목록에서도 코멘트가 있으면 까맣게 표시되도록 수정 부탁드립니다~

**Comment by aanoaa** [comment]
![구매내역-·-열린옷장](https://user-images.githubusercontent.com/170528/144729702-898fff46-9fcc-4825-8a39-d30f86b3d80b.png)

코멘트의 목적이 사용자의 배송요청란이 아니라, 운영자의 배송 코멘트입니다.

배송이 시작되고, 운송장번호가 입력되었을 경우 위 캡쳐화면의 `Comment` 버튼을 눌러서 특이사항을 입력하면 나타나게 됩니다.
이 기능은 활용되지 않는건가요?
사용자의 배송요청이 보여지면 되는건가요?

목록을 살펴보면 2021-11 월에도 활용된 기능입니다.

**Comment by aanoaa** [comment]
상태에 따라 나타나는 코멘트를 달리할 수는 있겠습니다.
결제완료 목록에서는 사용자의 배송요청사항을 표시하고, 발송대기 목록 부터는 운영자의 배송 코멘트를 나타내는 방법입니다.

**Comment by aanoaa** [comment]
임의로 결제완료 목록에서는 사용자의 배송요청사항을 표시하고, 발송대기 목록 부터는 운영자의 배송 코멘트를 나타내도록 했습니다.

**Comment by pingpongworks** [comment]
스태프가 일할 때 도움 될 거 같습니다. 잘 처리해주셔서 감사합니다. 담당자에게 원하는 결과가 맞는지 확인 후 이슈 닫겠습니다.

**Comment by pingpongworks** [comment]
온라인팀에서 원하는건 결제완료 상태에서 `주문서메모`에 내용이 있을 때 까맣게 표기가 되는 겁니다. 대여자가 주문 후에 전화나 카톡으로 추가요청하는 내용들이 꽤 있는데 주문서메모에 적어놓기 때문에 그 내용을 놓치지 않으려고 하는 겁니다.

**Comment by aanoaa** [comment]
주문서 메모가 뭔지 모르겠습니다.

**Comment by pingpongworks** [comment]
<img width="1154" alt="스크린샷 2021-12-06 오전 9 40 54" src="https://user-images.githubusercontent.com/17288038/144770853-e908ad75-22ad-4525-8160-cd49e6e2d69c.png">
대여 주문서 하단에 있는 주문서메모가 `주문서메모`입니다.

**Comment by pingpongworks** [comment]
- 결제완료 상태에서 대여자의 배송요청사항
- 발송대기 상태에서 운영자의 배송 코멘트
- 결제완료 상태에서 운영자의 주문서 메모

3가지 상태 모두 코멘트 블랙표기 되는게 좋을지 담당자에게 확인한 후 다시 작업 요청하겠습니다.

**Comment by aanoaa** [comment]
결제완료 상태에서 배송주문서 목록의 코멘트가 staff 의 "주문서 메모" 로 보이도록 변경했습니다.

**Comment by pingpongworks** [comment]
네, 일단 사용해볼게요. 감사합니다.
