### ISSUE TITLE
택배대여사이트 푸터 수정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#318]
![스크린샷 2022-01-07 오후 2 17 32](https://user-images.githubusercontent.com/17288038/148496057-2105591b-9a59-4f50-ab1c-86359bab6ec7.png)

현 시점에서 필요없는 내용, 잘못된 연결된 페이지 들이 있어서 빠른 수정요청드립니다. 

1. 방문예약
누르면 내부 수지니 페이지로 연결됩니다. 
방문예약 페이지로 연결되도록 수정 해주세요.
https://visit.theopencloset.net/visit

2. 온라인예약 => `택배주문 `으로 수정해주세요.

3. contact
트위터, 인스타, 페북 모두 삭제하고 메인홈페이지 하단의 `톡상담` 처럼 카카오톡 문의로 연결되도록 해주세요. 택배대여 주문과정에서 문제가 생겼을 경우 문의하기가 어렵다는 이용자들 피드백이 있어 수정하려고 합니다. 
http://pf.kakao.com/_xaxcxotE

![스크린샷 2022-01-07 오후 2 28 05](https://user-images.githubusercontent.com/17288038/148496639-8a890312-3dac-419b-8a14-1e5ff93ae18d.png)

**Comment by aanoaa** [comment]
https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-Plugin-Helpers-v0.0.33.tar.gz 에서 footer 를 변경하고 적용했습니다.

**Comment by pingpongworks** [comment]
감사합니다~
