### ISSUE TITLE
2022 설 연휴 동안 택배대여 신청을 할 수 없게 함

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#319]
택배 발송이 가능한 날짜를 고려헀을 때 설연휴를 전후하여
다음의 날짜가 의류착용일인 경우 배송을 할 수 없습니다.
의류 착용일을 누를 수 없게 하여
주문이 되지 않게 작업 요청드립니다.

1. 일반택배 
    착용일 기준 1/28(금) ~ 2/7(월) 선택 불가

2. 우체국 익일배송 
    착용일 기준 1/25(화)~2/8(화) 선택 불가 

3. 퀵 발송
    1/28(금) 2시 마감
    착용일 기준 1/31~2/2

**Comment by aanoaa** [comment]
반영하였습니다.

**Comment by pingpongworks** [comment]
감사합니다~
