### ISSUE TITLE
email 찾기와 비밀번호 재설정

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#32]
이용했던 적은 있지만 email 이 기억나지 않는 사용자를 위한 기능

**Comment by 10001if** [comment]
네, 얼마 전에 이메일이 기억나지 않는다고 연락이 왔었습니다. 기능이 필요합니다.

**Comment by aanoaa** [comment]
로그인을 staff.theopencloset.net 에서 하다보니 발생하는 문제입니다.
보다 친절한 비밀번호 찾기 기능이 필요합니다.

**Comment by aanoaa** [comment]
이름과 폰번호를 입력하게 하고 일치한다면 email 을 보여주도록 하는 방법이 있습니다.

**Comment by aanoaa** [comment]
![2017-05-09 11-06-41](https://cloud.githubusercontent.com/assets/170528/25832823/05207216-34a8-11e7-95d5-7cf5873631be.png)

**Comment by pingpongworks** [comment]
매우 편해졌네요. 감사합니다~
