### ISSUE TITLE
코트, 가방 대여품목 추가

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#321]
코트와 가방이 대여품목에 추가됨에 따라 사이트에 반영 요청드립니다.

_
1. 대여가격 안내, 표로 수정해주세요.
<img width="807" alt="스크린샷 2022-02-23 오후 3 02 31" src="https://user-images.githubusercontent.com/17288038/155268940-dba1e64d-5a30-4550-a438-4332e5bccb8b.png">

대여가격 안내 (3박 4일 기준)
| 품목                   | 가격        |
|--------------- |---------|
| 자켓,팬츠,스커트 | 10,000원  |
| 겨울용 코트         | 10,000원  |
| 셔츠, 블라우스     | 5,000원  |
| 구두, 가방           | 5,000원   |
| 타이, 벨트           | 2,000원   |
* 택배 발송비 3,000원입니다.
* 정장세트를 대여하는 경우, 타이는 무료입니다. 

_
2. 대여품목, 추가해주세요.
<img width="502" alt="스크린샷 2022-02-23 오후 3 11 42" src="https://user-images.githubusercontent.com/17288038/155270327-e996cd83-b052-4c4a-b933-511fa5ac8535.png">

_
3. 대여내역 이미지 교체 및 추가해주세요.
![가방](https://user-images.githubusercontent.com/17288038/155270551-2c335504-f39c-4c86-9cc0-400669ea15f8.png)
![구두](https://user-images.githubusercontent.com/17288038/155270554-21af111e-a599-423f-8d8b-d9c06eedbecc.png)
![넥타이](https://user-images.githubusercontent.com/17288038/155270556-d5a2047f-a44d-4bbe-989c-a58563867884.png)
![바지](https://user-images.githubusercontent.com/17288038/155270559-ffa905e9-13db-4f86-9958-8533b6877378.png)
![벨트](https://user-images.githubusercontent.com/17288038/155270561-b0120430-a591-4bde-948d-4fb145578b42.png)
![블라우스](https://user-images.githubusercontent.com/17288038/155270563-d971e27c-5167-4a4f-98df-5d2f98e80cf4.png)
![셔츠](https://user-images.githubusercontent.com/17288038/155270564-3fa3aa22-4e2b-4036-bf40-1e1ae827002f.png)
![자켓](https://user-images.githubusercontent.com/17288038/155270566-41af192d-31c6-4c48-9273-b6869b38b462.png)
![치마](https://user-images.githubusercontent.com/17288038/155270572-7c42c5c0-a861-4cca-b05f-cea275880a2d.png)
![코트](https://user-images.githubusercontent.com/17288038/155270574-53915f27-cce9-43b1-b121-34e7e30288d6.png)

**Comment by pingpongworks** [comment]
3월 2일에 쿠폰 전달하고 이용가능하도록 
3월 1일까지 작업 요청드립니다.

**Comment by aanoaa** [comment]
이미지 교체를 위해서 oavatar 의 이미지를 교체합니다.

    token=$token
    for category in bag shoes tie pants belt blouse shirt jacket skirt coat; do
        curl -F "token=$token" -F "key=$category" -F "img=@$category.png" https://avatar.theopencloset.net/avatar
    done

**Comment by aanoaa** [comment]
이미지는 업로드 했는데 예전 이미지가 여전히 노출됩니다.
같은 key 에 대해 여러장의 사진을 올릴 수 있습니다.
default 이미지를 변경하거나 rating 으로 노출되는 이미지의 priority 를 조절해줄 수 있을 것 같습니다.

**Comment by aanoaa** [comment]
각각의 추가된 이미지의 rating 을 변경해서 최근 이미지가 default 로 노출되도록 변경했습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
