### ISSUE TITLE
3/9 대선일 공휴일로 설정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#323]
3월 9일 (수) 대통령선거일을 공휴일로 지정하여 주문시 고려되도록 요청드립니다.

**Comment by pingpongworks** [comment]
3월 9일 발송 주문이 들어오지 않도록 
2월 28일까지 작업부탁드립니다.

**Comment by aanoaa** [comment]
작업됐습니다.
의류착용일은 미리 보내는 거라서 영향이 없고,
3/9 이후 날짜에 대해서 발송예정일이 3/9 일로 지정되지 않습니다.

**Comment by pingpongworks** [comment]
확인했습니다. 감사합니다.
