### ISSUE TITLE
4월 11일, 2시 이전 당일퀵발송/우체국익일발송 주문 제한

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#329]
월요일 오후에 전직원 참여 행사가 있어서 당일퀵/우체국 발송을 할 수 없습니다. 
주문 제한 설정을 요청드립니다.

- 제한일시 : 4월 11일 (월) 오전 9:00 - 14:00  (2시 이후는 원래 주문 안됨)
- 제한대상 : 당일 퀵발송 / 우체국 익일 발송

**Comment by aanoaa** [comment]
적용했습니다.

**Comment by pingpongworks** [comment]
감사합니다~

**Comment by aanoaa** [comment]
우체국 익일 발송은 빼먹고 안해서 지금 적용했습니다.
