### ISSUE TITLE
일반택배, 우체국 익일배송 : 광복절 연휴 택배없는 날 주문 제한 설정 

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#336]
8월 13일 (토) 택배없는 날
    8월 16일 (화) 하계휴가

**1. 일반 택배**
8월 17일 (수) ~ 8월 19일 (금)까지 착용일 선택 불가

**2. 우체국 익일배송**
8월 17일 (수) ~ 8월 18일 (목)까지 착용일 선택 불가

위와 같이 작업 부탁드립니다.

**Comment by aanoaa** [comment]
적용하였습니다.

**Comment by pingpongworks** [comment]
감사합니다.

**Comment by pingpongworks** [comment]
제가 요청을 잘 못했습니다. 
착용일을 제한하면 대여자들이 착용일 선택 오류로 잘못 이해할 거 같아요. 

착용일 선택 제한이 아니라
8월 16일 (화)를 공휴일로 지정 부탁드립니다.

**Comment by aanoaa** [comment]
적용했습니다.

**Comment by pingpongworks** [comment]
감사합니다~
