### ISSUE TITLE
택배없는 날 공휴일 지정

### ISSUE THREAD

**Issue by pingpongworks** [opencloset/OpenCloset-Share-Web#356]
8월 14일이 택배없는 날로 모든 택배노동자가 쉽니다. 

8월 13일 (화) ~ 8월 15일 (목)까지 공휴일로 지정해서 주문시 고려되도록 요청드립니다. 
8월 15일은 이미 공휴일로 지정되어 있을거라 13~14일 양일을 공휴일로 지정해주시면 됩니다. 

(이 기간에는 기증반송도 어려우므로 기증반송일로 설정할 수 없도록 함께 요청드립니다.

**Comment by yongbin** [comment]
8월 13,14일 양일 적용완료했습니다.

**Comment by pingpongworks** [comment]
확인했습니다.감사합니다~
