### ISSUE TITLE
추천 대여 목록의 색상별 정렬

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#39]

**Comment by aanoaa** [comment]
@yongbin 이 이슈가 해결되려면 추천의류검색을 색상별로 할 수 있도록 하거나, 결과에 색상을 포함하여 주어야 하겠습니다.

현재의 검색결과에서 일일이 색상을 검색해서 재배치 할 수도 있긴 합니다.

**Comment by yongbin** [comment]
확인해보니 `search_clothes` 함수가 현재 의류의 정렬은 지원하고 있지만 ( https://github.com/opencloset/opencloset/issues/886 ) `order.pre_color`를 보는것이 아니라 `user_info.pre_color`을 확인해서 검색옵션으로 사용하기때문에 원하는 결과가 나오지 않습니다. 이 부분을 수정해야합니다.

**Comment by yongbin** [comment]
생각해보면 `monitor`에서도 이미 주문서가 확정된 상태에서 검색을 하기 때문에 `user_id`가 아니라 `order_id`로 검색해도 문제가 없습니다. 다만, 현재 staff 에서 제공하는 `사용자` 하부 `의류검색` (user/:id/search/clothes/)의 경우 주문서가 없는 상태에서의 검색으로 특수한 경우에 해당합니다.
