### ISSUE TITLE
치수측정 안내 및 입력

### ISSUE THREAD

**Issue by yongbin** [opencloset/OpenCloset-Share-Web#4]
![screen shot 2016-05-30 at 5 01 51 pm](https://cloud.githubusercontent.com/assets/52704/15643424/3c779c46-2688-11e6-8bd4-0040e638bd9b.png)

**Comment by aanoaa** [comment]
동영상은 추가정보라고 생각합니다.
글과 그림으로써 어떻게 치수를 측정하는지 설명할 수 있어야 합니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/OpenCloset-Share-Web/issues/5#issuecomment-228259764

의 고민이 이어집니다.

- 재고관리의 API 를 이용
- 모듈화
- 새로 만든다

새로 만드는 건 아닌것 같고, 새로 만든다면 재고관리에서도 새로만든 API 를 사용해야 하겠죠.
재고관리 API 를 보강하면서 이용하는게 제일 좋지 않을까 합니다.

물론 재고관리 API 에서 기능을 모듈화해서 사용한다면 최고입니다.


답은 나왔습니다.

**재고관리 API 의 보강해서 사용한다**

지금은 콘트롤러 혹은 helper 에 구현되어 있는데, 이것을 모듈화하면서 기능을 보강(테스트추가?)


`api.theopencloset.net` 같을 걸 꿈꿨는데 묻어두도록 합니다.

**Comment by aanoaa** [comment]
바지길이나 배꼽둘레는 흔히 쓰이지 않아서 어려울 수 있습니다.

위에 했던 말인데, 각 부위/명칭 별로

>  글과 그림으로써 어떻게 치수를 측정하는지 설명할 수 있어야 합니다.

cc @10001if

**Comment by aanoaa** [comment]
@10001if
대여를 위해 최소한으로 필요한 치수를 남성, 여성 별로 남겨주세요.

**Comment by 10001if** [comment]
남성 | 여성 
----- | -----
가슴둘레 | 가슴둘레
윗배둘레 | 윗배둘레
팔길이 | 팔길이
허리둘레 | 허벅지둘레
허벅지둘레 | 엉덩이둘레
다리길이 | 무릎길이

**Comment by 10001if** [comment]
@aanoaa 확인 부탁드릴게요 ^^

**Comment by aanoaa** [comment]
@10001if 키, 몸무게는요? 이것도 필요하겠죠?

**Comment by aanoaa** [comment]
사용자가 입력하게 될 치수인데 윗배둘레, 다리길이등을 재나요?

**Comment by aanoaa** [comment]
정확하면 좋겠지만 요구하는게 많아지면 불편할 수도 있을 것 같습니다.

**Comment by aanoaa** [comment]
추천의류의 검색결과와 관련이 있습니다.
@yongbin 필요한 최소한의 신체치수를 알려주세요.

**Comment by yongbin** [comment]
예측이 기존 오프라인에서 신체치수 측정한것을 최대한 활용해서 사용하기 때문에 최소한 필요한 신체치수가 기존 오프라인에서 측정하고 있는(위 한만일 대표님이 적어주신) 목록과 동일합니다.

**Comment by aanoaa** [comment]
http://www.competitivecyclist.com/Store/catalog/fitCalculatorBike.jsp?INT_ID=IB12809#type

사이즈 측정에 대한 훌륭한 안내입니다.

**Comment by aanoaa** [comment]
가이드가 될만한 그림이나 사진이 있으면 좋겠지만, 준비가 될때까지 패스합니다.

- 허리둘레: 배꼽기준의 둘레
- 윗배둘레: 가장 볼록한 배의 둘레
- 팔길이: 중지 끝 부터 어깨관절 까지의 길이
- 허벅지 둘레: 허벅지의 가장 두꺼운 부분의 둘레
- 다리길이: 발바닥부터 골반뼈까지의 길이

위는 제가 임의로 정한 이해를 돕기 위한 팁입니다.
@10001if 틀리거나 맘에 들지 않는게 있다면 고쳐주세요.

**Comment by aanoaa** [comment]
@10001if 위 코멘트의 대한 내용을 검토해주세요

**Comment by 10001if** [comment]
> 허리둘레: 배꼽기준의 둘레

-> 허리둘레 : 바지를 입는 부분의 둘레 / (바지를 입지 않는다면) 골반뼈 윗부분의 둘레

> 윗배둘레: 가장 볼록한 배의 둘레

-> 윗배둘레: 배꼽 7cm 윗부분의 둘레

>팔길이: 중지 끝 부터 어깨관절 까지의 길이

-> 팔길이: 어깨뼈부터 손목뼈까지의 길이

>허벅지 둘레: 허벅지의 가장 두꺼운 부분의 둘레

>다리길이: 발바닥부터 골반뼈까지의 길이

@aanoaa 수정 부탁드립니다. ^^

**Comment by aanoaa** [comment]
ad2a63c470b8419b5214dd131b43782dfffac290

**Comment by aanoaa** [comment]
사용자의 신체치수를 저장하기 위해서 staff 의 api 를 호출합니다.
그런데 로그인된 사용자가 staff 이 아니라면 api 를 호출할 권한이 없어서 신체치수 변경을 할
수 없게 됩니다.

api 호출대신에 직접 수정하도록 변경해야 하겠습니다.

**Comment by aanoaa** [comment]
화면을 반으로 잘라서 http://opencloset1.godo.co.kr/shop/main/html.php?htmid=proc/body_size.htm
이 비디오를 삽입해야 합니다.

**Comment by aanoaa** [comment]
한방에 입력하는 것이 아니라, 신체부위를 하나씩 입력할 수 있도록 하고 입력해야 다음 신체부위를 입력할 수 있도록 해야 합니다.

**Comment by aanoaa** [comment]
처음 코멘트의 미리보기 처럼요

**Comment by 10001if** [comment]
신체 치수 텍스트 정보 수정 요청드립니다.

<신체 치수 측정 가이드>
※ 사이즈 측정 시 줄자를 조이는 정도는 줄자가 신체에 밀착되는 정도로
    너무 느슨하거나 꽉 조여서 측정하지 않는다.

목 둘레
-목과 어깨가 이어지는 라인(목의 가장 아랫 부분)에 줄자가
자연스럽게 걸칠정도로 둘레를 측정한다.

가슴 둘레
- 남자 : 양팔을 들어올린 후 줄자를 겨드랑이 가장 윗부분에 끼운 후 
양팔을 내린다. 
- 여자 : 가슴의 가장 두꺼운 부분(BP점)의 둘레를 수평으로 측정한다. *BP점-BUST POINT

배꼽 둘레
- 배꼽이 있는 위치에서 수평으로 둘레를 측정한다.

윗배 둘레
-배꼽 위치에서 6CM(보통의 경우 남성의 경우 손가락 3개, 여성의 경우 4개)에서 수평으로 둘레를 측정한다.

허리 둘레 
- 골반의 위치를 확인한 후 골반 바로 윗 부분의 둘레를 측정한다.

팔길이
- 팔을 가볍게 내린 상태에서 어깨뼈가 가장 톡 튀어나온 부분부터 손목 접히는 부분(손목뼈)까지 측정한다.

엉덩이 둘레
- 엉덩이의 가장 튀어나온 부분을 수평으로 측정한다.

허벅지 둘레
- 가랑이 가장 위까지 줄자를 올린 후 수평으로 둘레를 측정한다.

무릎 길이
- 허리 둘레를 측정한 위치(골반 바로 윗부분)부터 무릎뼈 바로 위까지의 길이를 측정한다.

다리 길이
-허리 둘레를 측정한 위치(골반 바로 윗부분)부터 발바닥이 지면에 닿는 길이까지 측정한다.

**Comment by 10001if** [comment]
신체치수 측정에 필요한 사진 공유드립니다.

![default](https://cloud.githubusercontent.com/assets/4696328/22616328/b0114b9a-eaee-11e6-9b9b-f6bccc9704f8.JPG)
![default](https://cloud.githubusercontent.com/assets/4696328/22616329/b016c8a4-eaee-11e6-940b-f0709ff0f03e.JPG)
![default](https://cloud.githubusercontent.com/assets/4696328/22616331/b01c1d9a-eaee-11e6-8972-2547b0dcabfb.JPG)
![default](https://cloud.githubusercontent.com/assets/4696328/22616332/b01db0f6-eaee-11e6-9d0b-b3afb39710fc.JPG)
![default](https://cloud.githubusercontent.com/assets/4696328/22616330/b01b99b0-eaee-11e6-83f6-260cca0164d3.JPG)
![default](https://cloud.githubusercontent.com/assets/4696328/22616333/b0200aae-eaee-11e6-9d01-8e102154d288.JPG)
![default](https://cloud.githubusercontent.com/assets/4696328/22616334/b04141c4-eaee-11e6-8ab2-97b3892257ed.jpg)
![default](https://cloud.githubusercontent.com/assets/4696328/22616335/b0430f40-eaee-11e6-8f84-b46184c0e7c6.JPG)
![default](https://cloud.githubusercontent.com/assets/4696328/22616336/b0456a6a-eaee-11e6-82c3-d2dff20baa08.JPG)
![default](https://cloud.githubusercontent.com/assets/4696328/22616337/b047d8fe-eaee-11e6-92be-300cd70a27bb.JPG)

**Comment by 10001if** [comment]
@aanoaa 메일로도 보내드리겠습니다.

**Comment by 10001if** [comment]
동영상 자료는 http://opencloset1.godo.co.kr/shop/main/html.php?htmid=proc/body_size.htm에서 확인 가능합니다.

**Comment by aanoaa** [comment]
동영상은 어디에 어떻게 넣는 것이 좋을까요?
위 이미지는 반영하였습니다.

**Comment by 10001if** [comment]
@aanoaa http://www.competitivecyclist.com/Store/catalog/fitCalculatorBike.jsp?INT_ID=IB12809#type 훌륭한 방식을 따라하면 어떨까 싶습니다.

**Comment by 10001if** [comment]
동일하게 진행되어도 무리가 없을 것 같습니다.

**Comment by 10001if** [comment]
사진과 동영상이 다르다는 문제가 있네요. 그 부분은 동영상에서 촬영 부분을 캠쳐하여 사용하여도 될 것 같습니다..

**Comment by aanoaa** [comment]
위 링크에서 동영상이 제공되는 부위는 적용하였습니다.

**Comment by aanoaa** [comment]
설명이 반영되어야 합니다.
레이아웃도 변경되어야 합니다.

**Comment by 10001if** [comment]
구두사이즈 설명 추가 요청드립니다. 

구두사이즈
본인의 구두사이즈를 알고 있지 않을 경우, 평소 신는 운동화 사이즈보다 5mm 작게 기입한다

**Comment by aanoaa** [comment]
밑줄이 노란색바탕으로 되어야 합니다.

**Comment by aanoaa** [comment]
> 배꼽 위치에서 6CM(보통의 경우 남성의 경우 손가락 3개, 여성의 경우 4개)에서 수평으로 둘레를 측정한다.

아래와 같이 바뀌어야 합니다.

배꼽 위치에서 6CM(보통의 경우 남성의 경우 손가락 3개, 여성의 경우 4개)위의 둘레를 수평으로 측정한다.
