### ISSUE TITLE
거래내역을 저장

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#40]
결제와 관련된 거래시도 및 결과를 저장해두는 것이 여러모로 유리할 것 같습니다.
결제할때에 결제액을 비교해야 하고, id 를 가지고 거래내역을 조회할 수도 있습니다.

우선 테이블이 추가되어야 할 것 같습니다.

**Comment by aanoaa** [comment]
payment_history

- id
- merchant_uid
- amount
- create_date
- status: paid, ready, cancel, fail

------------------------

상태가 업데이트 되는 것이 아니라 매번 insert 해주면 어떻게 진행되었는지 추적하기가 더 좋을 것 같습니다.

**Comment by aanoaa** [comment]
@yongbin 더 필요할 것으로 여겨지거나 의견이 있다면 말씀해주세요.

**Comment by yongbin** [comment]
이 대목부터는 @keedi 님도 도움을 주셔야 합니다. 소환

**Comment by keedi** [comment]
iamport에서 돌려받는 id도 저장해야 할 것 같습니다. 일단 생각나는것 부터...

**Comment by aanoaa** [comment]
iamport 조회했을때의 샘플입니다.

```
      {
        "amount": 100,
        "apply_num": null,
        "buyer_addr": "서울 광진구 화양동 xxxx",
        "buyer_email": "xxx@gmail.com",
        "buyer_name": "xxx",
        "buyer_postcode": "143-193",
        "buyer_tel": "010-xxxx-xxxx",
        "cancel_amount": 0,
        "cancel_reason": null,
        "cancel_receipt_urls": [ ],
        "cancelled_at": 0,
        "card_name": null,
        "card_quota": 0,
        "currency": "KRW",
        "custom_data": null,
        "escrow": false,
        "fail_reason": "F0004:PG사 결제요청에 실패하여 중단합니다(imp_092684221544) 결제모듈 재설치필요:",
        "failed_at": 1478732906,
        "imp_uid": "imp_092684221544",
        "merchant_uid": "merchant_1478732608219",
        "name": "주문명:test#1",
        "paid_at": 0,
        "pay_method": "trans",
        "pg_provider": "html5_inicis",
        "pg_tid": null,
        "receipt_url": "https://iniweb.inicis.com/DefaultWebApp/mall/cr/cm/mCmReceipt_head.jsp?noTid=&noMethod=1",
        "status": "failed",
        "user_agent": "sorry_not_supported_anymore",
        "vbank_date": 0,
        "vbank_holder": null,
        "vbank_name": null,
        "vbank_num": null
      },
```

**Comment by yongbin** [comment]
하나의 `order_id`에 여러번 결제시도를 할테니까 복수의 레코드가 쌓이겠네요 `update`안하고  `insert`만 사용하는건 저도 찬성입니다.

**Comment by yongbin** [comment]
`buyer_*` 는 순전히 PG쪽이나 아임포트 UI상으로 대략 확인하기 편하기 위해서 전달하는거고 원 자료가 저희디비기 때문에 따로 저장할 필요 없습니다.

**Comment by aanoaa** [comment]
`imp_uid` 는 고유한 값이기 때문에 변경되지 않습니다.
열린옷장계정이 하나의 값을 갖습니다.
관리페이지에서 확인할 수 있습니다.

**Comment by keedi** [comment]
`merchant_uid` 는 `cid` (클라이언트id)로, `imp_uid`는 `sid`(서버id)로 컬럼 변경해서 저장했으면 하고, 반환 결과는 json을 통채로 저장하는 컬럼을 만들어서 통째로 저장하고 어플리케이션에서 json decode해서 썼으면 합니다. 추가로 `vendor`(가칭) 컬럼을 추가하고 일단은 `iamport-html5_inicis`로 넣으면 좋을 것 같습니다.

**Comment by yongbin** [comment]
> imp_uid 는 고유한 값이기 때문에 변경되지 않습니다.

형석님 말한값은 imp_uid가 아니라 imp로 시작하는 *가맹점식별번호* 입니다. imp_uid는 import 서버에서 부여하는 거래 식별자로 매번 바뀝니다.

**Comment by aanoaa** [comment]
> 형석님 말한값은 imp_uid가 아니라 imp로 시작하는 가맹점식별번호 입니다. imp_uid는 import 서버에서 부여하는 거래 식별자로 매번 바뀝니다.

@yongbin `merchant_uid` 아닌가여?

**Comment by keedi** [comment]
추가로 결제 타입을 지정할 수 있는 컬럼 `paid_by` (가칭)를 추가해서 vbank인지 card인지 등을 기입했으면 합니다. json에 해당 정보가 들어있는가는 별개로요

**Comment by keedi** [comment]
@aanoaa merchant_uid와 imp_uid가 1:1대응이라고 보시면 될겁니다.

**Comment by aanoaa** [comment]
https://api.iamport.kr/#!/payments/getAllPaymentsByMerchantUid 에서 보면,

> 동일한 merchant_uid가 여러 건 존재할 수 있으므로 해당되는 모든 내역을 반환합니다.

라고 되어있습니다.

`merchant_uid` 는 중복될 수 있는데, `imp_uid+merchant_uid` 라고해서 중복이 되지 않을지는 모르겠습니다.

**Comment by keedi** [comment]
> iamport 조회했을때의 샘플입니다.
> 
> ```
>       {
>           ...
>         "imp_uid": "imp_092684221544",
>         "merchant_uid": "merchant_1478732608219",
>           ...
>       },
> ```

상기 두 정보가 쌍이라는 의미지요. 물론 `merchant_uid`는 우리가 지정해서 보내니까 iamport 쪽에서는 유니크함을 보장하지는 않겠죠. `merchant_uid` 책임은 우리가 지는셈입니다. 정리하면 `merchant_uid`를 유니크하게 관리할 책임은 우리쪽에 있고 iamport는 단지 받은 값을 그대로 돌려줄 뿐이라고 보면됩니다. 우리쪽에서는 imp_uid + merchant_uid 를 하는게(더하는게) 아니고 그냥 merchant_uid 랑 imp_uid랑 같은 의미다. 단 전제 조건은 우리가 유니크하게 유지한다. 그 정도로 보시면 될것 같습니다.

**Comment by yongbin** [comment]
넵 저희도 `merchant_uid`를 유니크하게 관리해야합니다.

**Comment by yongbin** [comment]
다시 본론으로 돌아와서 저장된 거래내역은 결국 정산등에서 활용될 가능성이 높습니다. 여기서 고려해봐야하는건 대부분의 정상적인 결제는 문제가 없겠지만 결제 취소발생 상황 혹은 지금은 지원계획이 없지만 부분취소가 발생한 상황등을 고려해서 생각해봐야 합니다.

**Comment by aanoaa** [comment]
가맹점 식별코드는 거래할때에 사용되지 않는군요.
`imp_` 로 시작해서 헛갈렸습니다.

`imp_uid`, `merchant_uid` 모두 저장하는게 맞습니다.

하지만 결제 준비 단계에서는 `imp_uid` 를 알 수 없고 `merchant_uid` 만 알 수 있습니다.
`imp_uid` 가 비어 있는 행이 있어도 될까요?

**Comment by aanoaa** [comment]
전체취소만 고려합니다.

**Comment by yongbin** [comment]
> 하지만 결제 준비 단계에서는 imp_uid 를 알 수 없고 merchant_uid 만 알 수 있습니다.
> imp_uid 가 비어 있는 행이 있어도 될까요?

네 `imp_uid`가 비어있고 결제시도단계의 기록을 보관하면 *결제시도 하다가 실패*한 거래들도 알수 있으니까 유용할거 같습니다. 추가적으로 사용자가 사용한 장비 환경이나 브라우져 버전 같은 내용도 저장하면 거래실패하는 상황들에 대해서 파악하기 좋을것 같습니다.



> 전체취소만 고려합니다.

찬성

**Comment by aanoaa** [comment]
`payment_history`

- id
- order_id
- imp_uid(sid)
- merchant_uid(cid)
- amount
- status
  - paid
  - ready
  - cancel
  - fail
- vendor
  - iamport-html5_inicis
  - ...
- pay_method(paid_by?)
  - vbank
  - card
  - ...
- json
- create_date

--------------------------

대충 그림은 나왔습니다.
더 자세한 내용은 schema 이슈에서 다루도록 하겠습니다.

**Comment by aanoaa** [comment]
#10 을 해결하기 위해 먼저 처리되어야 합니다.

**Comment by keedi** [comment]
`status`에 `paid`, `ready`, `cancel`, `fail` 등이 들어가는 것은 확인했습니다. 

> aanoaa commented 6 days ago • edited
> ... 
> 상태가 업데이트 되는 것이 아니라 매번 insert 해주면 어떻게 진행되었는지 추적하기가 더 좋을 것 같습니다.

이런 언급이 있는데 그러면 현재 테이블은 한번 데이터가 들어가면 업데이트 없고 계속 `status` 값만 바뀐 자료가 추가만 되는 것 맞는지요?

**Comment by keedi** [comment]
`payment_history.status` 값을 포함해 모든 값은 한번 들어가면 그대로 두고 `status`가 바뀔 경우 새로운 항목을 추가한다고 합니다. 그렇다고 하면 테이블을 2개로 나누는 것이 나을 것 같습니다. `status`와 `json`(현재 스키마 상은 `dump`로 되어있긴한데)를 별도 테이블로 분리하고 `payment_history.id`, `create_date` 도 추가하면 될 듯합니다.  코드 살펴보고 수정할 수 있으면 수정해보겠습니다.

**Comment by keedi** [comment]
더불어 hook에게 결과를 받은 다음 바로 payment_history에 지금은 바로 `ready`나 `paid`를 추가해주고 있는데 이것은 현재 paid, ready, cancel, fail 과 별개로 `hooked`와 같은 상태를 하나 추가해서 상태를 갱신시키고 별도의 워커를 돌려서 해당 워커에서 hooked인 항목은 api 요청을 통해 진짜 결과를 확인한 다음 워커에서 상태를 갱신 시켜야 하지 않을까 싶습니다. 훅의 경우 별도의 인증이 있는 것도 아니고, 위조가 손쉬운 관계로 알림 정도로만 생각하고 실제 상태 변경은 우리측에서 다시 요청을 보내야 할 것 같습니다.

**Comment by keedi** [comment]
선호하시거나 사용하려는 워크가 있으신지요?

**Comment by aanoaa** [comment]
iamport 로 부터는 항상 상태를 받습니다.

- paid
- failed
- ready
- cancelled

iamport 와의 트랜잭션이후에 payment_history 가 추가되는 것인데 임의의 상태를 추가하는건 어렵지 않을까요?
