### ISSUE TITLE
열린옷장 공식 로고 사용

### ISSUE THREAD

**Issue by keedi** [opencloset/OpenCloset-Share-Web#45]
story 에서 사용하던 열린옷장 공식 로고를 사용하면 될 것 같습니다.

제가 처리하겠습니다.

**Comment by keedi** [comment]
화면이 단순하기 때문에 네비게이션 바가 조금 더 두꺼우면 좋을 것 같습니다만, 최대한 기본 디자인을 수정하지 않는 범위에서 로고를 추가했습니다.

![screenshot-monster silex kr 10306 2017-01-26 05-36-08](https://cloud.githubusercontent.com/assets/138451/22308225/727e3bec-e389-11e6-93df-a792121ee3f1.png)

**Comment by keedi** [comment]
이슈 닫습니다.

**Comment by aanoaa** [comment]
`png` 파일이 없어요
