### ISSUE TITLE
훅 요청을 받은 뒤 pg사에 해당 결제의 내역을 확인

### ISSUE THREAD

**Issue by keedi** [opencloset/OpenCloset-Share-Web#49]
현재는 훅요청을 받은 뒤 훅 요청에 있는 정보를 그대로 신뢰하고 있습니다. 하지만 결제 관련인 만큼 정확하게 짚고 넘어가기 위해 pg 사에 다시 요청을 보내서 결과를 확인한 후 결제 상태를 변경하도록 합니다.

**Comment by aanoaa** [comment]
$ perldoc Iamport::REST::Client

`payment($imp_uid)` 메소드를 사용하면 될 것 같습니다.

**Comment by keedi** [comment]
일단은 내부적으로 오류가있거나 예상한 것과 결제 상태가 다른 경우 어떻게 할지 결정한 바가 없으므로 로그를 통해 기록만 남기는 방향으로 진행합니다. 예상되는 문제 포인트에 모두 분기문과 함께 오류메시지를 출력하도록 했으며 추가로 `FIXME` 태그를 달았으니 다시 진지하게 논의한 후 어찌 처리하는 것이 좋을지 결정하도록 합니다.

우선 요청을 보내고 결과값을 바탕으로 로그를 찍어주는 부분을 제외하면 동작 자체는 기존과 동일합니다. 조건문에서 분기는 하지만 취소를 한다던가 등의 추가 작업은 아직까지는 없습니다.

**Comment by keedi** [comment]
동작에 크게 영향은 주지 않으리라 생각합니다만, #51 이슈와 동시에 처리한 관계로 최종 테스트가 필요합니다.
