### ISSUE TITLE
서비스 소개 및 안내

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#5]
정장대여소개 · 열린옷장

    https://share.theopencloset.net/welcome/

로그인 하지 않은 첫방문자가 보게 될 화면 입니다.

**Comment by aanoaa** [comment]
사용자를 추가할때에 재고관리 서비스의 API 를 이용해야 할까요?
모듈화해서 사용한다면 모를까 따로 만들어야 한다면 가입경로가 두개가
되어버려서 데이터 관리가 힘들고 오류가 발생할 여지도 있습니다.

**Comment by aanoaa** [comment]
@10001if 
첫방문자를 위한 소개 및 안내에 대한 내용이 필요합니다.
이건 제 생각이고요, 생각하신게 있으면 말씀해주세요.

**Comment by 10001if** [comment]
@aanoaa 아직 명확하게 생각한 것은 없지만, 소개나 안내 내용은 전달해드리도록 하겠습니다~

**Comment by aanoaa** [comment]
서비스의 이용절차

1. 회원가입 및 로그인
  - 휴대폰 본인인증
2. 치수측정 안내 및 치수입력
3. 대여품목 카테고리 및 색상 수량 선택
4. 주소록 관리 및 배송될 주소의 선택
5. 결제 안내 및 결제
6. 배송상태에 따른 후처리 <- 어떠한 후처리?
7. 사진 업로드 안내

회원가입 없이도 이용할 수 있어야 합니다.
비회원과 회원의 다른 점이라면 비밀번호를 설정 하지 않는 정도?
이고 회원은 로그인 해서 자신이 이용했던 이력을 볼 수 있습니다(??) <- 예정에 없던 이슈

**Comment by 10001if** [comment]
열린옷장 
온라인대여
서비스 beta


열린옷장 온라인대여 서비스 란?
거리, 시간상 열린옷장 오프라인 공간을 방문할 수 없는 분들을 위한 온라인 택배 서비스입니다.
대여자가 직접 측정한 신체사이즈를 바탕으로 원하시는 스타일의 정장을 검색 제안합니다. 
언제든 온라인으로 주문하고, 어디서든 택배로 받을 수 있습니다. 

아직은 beta 서비스인 이유
열린옷장은 그동안 약 4만 명 이상의 대여를 통해 축적된 데이터를 기반으로 대여자의 신체사이즈에 맞는 옷을 컴퓨터 프로그램이 고르는 혁신적인 의류검색 엔진을 개발 중입니다. 다만 아직은 미완성인 상태로 좀 더 많은 대여 케이스 축적을 통해 정확도를 높여 나아가야 합니다. 그래서 아직은 beta서비스입니다. 

혁신적인 의류검색 엔진 개발에 참여할 기회
본 베타서비스에서는 본인이 직접 측정한 사이즈와 원하는 스타일을 입력하시면 열린옷장이 개발중인 의류 검색엔진을 통해 열린옷장 보유의류 중 적합한 의류 그룹을 찾은 후 사진과 함께 제안해드립니다. 그리고 그 중 배송 받고자 하는 의류를 대여자가 직접 선택할 수 있습니다. 

다만, 아직은 정확도가 완벽하지 않습니다
그래서 열린옷장 테일러들이 검색결과를 분석 후 검색을 통해 제안 드린 의류가 적합하지 않다고 판단되면 선택하신 의류와 유사하지만 다른 의류를 배송할 수도 있습니다. 그러나, 당신의 참여를 통해 세상에 없던 혁신적인 의류검색 엔진은 한 발 더 진화할 것입니다. 그리고 그 진화를 통해 ‘온라인 정장 대여’에 새로운 역사를 쓰게 될 것입니다.   
 











온라인 정장대여 방법

회원 가입원활한 배송을 위해 성명, 전화번호, 주소 등 개인정보를 정확하게 기입해주세요.

셀프 사이즈 측정잘 맞는 옷을 받기 위해 정확한 사이즈 측정은 필수! 사이즈 측정 가이드를 반드시 참고하여 신체사이즈를 정확하게 재고 빠짐없이 기입해주세요.

주문서 작성원하시는 품목과 스타일, 대여기간 등 주문서 항목을 빠짐없이 기입해주세요.

의류 검색 및 선택작성해주신 주문서를 바탕으로 열린옷장 보유의류 중 사이즈, 컬러, 스타일 등 조건에 적합한 의류 그룹을 검색하여 사진과 함께 보여드립니다. 보여드린 의류 중 마음에 드는 의류가 있다면 선택할 수 있습니다. 단, 아직 베타서비스이므로 검색 결과를 열린옷장 테일러가 분석하여 부적합한 선택으로 판단될 경우 다른 의류가 배송될 수 있습니다.

결제 완료배송비를 포함한 대여금액을 결제합니다.

의류 배송셀프 측정하신 사이즈에 맞는 정장을 선택하여 포장한 후 택배 배송합니다. 입으셔야하는 날짜 1일전까지 도착하도록 발송합니다. 

의류 반납대여기간 내에 도착하도록 대여기간 만료 1일 전에 박스포장 한 후 열린옷장으로 발송해주세요.

**Comment by aanoaa** [comment]
진화, 혁신적인, 새로운 역사 등등

넘 거창하지 않나요 저만 좀 그런가여

**Comment by 10001if** [comment]
열린옷장 
온라인대여
서비스 beta

열린옷장 온라인대여 서비스 란?
거리, 시간상 열린옷장 오프라인 공간을 방문할 수 없는 분들을 위한 온라인 택배 서비스입니다.
대여자가 직접 측정한 신체사이즈를 바탕으로 원하는 스타일의 정장을 제안합니다. 
언제든 온라인으로 주문하고, 어디서든 택배로 받을 수 있습니다.


열린옷장은 그동안 약 4만 명 이상의 대여를 통해 축적된 정보를 바탕으로 대여자의 신체사이즈에 맞는 옷을 제안하는 방법을 개발 중입니다. 다만 아직은 미완성인 상태로 좀 더 많은 대여 케이스 축적을 통해 정확도를 높여 나아가야 합니다. 그래서 아직은 beta서비스입니다.

베타 서비스에서는 본인이 직접 측정한 사이즈를 입력하면 열린옷장 보유의류 중 적합한 의류를 찾은 후 사진과 함께 제안합니다. 그리고 그 중 배송 받고자 하는 의류를 대여자가 직접 선택할 수 있습니다. 다만, 아직은 정확도가 완벽하지 않습니다. 그래서 열린옷장 테일러들이 결과를 분석 후 제안 의류가 적합하지 않다고 판단되면 선택한 의류와 유사하지만 다른 의류를 배송할 수도 있습니다. 

온라인 정장대여 방법

회원 가입원활한 배송을 위해 성명, 전화번호, 주소 등 개인정보를 정확하게 기입해주세요.

셀프 사이즈 측정잘 맞는 옷을 받기 위해 정확한 사이즈 측정은 필수! 사이즈 측정 가이드를 반드시 참고하여 신체사이즈를 정확하게 재고 빠짐없이 기입해주세요.

주문서 작성원하시는 품목과 스타일, 대여기간 등 주문서 항목을 빠짐없이 기입해주세요.

의류 검색 및 선택작성해주신 주문서를 바탕으로 열린옷장 보유의류 중 사이즈, 컬러 등 조건에 적합한 의류 그룹을 검색하여 사진과 함께 표시합니다. 표시된 의류 중 마음에 드는 의류가 있다면 선택할 수 있습니다. 단, 아직 베타서비스이므로 열린옷장 테일러가 분석하여 부적합한 선택으로 판단될 경우 다른 의류가 배송될 수 있습니다.

결제 완료 배송비를 포함한 대여금액을 결제합니다.

의류 배송셀프 측정하신 사이즈에 맞는 정장을 선택하여 포장한 후 택배 배송합니다. 입으셔야하는 날짜 1일전까지 도착하도록 발송합니다.

의류 반납대여기간 내에 도착하도록 대여기간 만료 1일 전에 박스포장 한 후 열린옷장으로 발송해주세요.

**Comment by 10001if** [comment]
@aanoaa 제가 조금 수정해 보았습니다.

**Comment by aanoaa** [comment]
넘 구리지만 complete
