### ISSUE TITLE
배송지 입력 란에 비고란의 추가 생성

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#50]
![2017-01-25 3 49 18](https://cloud.githubusercontent.com/assets/4696328/22321344/31125fb4-e3d7-11e6-91d7-d00d34fb49c1.png)
배송과 관련하여 추가 정보를 입력할 수 있는 비고란의 생성을 요청드립니다.

현재, 무료대여를 진행해야 하는 대여자분들에게는 쿠폰을 통한 대여 방법을 실행하고 있습니다.
하지만 온라인의 경우에는 쿠폰과 관련된 기능이 존재 하지 않기 때문에 온라인으로 무료대여권을 제공해야 하는 분들에게는 비고란에 쿠폰 번호를 입력하도록 하여 무료 대여를 진행하려고 합니다. 무료대여를 진행해야 하는 경우 결제 방식은 계좌이체를 선택하도록 한 뒤, 쿠폰 발급이 확인되면 입금 없이 의류 대여를 진행하려고 합니다. @aanoaa

**Comment by aanoaa** [comment]
비고를 쿠폰대용으로 쓰려고 하시는건데
몇가지 문제가 예상됩니다.

- 결제를 진행하지 않고 주문서의 상태를 임의로 바꿀 수 있는 기능이 없습니다.
- 입력한 쿠폰이 유효한지 확인하려면 직접 DB 를 조회해야 합니다.
- 입력한 쿠폰의 추적이 불가능 합니다.(재사용 가능)

당장 생각난 것만 3가지 입니다.

사용자의 목소리를 들을 수 있는 `비고` 란이 추가되는 건 필요한 기능입니다만,
쿠폰기능을 위해 사용하고자 한다면 위 변수들을 포함해서 대비를 해두어야 합니다.

쿠폰코드를 넣는 기능보다 위 변수들에 대한 예외처리가 더 오랜 시간이 걸릴 수 있습니다.

**Comment by 10001if** [comment]
> 결제를 진행하지 않고 주문서의 상태를 임의로 바꿀 수 있는 기능이 없습니다.
-> 이 부분은 이런 경우를 제외하더라도 필요한 상황이 발생할 수 있을 듯 합니다. 

> 입력한 쿠폰이 유효한지 확인하려면 직접 DB 를 조회해야 합니다.
> 입력한 쿠폰의 추적이 불가능 합니다.(재사용 가능)
-> 이 부분에 대해서는 생각을 하지 못했습니다. 충분히 문제가 될 소지가 있겠네요.

@aanoaa 쿠폰 기능을 넣는 이슈가 복잡하다고 생각되어 비고란의 생성을 요청드린 것입니다. 정상적인 방법이 아니기 때문에 쿠폰 기능을 삽입하는 것이 올바른 방법이라고 생각되시면 쿠폰 기능 추가를 요청드립니다.

**Comment by aanoaa** [comment]
비고는 대여자가 열린옷장에 주문과 관련된 문의/요청을 기록하는 컬럼입니다.
지금의 `order` 테이블에는 `desc`, `message` 등의 컬럼이 있지만 이것을 사용하기에는 부적절 합니다.
스키마의 변경이 필요합니다.

- desc

    staff 들이 사용하는 메모같은 기능
    라운드 반팔 블라우스 / 코트 추가 / 지난번 사이즈 원합니다.

- message

    대여메세지

**Comment by aanoaa** [comment]
배송과 관련된 문의/요청이 있을 수도 있을 것 같습니다.

**Comment by keedi** [comment]
이것이 비단 비고란 만의 문제는 아닌 것 같습니다. 관련해서 ticket.theopencloset.net 과 갈은 고객센터에 대응하는 사이트가 필요할 것으로 사료됩니다. 민원(?)과 같은 것은 이쪽으로 모두 돌려서 온라인으로 업무를 상담하게 하고 staff, share 등의 사이트에서 해당 이슈 번호를 사용하는 식으로 해야 할 것 같습니다. battle.net 고객 상담 페이지가 최근 봤던 사례 중 일반인이 접근하기에는 괜찮았던 것 같습니다. 다만 이렇게 진행할 경우 일정이나 로드맵 같은 것을 좀 잡아야지만 가능할 것 같습니다.

![screenshot-kr battle net-2017-02-01-16-22-07](https://cloud.githubusercontent.com/assets/138451/22498306/d1aeb45a-e89a-11e6-8211-56874b9446f8.png)

**Comment by keedi** [comment]
마찬가지로 쿠폰과 본 이슈는 별개인 것 같습니다. 쿠폰과 관련된 것은 별도의 이슈나 기능으로 처리해야 할것으로 보입니다.

**Comment by aanoaa** [comment]
고객의 입장에서 이런 help 기능은 좋겠지만 지금 원하는 기능은

"무광자켓으로 주세요"
"경비실에 맡겨주세요"

같은 것들을 처리하기 위함입니다.

**Comment by aanoaa** [comment]
배송 및 상품문의 등에 관련한 일련의 과정을 시스템에서 관리하면 좋겠지만,
필요가 있을때까지는 staff 이 직접 담당하도록 하고
여기에서는 배송요청/문의를 기록하는 기능으로 제한하도록 하겠습니다.

**Comment by aanoaa** [comment]
#70 에서 처리되었습니다.

7cb6907d8f4fb6b2f45c0f19e2ced7ef1e9289b4
