### ISSUE TITLE
쿠폰으로 대여

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#53]
쿠폰코드를 사용해서 대여할 수 있도록 해야 합니다.

**Comment by aanoaa** [comment]
서울시 이벤트도 고려해야 할까요?

**Comment by 10001if** [comment]
서울시 이벤트가 고려되는 것이 필요합니다. 작년에 진행할 때도 요청받은 부분이지만 구현이 어려워 승낙하지 못했었습니다.

**Comment by aanoaa** [comment]
1. 취업지원센터 -> 2. 열린옷장 -> 3. 방문예약

2번 단계에서 내부적으로 쿠폰이 지급됩니다.

온라인에서 사용하기위해서는..

- 지급된 쿠폰코드를 보여주고 온라인 대여로 사용가능하다고 안내합니다.
- 온라인에서 주문합니다.
- 결제할때에 쿠폰코드를 입력합니다.

이런식으로 하면 어떨까 합니다.
더 좋은 아이디어가 있다면 알려주세요.

**Comment by 10001if** [comment]
@aanoaa 네 제안해 주신 방법 괜찮습니다. 온라인 쿠폰 이용은 지난 번에 설명해 주신 것과 같이 결제시 쿠폰을 입력하는 방식으로 진행하는 것이 자연스러우니, 온라인의 경우에는 이렇게 사용하면 된다고 안내만 정확히 해주면 될 것 같습니다. ^^

**Comment by aanoaa** [comment]
이번 작업을 하면서,

OpenCloset::Web::Plugin::Helpers 의

- transfer_order
- commify

두개의 helper 를 OpenCloset::Plugin::Helpers 에 추가하였습니다.
중복이 되므로 OpenCloset::Web::Plugin::Helpers 에서 삭제해주어야 합니다.

OpenCloset::Plugin::Helpers v0.0.11 이 요구됩니다.
