### ISSUE TITLE
iamport admin 에서 가상계좌 환불이 아니됨

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#59]
> 결제취소에 실패하였습니다. [400733|환불서비스 이용 가맹점이 아닙니다.]

**Comment by 10001if** [comment]
@yongbin 오늘 오셔서 말씀해 주시면 바로 처리하도록 하겠습니다.

**Comment by yongbin** [comment]
오늘 이니시스에서 확인한 내용을 내부 내부 bz에 처리완료했습니다. 결론적으로 **현재 MID에서는 가상계좌 결제 취소서비스를 신청하지 않으며 가상계좌 결제 취소 서비스는 신규 MID 신청이나 신규 PG 계약시 진행합니다** 그때까지 발생하는 가상계좌의 환불이슈는 열린옷장에서 전화등으로 개별 컨택후 수동 계좌이체하는 방법으로 진행해야합니다. 

이슈 닫겠습니다.

**Comment by yongbin** [comment]
@10001if 님께 관련사항 말씀드렸습니다.

**Comment by yongbin** [comment]
확인결과 변경된 MID에서도 가상계좌 환불이 정상적으로 되지 않습니다. 관련해서 이니시스측에 확인이 필요합니다. @10001if

**Comment by 10001if** [comment]
@yongbin 제가 이니시스 측에 문의해야 할 내용을 정리해서 한번 설명해 주시면 좋겠습니다. 현재는 제가 어떤 내용을 문의해야할지 잘 모르겠습니다. 확인 해 주시면 바로 문의하도록 하겠습니다.

**Comment by yongbin** [comment]
가상계좌 환불 신청건은 확인결과 이니시스에서 실수로 누락시켰다고 합니다. 오늘중으로 처리해준다고 합니다.

**Comment by aanoaa** [comment]
https://api.iamport.kr/#!/payments/cancelPayment 에 보면,

> 승인된 결제를 취소합니다.
> 신용카드/실시간계좌이체/휴대폰소액결제의 경우 즉시 취소처리가 이뤄지게 되며, 가상계좌의 경우는 환불받으실 계좌정보를 같이 전달해주시면 환불정보가 PG사에 등록되어 익영업일에 처리됩니다.(가상계좌 환불관련 특약계약 필요)

라고 쓰여져 있습니다.

**Comment by yongbin** [comment]
테스트 완료했습니다. 정리하면 아래와 같습니다.
 - PG(이니시스에) 가상계좌 환불 계좌 등록이 정상적으로 완료되었음 (가상계좌 환불시 추가 300원의 수수료가 부과됨)
 - 가상계좌의 환불은 1. 이니시스 관리자 UI, 2. 아임포트 UI, 3. 우리 서비스 내(API 호출) 모두 가능하며 3은 아직 구현되지 않았으며, 1,2는 테스트 완료함
 - 가상계좌의 환불에 있어서 이니시스 관리자를 통해 환불한 사항은 아임포트 UI 목록에 반영되지 않음을 확인 (이는 정산에 영향이 있을수 있으므로 참고)
 - 가상계좌 환불신청을 할 경우 입금자의 이름을 8자 미만으로 truncate 되어야 함 ( '유용빈(SILEX)' -> '유용빈(SILE' )

이상입니다. 이슈 닫겠습니다.
