### ISSUE TITLE
회원가입 및 로그인

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#6]
어떤 입력을 받을 것인지 고민해야 하고 로그인 폼을 만들어야 합니다.

재고관리의 로그인과 구분되어야 할 것인지,
구분되지 않는다면 재고관리의 로그인을 재활용할 것인지 등에 대한 고민도 필요합니다.

**Comment by aanoaa** [comment]
제가 결정해버린다면 새로 만든다.
일 것 같습니다.

하지만 개발의 편의를 위해 임시로 재고관리의 로그인을 재활용 하도록하겠습니다.

**Comment by aanoaa** [comment]
지금 시스템 그대로 활용할 수도 있습니다.
인증번호에 따른 비밀번호 만료시간 대신에
사용자가 직접 비밀번호를 설정 할 수 있도록 해야 합니다.

사용자의 role 을 생각해봐야 합니다.
단순하게 staff 와 대여자로 구분해서 생각해 볼 수 있습니다.

role 에 따라 권한을 부여해서 기능을 제한해야 하기 때문입니다.
비밀번호 및 email 을 기억하지 못했을때 비밀번호의 reset 기능도 필요합니다.

**Comment by aanoaa** [comment]
휴대폰 본인인증에 관련된 내용도 이번 이슈에서 처리되어야 합니다.

**Comment by aanoaa** [comment]
@10001if 아래 서비스 신청해주세요.

쇼핑몰 주소는 https://share.theopencloset.net 이 될 예정입니다.

https://www.kcp.co.kr/service.payment.certRequest.do?cmd=certApply

**Comment by aanoaa** [comment]
대여자가 체결된 주문서의 목록을 볼 수 없어야 합니다.

`staff` 컬럼으로 구별 할 수 있습니다.
현재로썬 대여자와 staff 를 구별만 할 수 있다면 되기 때문에 충분합니다.

사용자별 role 에 관련한 작업은 필요가 있을때 진행하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 접수는 완료하였습니다. 업체에서 연락이 오면 다시 이야기 드릴게요.

**Comment by 10001if** [comment]
@aanoaa 신청 한 지 꽤 되었는데 연락이 없어서 상담사 연결을 시도했는데 10번 정도 전화해도 받지를 않네요. 우선 다시 신청해놓았습니다~

**Comment by aanoaa** [comment]
@yongbin 승인을 받으려면 서비스에 이용약관 및 개인정보 취급방침이 있어야 한다고 합니다.
해서, 임시로 서비스를 띄워놓아야 합니다.

설정은 제가 했고, `share.theopencloset.net` 도메인 설정을 해주세요.

승인을 받을 주소는 https://share.theopencloset.net/welcome 입니다.

**Comment by yongbin** [comment]
```
; <<>> DiG 9.8.3-P1 <<>> share.theopencloset.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39846
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 5, ADDITIONAL: 5

;; QUESTION SECTION:
;share.theopencloset.net.	IN	A

;; ANSWER SECTION:
share.theopencloset.net. 600	IN	A	61.100.184.211

;; AUTHORITY SECTION:
theopencloset.net.	105015	IN	NS	ns259.dnsever.com.
theopencloset.net.	105015	IN	NS	ns82.dnsever.com.
theopencloset.net.	105015	IN	NS	ns231.dnsever.com.
theopencloset.net.	105015	IN	NS	ns91.dnsever.com.
theopencloset.net.	105015	IN	NS	ns18.dnsever.com.

;; ADDITIONAL SECTION:
ns18.dnsever.com.	16182	IN	A	151.80.120.8
ns82.dnsever.com.	102665	IN	A	149.56.189.108
ns91.dnsever.com.	104592	IN	A	5.135.232.49
ns231.dnsever.com.	16164	IN	A	158.69.189.75
ns259.dnsever.com.	16164	IN	A	192.31.185.229

;; Query time: 301 msec
;; SERVER: 192.168.0.199#53(192.168.0.199)
;; WHEN: Thu Jul 28 16:44:07 2016
;; MSG SIZE  rcvd: 245
```

설정 완료했습니다.

**Comment by aanoaa** [comment]
@10001if 인증업체에 승인을 위해서 https://share.theopencloset.net/welcome 주소를 전달해주세요.

**Comment by aanoaa** [comment]
개발언어는 perl 입니다.

**Comment by 10001if** [comment]
@aanoaa 인증업체에 주소 전달했구요. 개발언어도 메일로 답변 드렸습니다.

**Comment by aanoaa** [comment]
이런 답변을 받았습니다.

> 또한 개발 언어는 예를 들어 asp / php /  jsp 등 으로 확인해서 보내주시기 바랍니다.

asp / php / jsp 는 사용하지 않고요.
perl 이라는 언어를 사용하고 있습니다.

**Comment by aanoaa** [comment]
> 안녕하세요. NHN 한국사이버결제 김여경입니다.
>
> KCP에서 제공하고 있는 샘플소스의 웹언어의 경우, ASP / JSP / PHP / ASP.NET 으로 제공하고 있으며
> 별도로 perl 의 언어로는 제공하는 부분이 없습니다.
>
> 우선 현재 저희가 제공하고 있는 각 언어별 샘플소스를 전달드리니 검토 부탁드립니다.

샘플소스는 크게 상관없습니다.

> 안녕하세요. NHN 한국사이버결제 김여경입니다.
>
> 현재 메일이 계속 반송되어 모듈 전달이 이루어지지 않고 있습니다.
>
> Gmail 계정을 제외한 다른 이메일 주소 회신해주시면 연동모듈 전달드리겠습니다.
>
> 감사합니다. J

@10001if 다른 메일로 보내셔서 받으시면 되겠는데요?

**Comment by 10001if** [comment]
@aanoaa 네. 다른 메일로 회신 요청하였습니다. ^^

**Comment by aanoaa** [comment]
@yongbin 결제대행사에서 본인확인서비스도 할 수 있는지 좀 알아봐주세요.

**Comment by yongbin** [comment]
네 아임포트같이 슥슥 할수 있는게 있는지 한번 알아보고 업뎃하겠습니다.

**Comment by aanoaa** [comment]
staff 이 아니면 유효기간이 짧은 휴대폰 인증번호를 비밀번호로 사용하고 있습니다.
이를 활용할 수 있도록 바꾸어야 합니다.

지금의 오프라인대여 시스템을 유지하면서 사용자가 입력한 비밀번호를 사용할 수 있어야
합니다.

기존 사용자의 편리한 전환도 고려해야 합니다.
열린옷장을 이용한 적이 있는 사용자라면 많은 정보가 남아있기 때문에 비밀번호만 설정해서
사용가능 해야 합니다.

**Comment by aanoaa** [comment]
- 열린옷장이 처음입니다.
- 열린옷장을 이용한 적이 있습니다.

이렇게 나누어서 기존 사용자에 대해 좀 더 손쉽게 입력할 수 있도록 유도할 수 있습니다.

**Comment by aanoaa** [comment]
필요한 정보를 받았다면 인증번호로 사용되던 비밀번호와 사용자가 설정한 비밀번호에 차이를
두어야 하는데, 이것은 유효기간을 늘려주면 해결이 됩니다.

인증번호를 받아서 사용하는 것이라면 5분? 정도만 유효하지만 그렇지 않은 경우에는 유효기간을
길게 설정해두면 됩니다.

오프라인 대여도 지금은 인증번호로만 사용이 가능한데 이것 역시 변경해야 합니다.
지금처럼 인증번호로도 사용가능하고, 비밀번호를 설정한 사용자라면 자신의 비밀번호로 사용할
수 있도록 변경해야 합니다.

**Comment by aanoaa** [comment]
비밀번호로도 사용가능하도록 방문예약 화면이 변경되어야 합니다.
이것은 온라인 서비스 개시 이후에 바뀌어야 합니다.

**Comment by aanoaa** [comment]
열린옷장을 이용한 적이 있는 사용자는 비밀번호만 입력받으면 됩니다.
이를 인증하기 위해서 `이메일`을 입력받으면 어떨까 합니다.

입력한 이메일이 있으면 해당 이메일로 새로운 비밀번호가 포함된 링크를 전달해주고,
비밀번호를 변경할 수 있도록 유도합니다.

입력한 이메일이 없다면 없다고 안내합니다.

이메일 내용은 제가 임의로 작성해서 붙여넣겠습니다.
원하신다면 내용을 바꿔주세요.

**Comment by aanoaa** [comment]
이메일을 보내기 위해서는 메일서버를 운영해야 합니다.
cc @yongbin

**Comment by aanoaa** [comment]
링크를 통해서 로그인을 허용하려면,

    GET /login?email=xxx&password=xxx

요런식으로 로그인이 가능해야 합니다.
로그인 후에는 비밀번호를 변경하도록 유도해야 합니다.

**Comment by aanoaa** [comment]
운영 서버가 메일서버가 되었기 때문에 `localhost` 이런식으로 사용했습니다만,
`mail.theopencloset.net` 같은 호스트명이 붙어서 운영된다면 더욱 좋겠습니다.

**Comment by aanoaa** [comment]
비밀번호 변경안내 메일입니다.

```
From: info@theopencloset.net
To: xxx@gmail.com
Subject: [열린옷장] 비밀번호 변경안내
Date: Tue, 4 Oct 2016 17:50:06 +0900

회원님의 요청으로 열린옷장 서비스의 비밀번호가 변경되었습니다.
아래 링크를 눌러서 비밀번호를 변경해주세요.

https://share.theopencloset.net/login?email=xxx%40gmail.com&amp;password=0006256affeb5e54d008823ef69461c3

-- 열린옷장
```

**Comment by aanoaa** [comment]
staff 가 아닐경우에 로그인해서 이용할 수 없습니다.
이 역시 opencloset/opencloset 에서 수정해주어야 하는 기능입니다.

**Comment by aanoaa** [comment]
재고관리에서 staff 가 아니더라도 로그인 할 수 있도록 수정하였습니다.

**Comment by aanoaa** [comment]
- [x] 새로운 계정을 만들 수 있음
- [x] 기존 사용자를 위해 비밀번호를 재설정 할 수 있도록 함
- [x] SMS 와 email 을 통한 본인확인
- [x] 서비스 사용을 위한 로그인과 로그아웃
- [ ] 인증기관을 통한 본인인증

**Comment by aanoaa** [comment]
인증기관은 나중에 해결하도록 하고 닫겠습니다.

**Comment by keedi** [comment]
> 운영 서버가 메일서버가 되었기 때문에 localhost 이런식으로 사용했습니다만,
> mail.theopencloset.net 같은 호스트명이 붙어서 운영된다면 더욱 좋겠습니다.

메일 서버는 외부로 노출될 경우 손이 많이 가고 보안에 취약해서 보통 메일 서비스를 제공하는 게 아니라면 내부에서만 되게 할텐데, 어찌됐든 도메인을 할당해서 운영할 것이라면 저희 수준(역량?)에서 감당이 될지 모르겠네요. 관련해서는 @yongbin 님과 확인해서 논의해보시길 바래요.

**Comment by yongbin** [comment]
메일을 수신하지 않고 발신만 하는건 상대적으로 그렇게 어렵지 않습니다. 메일서버관련해서 별도 이슈로 열어주시면 제가 진행하겠습니다.

**Comment by aanoaa** [comment]
@yongbin #17

**Comment by aanoaa** [comment]
회원가입시에 입력된 성별이 반영되지 않습니다.

**Comment by aanoaa** [comment]
`&` 대신에 `&amp;` 처럼 XML escaped 된 링크가 email 로 전달됩니다.
이를 수정해주어야 합니다.
