### ISSUE TITLE
테스트 했던 주문서들

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#60]
실제 서비스에 영향이 있을 수 있으므로 적절한 처리가 이루어져야 합니다.

- 50847
- 50849
- 50851
- 50852
- 50979
- 51037
- 51039
- 51042

**Comment by aanoaa** [comment]
옷장기지들이 share 에서 테스트를 하고 있습니다.
위에 적어놓은 것보다 훨씬 많은 주문서가 있습니다.

**Comment by aanoaa** [comment]
저의 23,000원이 여기 어딘가에 묻혀 있습니다.

**Comment by 10001if** [comment]
@aanoaa 오늘 돌려드리도록 하겠습니다. :)

**Comment by aanoaa** [comment]
test-share 가 아닌 share 에서 이미 많은 주문서들이 만들어졌고, 만들어지고 있습니다.
일괄로 삭제할 것이 아니라면 딱히 뭔가 해주어야 할 것은 없습니다.
결제 테스트를 했는데 환불받지 못했다거나 한 주문서가 있다면 남겨주세요.
