### ISSUE TITLE
PG 계약

### ISSUE THREAD

**Issue by yongbin** [opencloset/OpenCloset-Share-Web#63]
온라인 서비스를 위해서 기존 PG의 MID를 추가하거나, 신규 PG 계약을 진행해야 합니다.

**Comment by yongbin** [comment]
- [ ] PG 계약 진행방식 결정 
- [ ] 신규 PG 계약 진행

**Comment by yongbin** [comment]
**이니시스**를 통해서 신규 독립몰 MID를 추가하는 방향으로 결정되었습니다. 이후 진행은 @10001if 님께서 해주시고 완료되면 닫아주세요 이 이슈 진행전에 심사를 위해서 #64가 완료되어야 합니다.

**Comment by 10001if** [comment]
MID가 추가되었고 심사도 완료되었습니다. 이슈 닫도록 하겠습니다.
