### ISSUE TITLE
모바일 소액 결제 지원

### ISSUE THREAD

**Issue by yongbin** [opencloset/OpenCloset-Share-Web#65]
현재 열린옷장 PG가입 상태를 확인한뒤, 모바일 소액결제를 지원할지 여부를 결정해야합니다.

**Comment by yongbin** [comment]
- [ ] 현재 휴대폰 소액결제 가입여부
 - [ ] 열린옷장에서 온오프라인 결제에서 휴대폰 소액결제를 결제수단으로 사용할지 여부 결정

**Comment by yongbin** [comment]
@10001if 님과 확인했습니다. 1. 휴대폰 소액결제는 가입되어있지 않습니다. 2. 당분간 가입할 필요가 없습니다. 현재 share 에 들어있는 결제수단에서 '휴대폰 소액결제'를 제거해야합니다.

**Comment by keedi** [comment]
모바일 소액 결제는 현재 필요하지 않다는 최종 결론이 나왔습니다.

결제를 지원하지 않도록 목록에서 제거하는것은 ab369ea 커밋에서 @aanoaa 님께서 이미 처리하셨습니다.

이슈 닫습니다.
