### ISSUE TITLE
옷장지기의 피드백 묶음

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#70]
- /welcome 이 넘 구림
  - 중요한 내용이 없음
  - 대여일 수
  - 몇일전까지 주문해야 함 등의 내용
- /
  - 뭘눌러야 할지 모르겠음
  - 대여이력을 첫화면에서 볼 필요가 없다
  - `대여주문서 작성` 버튼을 `대여방법` 바로 밑에다가..
- /measurements
  - 치수측정 가이드가 없음
- 다시대여하기를 할 수 없음
  - 그 와중에 몇개만 골라서 할 수 있음 좋겠음
- 반납인 주문서에 대해 다시 대여하기
  - 그중에 몇개만 골라서 다시 대여하기
- 자켓/팬츠 대여시
  - 이 의류를 대여합니다 누르면 자켓 팬츠가 선택되어야 할 것 같은데 자켓만 선택됨
  - 대여할 의류를 선택할때에 /clothes/0P0B1?order_id=51263 식으로 가능함(팬츠가 가능)
- /orders/:id/purchase
  - 배송주소가 로그인 한 사용자 것이 보여짐
  - 희망색상이 아니보임
- 결제취소가 없음
  - 배송전에는 보통 취소가 가능
- 주문완료되고, 결제완료되었을때 문자메세지가 전송되어야..
- 3회이상 대여시 할인을 고려
- 4박 5일이 아니라 3박 4일임
- 의류준비부터 배송까지 최소 3일이 소요됩니다. (X) 5일 임
- /orders/new
  - 블라우스 타입이 이미지로 보여야..
- 옷캔(비백등)이면 대여되면 아니되는데 가능함
- 의류 종류와 실제 의류 요렇게 두개 보임
  - 바코드가 찍혔다면 대체 되든가 해야..
- 의류코드가 보일 필요가 없음
- 주문진행과정에 의류착용일이 보여져야 한다

**Comment by aanoaa** [comment]
이미 이슈에 등록된 것들도 있고 제가 알아서 진행할 수 없는 것들도 많습니다.
주로 컨텐츠에 관련된 것들은 제가 임의로 할 수 없습니다.

**Comment by aanoaa** [comment]
- 의류착용일선택하면 발송일/수령예정일과 '반납을 위한 택배발송일'을 표시
- 여성복은 선호색상 필요없다
- 연장기능이 없다
- *대여방법* 에서 이전단계로 갈 수 있는 방법이 있음 좋겠다
- 배송지는 추가 할 수 있으나 수령인의 전화번호와 이름을 기록할 수 없다
- 가상계좌(무통장입금) 이라고 적어줘야..
- 휴대폰소액결제 안됨
- 언제까지 입금해야 하는지 안내함(-5일 오전 10:00까지)
  - 이게 요일마다 다름(토,일,공휴일은 버퍼로 두지 않음)
- 내가 선택한 옷을 주문서에서 확인하고 싶다?
- 내가 주문하는 과정에서 발송일/수령예정일과 '반납을 위한 택배발송일'을 표시
- 주문서목록에서 의류착용일이 표시되어야
- 발송예정일과 발송일이 필요함
- 배송코멘트가 너무 작아서 커질 필요가 있음

**Comment by aanoaa** [comment]
> 배송지는 추가 할 수 있으나 수령인의 전화번호와 이름을 기록할 수 없다

사용자의 주소지를 여러개 저장할 수 있기는 하나, 수령인의 이름과 전화번호 역시 기록해둘 필요가 있습니다.
주문인과 수령인이 다를 수 있기 때문입니다.

우선 스키마 변경이 필요합니다.

**Comment by aanoaa** [comment]
사용자의 기본 주소에서도 변경이 필요할 수 있습니다.
주소는 같은데 수령인이 다르다면 이름과 전화번호를 다르게 입력할 수 있어야 합니다.
하지만, 이런 경우는 고려치 않도록 하겠습니다.

**Comment by aanoaa** [comment]
- [ ] /welcome 이 넘 구림
  - 중요한 내용이 없음
  - 대여일 수
  - 몇일전까지 주문해야 함 등의 내용
- [ ] /
  - 뭘눌러야 할지 모르겠음
  - 대여이력을 첫화면에서 볼 필요가 없다
  - `대여주문서 작성` 버튼을 `대여방법` 바로 밑에다가..
- [ ] /measurements
  - 치수측정 가이드가 없음
- [ ] 다시대여하기를 할 수 없음
  - 그 와중에 몇개만 골라서 할 수 있음 좋겠음
- [ ] 반납인 주문서에 대해 다시 대여하기
  - 그중에 몇개만 골라서 다시 대여하기
- [ ] 자켓/팬츠 대여시
  - 이 의류를 대여합니다 누르면 자켓 팬츠가 선택되어야 할 것 같은데 자켓만 선택됨
  - 대여할 의류를 선택할때에 /clothes/0P0B1?order_id=51263 식으로 가능함(팬츠가 가능)
- [ ] /orders/:id/purchase
  - 배송주소가 로그인 한 사용자 것이 보여짐
  - 희망색상이 아니보임
- [ ] 결제취소가 없음
  - 배송전에는 보통 취소가 가능
- [ ] 주문완료되고, 결제완료되었을때 문자메세지가 전송되어야..
- [ ] 3회이상 대여시 할인을 고려
- [ ] 4박 5일이 아니라 3박 4일임
- [ ] 의류준비부터 배송까지 최소 3일이 소요됩니다. (X) 5일 임
- [ ] /orders/new
  - 블라우스 타입이 이미지로 보여야..
- [ ] 옷캔(비백등)이면 대여되면 아니되는데 가능함
- [ ] 의류 종류와 실제 의류 요렇게 두개 보임
  - 바코드가 찍혔다면 대체 되든가 해야..
- [ ] 의류코드가 보일 필요가 없음
- [ ] 주문진행과정에 의류착용일이 보여져야 한다
- [ ] 의류착용일선택하면 발송일/수령예정일과 '반납을 위한 택배발송일'을 표시
- [ ] 여성복은 선호색상 필요없다
- [ ] 연장기능이 없다
- [ ] *대여방법* 에서 이전단계로 갈 수 있는 방법이 있음 좋겠다
- [ ] 배송지는 추가 할 수 있으나 수령인의 전화번호와 이름을 기록할 수 없다
- [ ] 가상계좌(무통장입금) 이라고 적어줘야..
- [ ] 휴대폰소액결제 안됨
- [ ] 언제까지 입금해야 하는지 안내함(-5일 오전 10:00까지)
  - 이게 요일마다 다름(토,일,공휴일은 버퍼로 두지 않음)
- [ ] 내가 선택한 옷을 주문서에서 확인하고 싶다?
- [ ] 내가 주문하는 과정에서 발송일/수령예정일과 '반납을 위한 택배발송일'을 표시
- [ ] 주문서목록에서 의류착용일이 표시되어야
- [ ] 발송예정일과 발송일이 필요함
- [ ] 배송코멘트가 너무 작아서 커질 필요가 있음

**Comment by 10001if** [comment]
@aanoaa 필요하다고 보이는 것 위주로 순서를 정리했습니다. 위에서 부터 중요한 이슈입니다. 제가 알려드려야 하는 내용이 없는 것부터 진행해 주시면 될 것 같아요.

**Comment by aanoaa** [comment]
> 여성의 경우 자켓-스커트를 선택하면 사이즈표를 보여주고 자신의 사이즈에 맞는 의류 사이즈를 선택할 수 있도록 함

이미 #71 이슈에 등록되어있습니다.
그쪽에서 진행하겠습니다.

**Comment by aanoaa** [comment]
> 주문완료되고, 결제완료되었을때 문자메세지가 전송되어야..

어느 때에 어떤 메세지가 전송되어야 하는지 적어주세요.

**Comment by aanoaa** [comment]
> 3회이상 대여시 할인을 고려

시나리오가 필요합니다.

A 씨는 3회 이상 대여한 적이 있습니다.
다시 대여하기 위해서 대여품목을 선택하고 배송주소를 입력하였습니다.

결제할때에 3회 이상 대여자이므로 할인이 적용됩니다.

20,000 인데 ?% 할인이 됩니다.

--------------------

이건 제가 상상한거고요.
로그인 했을때 할인에 대해 안내할 것인지,
대여품목을 고를때부터 할인가가 적용되어서 안내되어야 하는지, 결제할때에 적용되어도 되는지 등등
시나리오가 있으면 현재버전에서 바꿔야 할 부분들을 쉽게 파악할 수 있습니다.

**Comment by aanoaa** [comment]
> 옷캔(비백등)이면 대여되면 아니되는데 가능함

제가 테스트하면서 발생한 문제인데,
실제로는 포장할때에 의류의 바코드를 찍게 됩니다.

하지만 저는 테스트하느라고 셔츠를 대여하기 위해서 `S010` 이런식으로 아무거나 막 넣었습니다.
그중에 옷캔인 의류가 있엇고 옷캔의류임에도 대여중인 상태로 바꿀 수가 있었습니다.

**Comment by aanoaa** [comment]
2b648d57b35d8146b9aa73b9ade98be1e6c1ceee

**Comment by aanoaa** [comment]
> 의류착용일선택하면 발송일/수령예정일과 '반납을 위한 택배발송일'을 표시

    발송일 = 의류착용일 - n일
    대여일 = 발송일 + n일
    반납일 = 대여일 + 4d
    택배발송일 = 반납일 - n일

위 내용이 필요합니다.

**Comment by aanoaa** [comment]
> 연장기능이 없다

대여자의 입장에서 연장기능이 없는거죠?
staff 는 반납예정일을 변경할 수 있습니다.

3박4일 뿐만 아니라 4박5일, 5박6일 등등 선택할 수 있는 기능이 필요한거죠?

**Comment by aanoaa** [comment]
대여기간을 입력하기에 적절한 곳은 대여품목을 선택할때에가 아닌가 싶습니다.

지금은 의류 착용일만을 입력하는데, 이렇게 되면 좀 애매해집니다.
기간으로 선택하면 착용일은 의미 없고 from ~ to 를 대여자가 선택해야 합니다.

현재는 의류착용일을 가지고 열린옷장에서 from ~ to 를 정하는 시스템이지만,
대여기간을 입력받아야 한다면 대여자가 from ~ to 를 정해야 합니다.

**Comment by aanoaa** [comment]
일단 제가 임의로 정해놓고 틀린 곳을 바로 잡아주시면 수정하겠습니다.

    발송(예정)일 = 의류착용일 - 2일 - 주말 - 공휴일
    대여일 = 발송일 + 0일
    반납일 = 대여일 + 4일
    택배반납일 = 반납일 - 1일

**Comment by aanoaa** [comment]
의류착용일은 현재시간을 기준으로 계산되어야 한다

    의류착용일 = (AM 10:00 이전) 오늘 + 3일 부터
    의류착용일 = (AM 10:00 이후) 오늘 + 4일 부터
    발송(예정)일 = 의류착용일 - 3일(AM 10:00 이전) - 주말 - 공휴일
    대여기간 = 대여일 ~ 반납일
    대여일 = 착용일 - 주말 - 공휴일 - 1일
    반납일 = 대여일 + 주말 + 공휴일 + 3일
    택배반납일 = 반납일 - 주말 - 공휴일 - 1일

- 09일(목) 09:00 에 주문 -> 14일(화) 부터 가능
- 09일(목) 11:00 에 주문 -> 15일(수) 부터 가능
- 반납일: 27(월)
- 택배반납일: 24(금)

**Comment by aanoaa** [comment]
> 대여기간을 입력하기에 적절한 곳은 대여품목을 선택할때에가 아닌가 싶습니다.

착용일 기준으로 가장빠르게 보내기 때문에 착용일 앞뒤 날짜를 계산할 필요가 없습니다.
착용일 + n일이 되는 것만 고려하면 됩니다.

**Comment by 10001if** [comment]
> 주문완료되고, 결제완료되었을때 문자메세지가 전송되어야..
> 어느 때에 어떤 메세지가 전송되어야 하는지 적어주세요.

▶주문완료_무통장(가상계좌)
[열린옷장]
- 000님, 신청하신 주문이 정상적으로 접수 되었습니다. 결제금액을 국민은행 205737-04-00301 열린옷장으로 
2017-00-00 00:00(접수일로부터 2시간 이내)까지 입금 바랍니다. 기한 내 미 입금시 주문이 자동 취소 됩니다.

▶주문완료_카드
[열린옷장]
- 000님, 신청하신 주문이 정상적으로 결제완료 되었습니다. 주문 확인 과정을 거친 후, 착용일 전에 택배를 전달 받을 수 있도록 기한 내에 발송하도록 하겠습니다.   

▶결제완료
[열린옷장]
- 000님, 입금이 확인되었습니다. 주문 확인 과정을 거친 후, 착용일 전에 택배를 전달 받을 수 있도록 기한 내에 발송하도록 하겠습니다.

**Comment by 10001if** [comment]
의류착용일 = 대여자 본인이 의류를 착용하는 날을 말합니다. 
발송(예정)일 = 의류착용일 3일 전을 말합니다. 예) 의류착용일 20일, 발송(예정)일 17일 (주말, 공휴일 제외)   
택배반납일 = 반납일 1일 전을 말합니다. 예) 반납일 22일, 택배 발송일 21일 (주말, 공휴일 제외)

"ㅇㅇㅇ님, 의류 착용일은 2/20(월)입니다. 의류는 2/15에(수)발송 예정이며 2/17(금) 이전에 배송이 완료됩니다." 라는 멘트를 추가적으로 삽입하고자 합니다.

**Comment by 10001if** [comment]
> 3회이상 대여시 할인을 고려
> 시나리오가 필요합니다.
> 
> A 씨는 3회 이상 대여한 적이 있습니다.
> 다시 대여하기 위해서 대여품목을 선택하고 배송주소를 입력하였습니다.
> 
> 결제할때에 3회 이상 대여자이므로 할인이 적용됩니다.
> 
> 20,000 인데 ?% 할인이 됩니다.
> 
> 이건 제가 상상한거고요.
> 로그인 했을때 할인에 대해 안내할 것인지,
> 대여품목을 고를때부터 할인가가 적용되어서 안내되어야 하는지, 결제할때에 적용되어도 되는지 등등
> 시나리오가 있으면 현재버전에서 바꿔야 할 부분들을 쉽게 파악할 수 있습니다.

대여품목을 고를 때에는 안내가 따로 없어도 될 것 같구요. 그냥 결제 시에만 할인이 적용되면 됩니다. 
관련해서 안내되어야 할 설명은 다음과 같습니다.

대여 횟수가 3회 이상인 경우, 대여비용의 부담이 커지는 것을 줄이기 위해 다음과 같은 정책을 실시하고 있습니다. 
1. 자켓+바지 혹은 자켓 +스커트를 대여하는 경우 나머지 품목(셔츠, 블라우스, 구두, 타이, 벨트)은 대여비를 받지 않습니다. 
2. 세트로 의류를 대여하지 않는 경우, 대여품목의 전체 대여비의 30%를 할인하여 대여비를 책정합니다.

>> 3회 이상 대여 할인 기준은 다음을 참조해주세요. 

자켓1+바지1 대여일 경우, 셔츠1, 타이1, 구두1, 벨트1 만 무료
자켓2+바지2 대여일 경우, 셔츠2, 타이2, 구두2, 벨트2 만 무료
자켓1+스커트1 대여일 경우, (셔츠1 또는 블라우스1), 타이1, 구두1 만 무료
자켓2+스커트2 대여일 경우, (셔츠 또는 블라우스 개수 합이 2), 타이2, 구두2 만 무료
이외의 경우 추가되는 항목은 30% 할인을 적용
자켓3벌 이상이거나, 바지3벌 이상이거나, 스커트3벌 이상이거나, 기본 대여일 기준 대여금액이 10만원 이상이면 단체 대여로 간주하고 무상 대여 품목 또는 30% 할인을 적용하지 않음

**Comment by 10001if** [comment]
열린옷장의 누적 대여기록과 신체치수를 바탕으로 000의 사이즈에 잘 맞는 의류가 추천됩니다.

1. 추천된 의류 중 마음에 드는 자켓사진을 선택해 주세요. 의류를 선택하여 상세 사이즈를 확인 한 후, 의류를 대여해주세요.

2. 마음에 드는 의류가 없거나, 추천된 의류가 없는 경우 `추천대여` 버튼을 눌러주세요. 
* 추천대여는 000님에게 맞는 사이즈의 의류 중에서 열린옷장이 가장 적합하다고 판단하는 의류를 추천하여 택배 발송하는 제도를 말합니다.

**Comment by aanoaa** [comment]
기본적인 대여기간은 3박4일 입니다.
이것을 선택가능하게 하려고할때에 고려해야 할 문제는,

- 대여비(+20% / 1day)
- 이와 관련된 대여기간의 저장

이제까지의 offline 대여는 착용일과 반납일등을 staff 이 포장단계에서 지정합니다.
결제할때에 대여기간을 얘기하고 연장이 필요할때에 늘려주는 방법이었습니다.

`3박4일`이라는 대여기간을 따로 저장해두지 않았고 결제할때에 대여일과 반납예정일을 저장했습니다.

해서 `대여기간 = 반납예정일 - 대여일` 이 되고 있습니다.

온라인주문에서는 배송문제가 있기 때문에 공휴일과 주말은 제외하기 때문에 비용 계산이 어려워 질 수 있습니다.
대여기간이 `반납예정일 - 대여일` 이 아닐 수 있기 때문입니다.

-------------------------------------

    대여기간: 4일(3박4일)

대여기간을 따로 저장해두고 지금처럼 포장할때에 대여기간을 더해서 반납예정일을 추정해내는 방법을 사용하면 되지 않을까 합니다.

**Comment by aanoaa** [comment]
연장일 = 대여기간 - 4
    연장비 = 대여비 * 연장일 * 20%

포장단계에서 하면 아니되겠군요.
결제금액이 정해져야 하기 때문입니다.

**Comment by aanoaa** [comment]
품목선택단계에서

- 대여기간을 선택하게 합니다.
- 반납예정일을 추정해서 저장합니다.
- 연장비를 계산해서 저장합니다.

끝?

쓰다보니 간단해진 것 같은데, 포장단계에서 임의로 반납예정일을 수정하지 않도록 주의해야 하겠습니다.
대여기간은 지금과 같이 따로 저장해두지 않아도 될 것 같습니다.

**Comment by aanoaa** [comment]
연장이 길어졌을때에, 주말(토,일)이 2번 포함된다면 4일을 대여기간에서 제외하게 됩니다.
대여일이 02-15이고 대여기간이 8박9일 이라면 반납인은 언제가 되어야 할까요?

@10001if

**Comment by aanoaa** [comment]
- [ ] 주문완료되고, 결제완료되었을때 문자메세지가 전송되어야..
- [ ] 3회이상 대여시 할인을 고려
- [ ] *대여방법* 에서 이전단계로 갈 수 있는 방법이 있음 좋겠다
- [ ] 언제까지 입금해야 하는지 안내함(-5일 오전 10:00까지)
  - 이게 요일마다 다름(토,일,공휴일은 버퍼로 두지 않음)
- [ ] 배송코멘트가 너무 작아서 커질 필요가 있음
- [ ] 온라인 쿠폰 입력 프로세스 적용 (2월 말까지)
- [ ] /welcome 이 넘 구림
  - 중요한 내용이 없음
  - 대여일 수
  - 몇일전까지 주문해야 함 등의 내용
- [ ] 다시대여하기를 할 수 없음
  - 그 와중에 몇개만 골라서 할 수 있음 좋겠음
- [ ] 반납인 주문서에 대해 다시 대여하기
  - 그중에 몇개만 골라서 다시 대여하기
  - 희망색상이 아니보임
- [ ] 결제취소가 없음
  - 배송전에는 보통 취소가 가능
- [ ] /orders/new
  - 블라우스 타입이 이미지로 보여야..
- [ ] 의류코드가 보일 필요가 없음
- [ ] 여성복은 선호색상 필요없다
- [ ] 내가 선택한 옷을 주문서에서 확인하고 싶다?

-------------------------

남은 것 다시 적습니다.

**Comment by aanoaa** [comment]
아래는 @10001if 님의 의견을 받아서 날짜계산에 쓰이고 있습니다.
반납일에는 주말과 공휴일을 더하면 아니된다고 하는데 하직 확실하지는 않습니다.

    # 의류착용일(AM 10:00 이전) = 주말 + 공휴일 + 3일 부터
    # 의류착용일(AM 10:00 이후) = 주말 + 공휴일 + 4일 부터
    # 발송(예정)일 = 의류착용일 - 주말 - 공휴일 - 3일
    # 대여기간 = 대여일 ~ 반납일
    # 대여일 = 착용일 - 주말 - 공휴일 - 1일
    # 반납일 = 대여일 + 주말 + 공휴일 + 3일
    # 택배반납일 = 반납일 - 주말 - 공휴일 - 1일

**Comment by aanoaa** [comment]
반납일과 택배반납일은 주말과 공휴일을 고려하지 않습니다.

    # 의류착용일(AM 10:00 이전) = 주말 + 공휴일 + 3일 부터
    # 의류착용일(AM 10:00 이후) = 주말 + 공휴일 + 4일 부터
    # 발송(예정)일 = 의류착용일 - 주말 - 공휴일 - 3일
    # 대여기간 = 대여일 ~ 반납일
    # 대여일 = 착용일 - 주말 - 공휴일 - 1일
    # 반납일 = 대여일 + 3일(대여기간)
    # 택배반납일 = 반납일 - 1일

**Comment by aanoaa** [comment]
> 대여방법 에서 이전단계로 갈 수 있는 방법이 있음 좋겠다

브라우저의 back 버튼 누르는걸로..

**Comment by aanoaa** [comment]
> 언제까지 입금해야 하는지 안내함(-5일 오전 10:00까지)

어떤 결제수단을 선택하던지, 의류착용일에 맞춰서 배송이 이루어 지기위해서는
결제 마감시간이 필요합니다.

오늘 주문해놓고 3일뒤에 결제가 되면 아니됩니다.

**Comment by 10001if** [comment]
@aanoaa 


> 의류착용일선택하면 발송일/수령예정일과 '반납을 위한 택배발송일'을 표시
> 언제까지 입금해야 하는지 안내함(-5일 오전 10:00까지) 이게 요일마다 다름(토,일,공휴일은 버퍼로 두지 않음)
> 1번 2 번의 내용은 다음과 같은 문구를 통해 해결하고자 합니다.
> 
> 1번의 경우에는 (1) 착용일을 입력할 때 (2) 내가 주문하는 과정에서 표시되고
> 2번의 경우에는 (1) 착용일을 입력할 때 보여야 하고 (2) 결제시에도 안내되어야 합니다.
> 
> 의류 착용일 = 02/20
> 발송(예정)일 = 02/17
> 택배 반납일 = 02/21
> 
> 주말, 공휴일은 대여기간에 포함되지 않습니다.
> ** ㅇㅇㅇ님, 2/15(수)에 택배를 발송할 예정입니다. 000님의 의류 착용일은 2/20(월)이므로 2/17(금) 이전에 의류를 전달받으시려면, 2/15(수) 오전 10:00까지 결제가 완료되어야 합니다. 내용을 확인하셨다면 체크 버튼을 눌러주세요 - [x]

이렇게 할까 했습니다.

**Comment by aanoaa** [comment]
![2017-02-11 07-50-12](https://cloud.githubusercontent.com/assets/170528/22847243/0a86e32e-f02f-11e6-9763-786a401c0fe0.png)

발송예정일이 잘못 계산됩니다.

**Comment by aanoaa** [comment]
의류착용일(AM 10:00 이전) = 주말 + 공휴일 + 3일 부터
    발송(예정)일 = 의류착용일 - 주말 - 공휴일 - 3일

오늘이 02-11(토) 이고, 10시 이전입니다.
의류착용일은 02-15(수) 부터 가능합니다.

발송(예정)일은 02-10(금) 입니다.

발송(예정)일이 잘못 계산된 것이 아니라, 구하는 방법이 잘못되었습니다.
조건이 더 있는 것 같습니다.

**Comment by aanoaa** [comment]
> 언제까지 입금해야 하는지 안내함(-5일 오전 10:00까지)

입금기한이 지났는데 결제가 완료되는 경우에 대한 예외처리도 해야 합니다.

예로, 오늘 AM 10:00 까지 입금해야지만 의류착용일 이전에 배송가능한 주문서인데
10:05 분에 입금이 된다면 이 결제는 돌려주고 새로운 주문서를 작성하도록 안내해야 합니다.

**Comment by aanoaa** [comment]
결제기한은 발송(예정)일의 오전 10:00 까지 입니다.
이게 가상계좌의 입금기한에도 사용될 수 있습니다.
현재는 +2h 입니다.

**Comment by aanoaa** [comment]
Tue, 14 Feb 2017 14:30:30 +0900 기준입니다.

착용일보다 택배 발송일이 하루 빠릅니다.

![2017-02-14 14-30-11](https://cloud.githubusercontent.com/assets/170528/22916472/1dc83b0a-f2c2-11e6-8780-8e7f2cba68de.png)

**Comment by aanoaa** [comment]
계산 방법이 변경되었습니다.

    # 발송(예정)일 = 주말 + 공휴일 + 0일    # AM 10:00 이전
    # 발송(예정)일 = 주말 + 공휴일 + 1일    # AM 10:00 이후
    # 대여일      = 발송(예정)일 + 공휴일 + 주말 + 2일
    # 의류착용일   = 대여일 + 1일
    # 반납일      = 대여일 + 대여기간(default 3일)
    # 택배일      = 반납일 - 1일

**Comment by aanoaa** [comment]
결제기한을 발송(예정)일 AM 10:00 까지로 처리해야 합니다.

- 결제기한이 지난 주문서는 결제 할 수 없도록 함
- 결제기한이 지난 이후 결제가 된다면 자동 취소 시켜야 함 (의류착용일 이전에 배송 할 수 없기 때문에)
  - 10:00 이전에 결제 버튼을 누르고 10:00 이후에 결제완료

**Comment by aanoaa** [comment]
> 기한 내 미 입금시 주문이 자동 취소 됩니다.

자동으로 취소 안됩니다.
자동취소를 원하시는 거라면 따로 기능이 필요합니다.

**Comment by aanoaa** [comment]
의류착용일이 월요일일때 반납택배발송일이 착용일 하루전으로 계산됩니다.

**Comment by aanoaa** [comment]
많은 이슈가 처리되었습니다.
시간이 필요하거나 혼자서 처리하기 힘들거나 해결할 필요가 없는(?) 이슈들이 남았습니다.

이슈를 각각 따로 등록해서 진행하도록 하겠습니다.
