### ISSUE TITLE
여성 자켓/스커트 선택 시 사이즈 표를 보여주고 자신의 신체 사이즈의 맞는 옷을 선택하게 하도록 함

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#71]
![2017-02-02 6 02 05](https://cloud.githubusercontent.com/assets/4696328/22543131/8dbccd8a-e972-11e6-944d-be763f2b01f5.png)

여성이 자켓, 스커트를 선택한 경우

1. 위의 사이즈표를 보여주고 자신의 사이즈에 맞는 의류 사이즈를 선택하여 입력할 수 있도록 함.
예) 자켓 - L(77), 스커트 - M(66)
2. 그런데 기본 적으로 자신이 입력한 사이즈를 기반으로 먼저 추천이 되고 이 이후에 사이즈 선택을 추가적으로 변경 할 수 있도록 하면 더 좋을 듯 합니다. 이때 추천은 자켓은 윗배, 스커트는 엉덩이 기준으로 합니다.
예)자켓- L(77)은 윗배 78~82가 추천 , 스커트 - M(66)는 90~94 추천

2번 적용이 어렵다면 적용되지 않아도 되지만, 1번은 필수적으로 적용되어야 합니다.

**Comment by aanoaa** [comment]
대여주문서가 아니라 신체 치수 입력에서 위 표를 보여주고 입력받으면 될 것 같습니다.

스키마의 변경도 필요합니다.
자켓과 스커트의 common size? 를 저장해두어야 합니다.

    자켓: 55
    스커트: 66

이런식의 추가 정보를 저장해두고 staff 가 옷을 고를때 보여주어야 합니다.

**Comment by aanoaa** [comment]
![2017-02-09 10-39-31](https://cloud.githubusercontent.com/assets/170528/22765513/17a0fa30-eeb4-11e6-851f-9a61b18cee20.png)

선택해서 저장할 수 있도록 하였습니다.

**Comment by 10001if** [comment]
`신발 크기` `자켓 크기` `스커트 크기`를
`신발 사이즈` `자켓 사이즈` `스커트 사이즈`로 수정 요청드립니다. ^^
