### ISSUE TITLE
기존 이용자에게 보내는 비밀번호 변경 메일 제목에 오류가 있음

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#73]
![_20170204_121010_1](https://cloud.githubusercontent.com/assets/4696328/22616181/8c1761a0-eaeb-11e6-9691-56ebe123e887.jpg)
다음과 같은 오류가 있습니다. 확인 부탁드립니다.

**Comment by aanoaa** [comment]
메일 클라이언트가 무엇인가요?

**Comment by 10001if** [comment]
gmail을 사용하여 열어보았습니다~

**Comment by aanoaa** [comment]
![password](https://cloud.githubusercontent.com/assets/170528/22730015/9d1e663e-ee28-11e6-8a3f-8195609c0039.png)

저도 gmail 쓰는데..

**Comment by 10001if** [comment]
그러네요. 제가 한번 더 확인해 볼게요. 그 때 이슈가 있으면 다시 열겠습니다.
