### ISSUE TITLE
주문 - 대여품목 카테고리 및 색상 선택

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#8]
대여하고자 하는 의류품목과 색상등을 선택하고,
주문서를 작성하는 과정입니다.

**Comment by yongbin** [comment]
![screen shot 2016-05-19 at 8 56 13](https://cloud.githubusercontent.com/assets/52704/16720831/0b10fde2-4775-11e6-8afe-80ea3286a4dc.png)

오늘 확인결과 기존에 생각했던 방식과 약간의 변경이 있습니다. 정리하면 아래와 같습니다.

-   공통
    -   로그인한 사용자의 성별의 의류만 대여한다.
    -   로그인한 사용자의 사이즈만 대여한다.
    -   코트, 조끼, 원피시는 대여하지 않는다 (열린옷장 이슈)
-   남자
    -   자켓, 바지, 셔츠, 구두, 벨트, 타이를 n개 선택이 가능하다.
    -   셔츠는 '레귤러', '와이드', '선택 안함' 셋중 하나를 선택해서 n개를 배분한다. (즉 자켓 1, 바지 1, 셔츠 3(레귤러 1, 와이드 1, 무선택 1), 벨트 1, 타이 1로 선택가능)
    -   셔츠 타입에 대한 자세한 설명이 사용자에게 제공되어야 한다 (한만일 대표님 정리)
    -   자켓과 바지 한벌당 타이가격은 한개씩 할인한다.
    -   각각의 가격
        -   자켓 : 10000
        -   바지 : 10000
        -   셔츠 : 5000
        -   구두 : 5000
        -   벨트 : 2000
        -   타이 : 2000
-   여자
    -   자켓, 스커트, 블라우스, 구두를 n개 선택이 가능하다.
    -   블라우스는 '라운드 반팔', '라운드 민소매', '탑', '셔츠', '승무원', '선택안함' 여섯개중 하나를 선택해서 n개로 배분한다.
    -   블라우스 타입에 대한 자세한 설명이 사용자에게 제공되어야 한다 (한만일 대표님 정리)
    -   각각의 가격
        -   자켓 : 10000
        -   스커트 : 10000
        -   블라우스 : 5000
        -   구두: 5000

**Comment by yongbin** [comment]
@10001if 님과 의논해서 남성 자켓 바지, 여성 자켓 스커트는 n개가 아닌 최대 1개로 고정하기로 했습니다. 
 - 대여 결과 화면에서 남자의 경우 '자켓', '바지', 여자의 경우 '자켓', '스커트' 가 기본 선택되어있고 선택해지 (단품대여) 할수 있는 형태로 제시됩니다.
 - 자켓과 바지, 자켓과 스커트는 주문서당 1세트 고정이며 나머지 항목 옵션은 n개 선택이 가능합니다.

**Comment by yongbin** [comment]
슈트 자체의 옵션은 다음과 같습니다.

- 남성 
 - 색상
 - 계절
 - 버튼수 
- 여성
 - 색상
 - 계절

**Comment by aanoaa** [comment]
여러벌 대여가 안될 이유가 없는데 수량에 제한을 두는 이유가 뭔가요?

**Comment by aanoaa** [comment]
원버튼인지 투버튼인지 선택하게 하는 것은 사용하기에 불편함만 가져올 수 있습니다.
사진을 볼 수 없는 상황에서 버튼 갯수는 의미 없습니다.

포장단계에서 선택된 의류를 가지고 사용자에게 확인을 받는 절차를 거치거나 생략하거나
하는 것이 적절할 것 같습니다.

    포장준비 - 사용자 확인 - 포장

이것 역시 문제가 있습니다.
사용자 확인 절차가 얼마나 오래 걸릴지 알 수 없습니다.

추천의류의 사진을 선택할 수 있도록 하되, 서비스 특성상 선택된 의류를 대여할 수 없는 상황에서는
연락을 하던지, 다른 의류를 보내주던지 할 수 있도록 하는 것도 방법입니다.

**Comment by aanoaa** [comment]
다시 한번 생각해본 서비스의 흐름입니다.

- 신체치수 입력
- 주문서 작성
  - 자켓, 바지, 셔츠, 구두..
- 추천의류중에 1,2,3 순위를 선택
  - 혹은 직원추천옵션(아무거나)
  - 추천의류가 없거나 모두 맘에 안들었을때 대안이 필요
  - 초기에 사진이 없을 수 있음
  - 서비스 특성(1벌 밖에 없음)을 설명하고 그에 따른 조치에 대한 안내
  - 사진을 사용자가 등록할 수 있도록 유도하는 방법이 필요
    - 착용샷을 올리면 할인해준다던지?


추천의류를 전혀 보여주지 않는 방향으로 생각했지만,
대여 가능한 의류들 중에서 고르게 한다면 만족도가 좀 더 높지 않을까 싶습니다.

여름인데 동복을 골랐다고 한다면, 포장전에 연락을 해볼 수도 있고요.

**Comment by 10001if** [comment]
@aanoaa 제가 검색에 필요한 정보와 온라인 선택 옵션을 착각해서 발생한 문제 같습니다.

슈트 자체의 옵션은 다음과 같습니다.

- 남성 
 - 색상 ( 직원추천 / 블랙 / 네이비 / 그레이 )
 ~~- 계절 ( 춘추 / 동복 / 하복 )~~
 ~~- 버튼수 ( 원버튼 / 투버튼 )~~
- 대여목적 ( 입사면접, 결혼식, 상견례, 대학(원)면접, 모의면접, 인턴면접, 장례식, 사진촬영(웨딩촬영), 세미나, 발표, 공연(연주회), 축제(행사), OT, 아르바이트, 졸업식, 입학식)
- 여성
 - 색상 ( 직원추천 / 블랙 / 네이비 / 그레이 )
 ~~- 계절 ( 춘추 / 동복 / 하복 )~~
- 대여목적 ( 입사면접, 결혼식, 상견례, 대학(원)면접, 모의면접, 인턴면접, 장례식, 사진촬영(웨딩촬영), 세미나, 발표, 공연(연주회), 축제(행사), OT, 아르바이트, 졸업식, 입학식)

**Comment by yongbin** [comment]
현재 추천없이 사용하는 단계에서는 문제가 없는데, 추후  추후 사진이 추가되고 사용자가 직접 추천의류를 선택해서 대여하는 경우 (의류 상세에서 대여를 누르는 흐름일때) 주문서당 여러벌을 지원하려면 장바구니 같은 기능이 필연적으로 필요해집니다.반면 한벌로 고정할 경우 `의류상세` - `옵션선택` - `결제` 로 한 흐름으로 처리할수 있기때문에 간편합니다. 현실적으로 거의 대부분의 사용자가 한벌을 대여하고 있는것도 이유입니다.

**Comment by yongbin** [comment]
지금 제가 이해하고 있는 흐름은 

 - 로그인
 - 신체치수 입력
 - 주문서 작성(이 이슈)
 - 결제
 - 옷을 찾아서 발송

입니다. 결제 이후에 접수된 주문서를 가지고 추천의류 시스템을 이용하던, 경험을 기반으로 찾던, 대여자와 다시한번 통화해서 확인을 하던 당장은 시스템 외 이슈입니다. 형석님이 말씀하신것 처럼 지금 방식은 옷을 특정하지 않기때문에 시스템이 극단적으로 단순해지는게 가장 큰 장점인것 같습니다.

**Comment by aanoaa** [comment]
한벌로 고정했을때 서비스가 단순해진다는 것은 큰 장점 같습니다.

제가 생각한 서비스의 흐름은 마일스톤의 이슈 순서대로 입니다.
https://github.com/opencloset/OpenCloset-Share-Web/milestone/1


사용자가 선택하지 못했다면 불만이 생길 수 있지만, 
본인이 선택한 것이라면 불만이 있어도 수용할 수 있을 것 같다 입니다.

그래서 생각했던 것이

1. 배송전에 옷에 대한 정보를 보내주고 확인받는다.
2. 추천의류중에 우선순위 1,2,3 을 고른다

입니다.

위 단계가 추가된다면 `어? 뭐 이런 옷을 보냈어?` 하는 사용자가 적어질 것입니다.
일단 옷을 보고 주문을 취소하거나 맘에 안들지만 수용하거나..

**Comment by 10001if** [comment]
@aanoaa 형석님 질문이 있는데요. 그럼 결제 전에 의류를 사용자가 선택하는 시간이 필요할 것 같은데. 이 시간이 지난 후에 결제를 요청하는 것도 문제가 없을까요?

**Comment by aanoaa** [comment]
제가 질문을 이해를 못했습니다.

> 배송전에 옷에 대한 정보를 보내주고 확인받는다.

결제후에 포장단계에서 선택된 의류 사진을 사용자에게 보내주는 방법

> 추천의류중에 우선순위 1,2,3 을 고른다

결제 전에 추천의류중에 선택하는 방법

**Comment by aanoaa** [comment]
주문서에 online 과 offline 을 구별할 수 있는 컬럼이 필요합니다.

**Comment by yongbin** [comment]
다음 두가지 이슈가 등록되어있습니다. 급하시면 형석님이 진행하셔도 되고 아니면 지금 진행하고 있는 https://github.com/opencloset/opencloset/issues/606 완료되고 진행하겠습니다. 

https://github.com/opencloset/OpenCloset-Schema/issues/27
https://github.com/opencloset/opencloset/issues/715

**Comment by aanoaa** [comment]
사용자는 옳게 주문했는지 확인을 위해서 또는
배송추적을 위해서 주문서를 확인하고 싶어할 수 있습니다.

이때에 별다른 로그인없이 접근할 수 있도록 하면 좋겠습니다.

https://share.theopencloset.net/order/:order_id

형식인데, `order_id` 는 다른 사람들도 쉽게 추측할 수 있습니다.
해서 주문서마다 UUID 를 부여해서

https://share.theopencloset.net/order/:UUID

처럼하면 남들은 추측하기 어려운 링크가 만들어 집니다.

**Comment by aanoaa** [comment]
주문서에 uuid 를 사용하기 위해서는 DB 스키마가 변경되어야 합니다.

1. 주문서에 uuid 컬럼을 넣는다
2. 주문서와 uuid 간의 map 테이블을 만든다

다른 좋은 대안이 있다면 알려주시기 바랍니다.

**Comment by aanoaa** [comment]
주문서의 상태도 추가되어야 합니다.

주문 ~ 결제 까지의 상태를 세분화해서

- 카테고리 선택 후
- 추천의류 선택 후
- 결제전
- 배송전

등등에 대한 상태를 추가해서 상태를 추적해나가야 합니다.

**Comment by aanoaa** [comment]
본인과 staff 를 제외한 사람은 특정 주문서를 볼 수 없어야 합니다.

**Comment by aanoaa** [comment]
옷을 선택한 이후에 다시 선택할 수 있어야 합니다.

취소해서 처음부터 주문하거나 카테고리는 그대로 두고 추천의류목록에서
다시 선택하거나

**Comment by aanoaa** [comment]
> 주문서에 uuid 를 사용하기 위해서는 DB 스키마가 변경되어야 합니다.

로그인해서 사용하게 한다면 UUID 를 이용해서 만들 필요가 없습니다.
자신의 주문서말고는 볼 수 없도록 하는 방법입니다.

**Comment by aanoaa** [comment]
방문예약신청이나 회원가입할때에 집주소를 입력받긴하지만,
배송주소는 여러곳을 입력해두고 선택할 수 있다면 편리합니다.

해서 사용자마다 여러곳의 배송주소를 관리할 수 있도록 해야 합니다.

**Comment by aanoaa** [comment]
대여목적과 의류착용일을 입력받아야 합니다.

**Comment by aanoaa** [comment]
의류착용일은 적용했습니다만, 대여목적은 일단 skip 합니다.

**Comment by 10001if** [comment]
@aanoaa 선택한 의류를 그대로 대여하는 경우라면 대여목적을 아는 것이 중요하지 않을 수 있겠지만, 선택한 의류 외에 다른 의류를 보내줘야 하는 상황이 발생할 것이므로 대여목적을 아는 것이 필요해 보입니다. 대여목적도 차후에 입력가능하도록 수정 요청드립니다~

**Comment by aanoaa** [comment]
대여목적을 넣는 것은 어려운 일이 아닌데 어디에 어떤 방식으로 넣어야 할지 고민하는게 시간이
걸려서 skip 하였습니다.

나중에 사용해보시고 어느 과정에 대여목적을 넣는게 좋겠다 라는 얘기를 해주시면 반영하도록
하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 네~ 알겠습니다. 사용 후 다시 말씀드리도록 할게요~

**Comment by aanoaa** [comment]
pre_category 를 활용할 생각을 못했습니다.

현재는 선택한 의류품목에 대해서 order_detail 을 만들어서 처리합니다.
