### ISSUE TITLE
소개화면이 넘 구림

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#80]
/welcome

**Comment by keedi** [comment]
이건 좀 솔직히 우리가 할 수 없는 영역이 아닌가... 최소 welcome 페이지에서 어떤 내용을 담고 싶은지는 나와야 할 것 같습니다. html, css는 아니더라도 포토샵 화면이라도...

**Comment by aanoaa** [comment]
네 그래서 assignee 에 @10001if 님을 넣었습니다.
대화해서 이미 알고 있습니다.

**Comment by 10001if** [comment]
@aanoaa @keedi 이 부분에 대한 고민이 많이 부족했습니다. 고민해 보고 말씀드리도록 하겠습니다.

**Comment by 10001if** [comment]
오픈 전까지 특별히 개선안을 내놓기가 어려울 것 같습니다. 

기존에 이용한 적 있는 사람과 그렇지 않은 사람을 구분하여 바로 대여페이지로 안내하는 것이 좋을 것 같습니다.

**Comment by aanoaa** [comment]
자세하게 어떻게 해달라는 요청이 있을때까지 기다리겠습니다.

**Comment by 10001if** [comment]
특별한 아이디어가 없기 때문에 v0.0.3으로 변경하겠습니다.

**Comment by 10001if** [comment]
열린옷장 ‘온라인 정장대여 서비스’ 란?
거리, 시간상 열린옷장 오프라인 공간을 방문할 수 없는 분들을 위한 온라인 택배 서비스입니다.
대여자가 직접 측정한 신체사이즈를 바탕으로 원하시는 스타일의 정장을 검색 제안합니다. 
언제든 온라인으로 주문하고, 어디서든 택배로 받을 수 있습니다. 

아직은 beta 서비스인 이유
열린옷장은 그동안 축적된 약 5만 명 이상의 대여 데이터를 기반으로, 대여자의 몸에 잘 맞는 옷을 컴퓨터 프로그램이 추천하는 혁신적인 의류검색 엔진을 개발 중입니다. 더 많은 대여 케이스 축적을 통해 정확도를 높여 나아가고 있습니다. 그래서 아직은 beta서비스입니다. 

혁신적인 의류검색을 경험해보세요.
직접 측정한 신체사이즈와 원하는 스타일을 입력하시면 적합한 의류를 찾은 후 사진과 함께 제안해드립니다. 그 중 원하는 의류를 대여자가 직접 선택할 수 있습니다. 다만, 검색된 의류가 적합하지 않다고 판단되면 선택하신 의류와 유사한 다른 의류를 배송할 수도 있습니다. 
 




온라인 정장대여 방법

회원 가입정확한 배송을 위해 성명, 전화번호, 주소 등의 정보를 기입해주세요.

셀프 사이즈 측정사이즈 측정가이드를 참고하여 신체사이즈를 잰 후 빠짐없이 기입해주세요.

주문서 작성원하시는 품목과 스타일, 대여기간 등 주문서 항목을 기입해주세요.

의류 검색 및 선택작성해주신 주문서를 바탕으로 사이즈, 컬러, 스타일 등 조건에 적합한 의류를 검색하여 사진과 함께 보여드립니다. 보여드린 의류 중 마음에 드는 의류를 선택할 수 있습니다. 단, 아직 베타서비스이므로 검색 결과가 부적합하다고 판단될 경우 다른 의류가 배송될 수 있습니다.

결제 완료배송비를 포함한 대여금액을 결제합니다.

의류 배송주문해주신 의류를 포장한 후 착용일 1일전까지 도착하도록 택배 발송합니다. 

의류 반납대여기간 내에 도착하도록 대여기간 만료 1일 전에 열린옷장으로 발송해주세요.

**Comment by 10001if** [comment]
이 내용으로 요청드립니다. 다만, 지금은 텍스트로 정리되어 올라가 있어서 원래 요구하는 형태의 파일은 메일로 발송하였습니다. 오시면 뵙고 다시 설명드릴게요.

**Comment by aanoaa** [comment]
[온라인대여 메인페이지 2016.07.19.pdf](https://github.com/opencloset/OpenCloset-Share-Web/files/815931/2016.07.19.pdf)

**Comment by aanoaa** [comment]
밑줄이 노란색 바탕이 되어야 합니다.
