### ISSUE TITLE
주문서 작성의 상세화

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#84]
- ~~넥타이의 패턴 선택 가능하도록~~ (#91)
  - 솔리드
  - 스트라이프
  - 체크
  - 도트
  - 기타
- 선호색상을 여러개 선택할 수 있도록
- 대여목적이 필요(추천대여시 필요)
- 배송방법의 선택(택배 or 퀵)
- 신체 치수에따라 대여불가능한 블라우스가 있음 (승무원 블라우스는 85초과시 재고가 없음)
- 블라우스 정렬 및 이름 수정
  - 긴소매 라운드 블라우스
  - 반소매 라운드 블라우스
  - 민소매 라운드 블라우스
  - 긴소매 셔츠형 블라우스
  - 반소매 셔츠형 블라우스 (추가)
  - 탑 블라우스
  - 승무원 블라우스

**Comment by aanoaa** [comment]
퀵 배송은 의류착용일과도 관련이 있습니다.
단순한 선택의 문제는 아닙니다.

**Comment by aanoaa** [comment]
재고는 중요한 건데 재고와 관련된 논의가 부족하지 않았나 싶습니다.
현재는 모든 사이즈별 재고가 있다고 가정하고 있습니다.

**Comment by aanoaa** [comment]
- 여자 바지 선택 가능하지 않도록 수정
- 블라우스 : 선택한 블라우스가 품절될 경우 대체될 수 있음으로 표기
- 여성 색상 선택은 블랙으로 통일

**Comment by aanoaa** [comment]
> 대여목적이 필요(추천대여시 필요)

이건 꼭 필요합니다.

**Comment by aanoaa** [comment]
> 여자 바지 선택 가능하지 않도록 수정

지금은 문제가 있어서 꼭 필요한 기능입니다.

> 블라우스 : 선택한 블라우스가 품절될 경우 대체될 수 있음으로 표기
> 여성 색상 선택은 블랙으로 통일

위 두개도 꼭 필요한 기능입니다.

**Comment by aanoaa** [comment]
나머지는 v0.0.3

**Comment by aanoaa** [comment]
- ~~대여목적이 필요(추천대여시 필요)~~
- ~~여자 바지 선택 가능하지 않도록 수정~~
- ~~블라우스 : 선택한 블라우스가 품절될 경우 대체될 수 있음으로 표기~~
- ~~여성 색상 선택은 블랙으로 통일~~

**Comment by 10001if** [comment]
- ~~넥타이의 패턴 선택 가능하도록~~ (#91)
  - 솔리드
  - 스트라이프
  - 체크
  - 도트
  - 기타
- 선호색상을 여러개 선택할 수 있도록
~- 대여목적이 필요(추천대여시 필요)~
~- 배송방법의 선택(택배 or 퀵)~
~- 신체 치수에따라 대여불가능한 블라우스가 있음 (승무원 블라우스는 85초과시 재고가 없음)~
~- 블라우스 정렬 및 이름 수정~
  - 긴소매 라운드 블라우스
  - 반소매 라운드 블라우스
  - 민소매 라운드 블라우스
  - 긴소매 셔츠형 블라우스
  - 반소매 셔츠형 블라우스 (추가)
  - 탑 블라우스
  - 승무원 블라우스

나머지 이슈는 모두 해결되었고 - 선호색상을 여러개 선택할 수 있도록 만 남아 있습니다. 본 이슈만 다시 등록해 새로 열도록 하겠습니다.
