### ISSUE TITLE
배송주문서목록에 주문서의 상태를 반영

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#87]
주문서 목록에서 주문서의 상태를 임의로 변경 할 수 있어야 합니다.

51185 주문서는 이미 `반납`까지 완료된 상태인데, 현재 `배송중` 상태입니다.
그래서 `반납`으로 변경하려 했으나, 변경할 수 있는 버튼이 없습니다.

**Comment by aanoaa** [comment]
몇가지 고려해야 할 사항을 확인해보고, 주문서의 상태를 제외하고 임의로 변경할 수 있도록 하겠습니다.

- [ ] `대여중` 인 상태의 주문서는 상태를 임의로 변경하면 아니됨
- ...

**Comment by 10001if** [comment]
https://github.com/opencloset/OpenCloset-Share-Web/issues/118 이 이슈도 같은 기능을 필요로 하는 것 같습니다..

**Comment by aanoaa** [comment]
주문서의 상태가 `반납`으로 변경되면 배송상태도 `반납`으로 되어야 하는게 아닌가 싶습니다.
의류반납처리는 staff 에서 하고 있습니다. 관련된 작업을 staff 처리해야 합니다.

**Comment by aanoaa** [comment]
배송상태는 그대로 두고 배송주문서 목록에 주문서의 상태를 반영하는 것이 더 좋은 방법 같습니다.

**Comment by aanoaa** [comment]
`대여중` 과 `반납` 사이에는 주문서의 상태를 임의로 변경하면 안됩니다.
반납받지 않은 주문서를 수선등과 같은 상태로 변경하면 문제가 발생하기 때문입니다.

> 51185 주문서는 이미 반납까지 완료된 상태인데, 현재 배송중 상태입니다.
> 그래서 반납으로 변경하려 했으나, 변경할 수 있는 버튼이 없습니다.

위와 같은 문제를 해결하는 것이 목적이라면, 앞서 얘기했듯이 배송주문서 목록에 주문서의 상태를 반영하는 것이 더 바람직합니다.

**Comment by 10001if** [comment]
@aanoaa 네. 배송주문서 목록의 상태를 반영하는 방법이 좋아보입니다.

**Comment by aanoaa** [comment]
하지만 문제는 여전히 남아있습니다.
`환불`된 혹은 테스트를 위해서 `결제완료` 된 주문서의 상태는 변경할 방법이 없습니다.

**Comment by aanoaa** [comment]
>  환불된 혹은 테스트를 위해서 결제완료 된 주문서의 상태는 변경할 방법이 없습니다.

#124 에서 진행하겠습니다.

**Comment by 10001if** [comment]
@aanoaa 배송주문서 목록에서 상태를 변경한다고 하셨는데, 어디에서 진행되는지 궁금합니다.  오시면 여쭤보도록 할게요. ^^

**Comment by 10001if** [comment]
@aanoaa 확인했습니다. 이해 하였습니다. ^^
