### ISSUE TITLE
옷장지기의 피드백 #2

### ISSUE THREAD

**Issue by 10001if** [opencloset/OpenCloset-Share-Web#88]
1. 대여기간 설정 하는 부분을 지금보다 눈에 띄게 할 수 있으면 좋겠습니다. 
2. 상품의류를 배치할때, 상단에 사진이 있는 의류로 배치를 하고 치수에 가장 적합한 의류를 추천의류라는 표시하면 대여자가 선택하기 수월할 것 같고, 사진이 없는 의류에 사진준비중이라는 텍스트가 추가되면 좋겠습니다.
3. 타이 선택시 패턴/솔리드를 선택할 수 있으면 좋겠습니다.
4. 치수측정단계 
->대여자 입장에서 치수측정한 값이 의류를 선택하는 과정에서 어떻게  참고되는지 잘 모를 것 같아요.
->사이즈는 고정된 숫자가 아니라 범위로 표기하는 건 어떤가요 (*측정해주신 사이즈에 잘 맞는 의류로 보내드린다고 설명) 범위는 다시 이야기 드리겠습니다. 
4) 품목 선택 전에 해당 사이즈를 미리 선택하는 이유는 뭔가요?
5. 대여품목
1) 여자 바지 선택 가능하지 않도록 수정
2) 블라우스 : 선택한 블라우스가 품절될 경우 대체될 수 있음으로 표기
3) 여성 색상 선택은 블랙으로 통일
6. 결제
결제마감일자 및 시간을 조금 더 명확히 고지해주세요.
2017년 3월 2일 오전 10시가 지나면 주문이 자동 취소됩니다. 
7. 기타
뒤로 돌아가면 주문서가 또 생성되어요
뒤로 버튼 만들어주세요. -> 품목이 변경되면 대여기록에 주문서가 남습니다. 
8. 관리자 정보에서 배송일 기준으로 `발송일 오늘`, `발송일 D-1`, `발송일 D-2`, `발송일 D-3~`이 구분되어 보였으면 좋겠습니다.

**Comment by aanoaa** [comment]
> 품목 선택 전에 해당 사이즈를 미리 선택하는 이유는 뭔가요?

이 내용을 제외하고 전부 분리해서 이슈를 만들어 두었습니다.
보충 설명이 필요합니다.

**Comment by aanoaa** [comment]
> 품목 선택 전에 해당 사이즈를 미리 선택하는 이유는 뭔가요?

여성의 자켓 사이즈와 스커트 사이즈를 왜 미리 입력받느냐는 질문입니다.

#92 에서 진행하도록 하겠습니다.
