### ISSUE TITLE
대여기간 설정을 눈에 띄도록 변경

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#89]
대여기간 설정 하는 부분을 지금보다 눈에 띄게 할 수 있으면 좋겠습니다.

**Comment by aanoaa** [comment]
이건 일부러 제가 눈에 잘 띄지 않도록 했습니다.(상의없이)
보통 3박4일 대여가 가장 많을 것이라고 추측했습니다.

필요한 사람은 찾아서 바꿔주고, 필요없는 사람들은 신경쓰이지 않도록 했습니다.

**Comment by aanoaa** [comment]
단순히 선택옵션의 크기를 키워주면 될까요?
아님 눈에 잘띄게 강조해야 하는 건가요?

**Comment by 10001if** [comment]
대부분 3박 4일일 것으로 생각합니다. 그렇지만 예의적으로 기간을 연장하는 사람들이 있을테니 식별은 용이하도록 선택옵션의 크기만 조금 키우면 될 것 같습니다. 다른 글씨체와 동일하거나 조금 크게 하면 충분하지 않을까 생각합니다.

**Comment by aanoaa** [comment]
#117 에 포함되어 있습니다. 닫도록 하겠습니다.
