### ISSUE TITLE
사진이 있는 의류를 우선순위로 배치

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#90]
상품의류를 배치할때, 상단에 사진이 있는 의류로 배치를 하고 치수에 가장 적합한 의류를 추천의류라는 표시하면 대여자가 선택하기 수월할 것 같고, 사진이 없는 의류에 사진준비중이라는 텍스트가 추가되면 좋겠습니다.

-------------------

지금은 특정의류에 대해 사진의 존재 여부는 매번 질의를 하지 않는 이상 알 수 없는 문제가 있습니다.

**Comment by 10001if** [comment]
@aanoaa 당장 해결이 시급한 이슈는 아닙니다. 우선 닫아놓고 필요할 때 다시 열도록 하겠습니다.
