### ISSUE TITLE
치수측정 보충 가이드

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#92]
->대여자 입장에서 치수측정한 값이 의류를 선택하는 과정에서 어떻게  참고되는지 잘 모를 것 같아요.
->사이즈는 고정된 숫자가 아니라 범위로 표기하는 건 어떤가요 (*측정해주신 사이즈에 잘 맞는 의류로 보내드린다고 설명) 범위는 다시 이야기 드리겠습니다. 

------------------

이건 제가 이해를 못했습니다.

**Comment by aanoaa** [comment]
> 대여자 입장에서 치수측정한 값이 의류를 선택하는 과정에서 어떻게 참고되는지 잘 모를 것 같아요.

여성의 자켓사이즈를 선택할때에 신체사이즈 +(4|5) 가 되어야 정확한 의류사이즈임을 알려줘야 할 것 같다는 얘기입니다.
스커트는 +(4|5)를 더하지 않고 동일합니다.

자켓사이즈와 스커트사이즈는 n 이 아니라 n ~ m 의 범위 값이 필요합니다.
cc @10001if

**Comment by aanoaa** [comment]
자켓 사이즈와 스커트 사이즈를 입력하지 않으면 오류가 발생하는데, 한글로 오류메세지가 나와야 합니다.

> Parameter validation failed: bottom_size, top_size

자케사이즈와 스커트사이즈를 입력해주세요.

이런식으로 바뀌어야 합니다.

**Comment by aanoaa** [comment]
추천선택과 관련된 이야기가 있었으나 추후에 결정해서 알려주겠다고 합니다.
cc @10001if

**Comment by 10001if** [comment]
사이즈 기준을 아래와 같이 수정하려고 합니다. 기존에는 결정되어 있는 사이즈였는데, 범위로 변경하였습니다.
![2017-02-28 10 49 45](https://cloud.githubusercontent.com/assets/4696328/23388117/b018e61c-fda3-11e6-84d6-f03485beb772.png)

**Comment by 10001if** [comment]
추천이 가능하다면 추천방향으로 하되, 추천이 어렵다면 추천된 사이즈를 안내해주려고 합니다.

1. 추천의 경우
(1) 자켓 : 신체 윗배 + 5cm = 나온 범위로 추천을 합니다.
(2) 스커트 : 신체 엉덩이 = 범위로 추천을 합니다.
조금 여유있게 

2. 추천하지 않는 경우
(1) 자켓 : 신체 윗배 +5cm 사이즈를 알려줍니다. 
(2) 엉덩이 : 엉덩이 둘레를 알려줍니다. 

추천하거나 추천하지 않는 경우에도 공통적으로 아래의 내용이 들어갔으면 합니다.

* 열린옷장 정장 선택 팁
1. 자켓 : 윗배 둘레에 5cm를 더해서 찾는다. 
2. 스커트 : 엉덩이둘레에 맞는 사이즈를 찾는다.
* 위 가이드는 참고용이며 상세사이즈를 확인 후 선택해주세요. -> 볼드처리

**Comment by aanoaa** [comment]
스커트 사이즈표에서 허리둘레가 `86 ~ 90` 구간과 `99 ~ 102` 구간이 없습니다.

**Comment by 10001if** [comment]
![2017-03-02 4 26 37](https://cloud.githubusercontent.com/assets/4696328/23497134/0c9fc5be-ff65-11e6-8854-fdcaccb9d4c4.png)
@aanoaa 구간 수정하여 넣었습니다.

**Comment by aanoaa** [comment]
9cd682d7dd8d83538410fbddb8d2b29740d2ff59

**Comment by aanoaa** [comment]
여성의 자켓사이즈, 스커트사이즈의 윗배둘레와 엉덩이둘레를 강조해서 보여줘야 합니다.

**Comment by aanoaa** [comment]
4452b29848046fcec0c071440bbccd5fa9f7571d
