### ISSUE TITLE
결제마감일자를 명확히 표시

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#94]
결제마감일자 및 시간을 조금 더 명확히 고지해주세요.
2017년 3월 2일 오전 10시가 지나면 주문이 자동 취소됩니다.

**Comment by aanoaa** [comment]
주문은 자동취소 되지 않습니다.
자동취소 기능을 원하시는 거라면 자동취소 기능을 만들어야 합니다.

하루 한번일괄로 취소하는 기능이겠죠 아마도..

**Comment by aanoaa** [comment]
> 2017년 3월 2일 오전 10시가 지나면 주문이 자동 취소됩니다.

2017년 3월 2일 오전 10시가 지나면 결제를 할 수 없습니다.

정도로 사용할 수 있습니다.
이유는 발송(예정)일을 맞출 수 없기 때문입니다.

**Comment by aanoaa** [comment]
@10001if 님이 적절한 문구를 답변해주신다고 합니다.

**Comment by 10001if** [comment]
주문한 품목을 0000년 00월 00일에 배송 받으려면, 2017년 3월 2일 오전 10시까지 결제가 완료되어야 합니다. 기한 내 결제가 되지 않으면 의류 발송이 불가능하며 해당시각 이후에는 결제를 진행할 수 없습니다.

**Comment by 10001if** [comment]
2017년 3월 2일 오전 10시까지 결제가 완료되어야 합니다. 부분은 볼드처리 요청드립니다.

**Comment by 10001if** [comment]
@aanoaa 0000년 00월 00일에 배송 받으려면 -> 대여자가 배송받는 날을 말합니다.

**Comment by aanoaa** [comment]
주문한 품목을 0000년 00월 00일에 배송 받으려면, **2017년 3월 2일 오전 10시까지 결제가 완료되어야 합니다.** 기한 내 결제가 되지 않으면 의류 발송이 불가능하며 해당시각 이후에는 결제를 진행할 수 없습니다.
