### ISSUE TITLE
결제취소가 아니됨

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#97]
카드결제취소가 아니된다고 합니다.

**Comment by aanoaa** [comment]
테스트한다고 모든 결제를 취소해서 발생한 일이 아닌가 싶습니다.
결제 취소액 한도가 있는게 아닐까 싶습니다.
지금도 여전히 그러한지 알아봐야 합니다.

**Comment by 10001if** [comment]
따로 이슈가 발생하지 않으므로 우선 닫도록 하겠습니다. 이슈가 추가로 발생하면 다시 열겠습니다.
