### ISSUE TITLE
배송완료상태로 변경되지 아니함

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-Share-Web#99]
확인이 필요합니다.

**Comment by 10001if** [comment]
@aanoaa 배송완료시 반송에 관한 안내가 이뤄지므로 필수적으로 진행되어야 하는 절차입니다. 빠른 확인 요청드립니다~

**Comment by aanoaa** [comment]
54090 주문서는 배달이 완료되었지만 배송완료 상태로 넘어가지 않았습니다.

**Comment by aanoaa** [comment]
택배추적(`shipped2delivered`) 프로그램의 오류입니다.

주문서의 상태는 `대여중`이면서 배송상태가 `배송중`인 주문서를 찾아야 하는데,
주문서의 상태가 `배송중`인 주문서를 찾고 있었습니다.

**Comment by aanoaa** [comment]
https://github.com/keedi/Parcel-Track-KR-CJKorea/pull/3

    requires 'Parcel::Track::KR::CJKorea', '0.005';

이 우선되어야 합니다.
아직 배포되지 않았습니다.

**Comment by 10001if** [comment]
@aanoaa 반납 안내에 대해 조금 더 적극적인 안내가 필요하다고 생각합니다. 다만, 배송완료시에는 반납 안내가 되는 것은 반드시 필요하다고 생각합니다. 빠른 작업 요청드립니다. ^^

**Comment by aanoaa** [comment]
[Parcel-Track-KR-CJKorea-0.005.tar.gz](https://cpan.metacpan.org/authors/id/K/KE/KEEDI/Parcel-Track-KR-CJKorea-0.005.tar.gz) 배포되었습니다.
